webpack/webpack-cli

- .travis.yml
- package.json
Will implement linting and travis
> Integrate travis & linting

- lib/transformations/loaders/__testfixtures__/loaders.input.js
- lib/transformations/loaders/loaders.js
Handling `-loader` suffix from #6 
Yes, updated the test case accordingly
No
> Feat - Adds -loader suffix after loader manipulation

- package.json
build/DX related change
Not required
Not required (I guess)
**Summary**
https://github.com/okonet/lint-staged allows running linters and fix your code even before you commit it. [Motivation](https://medium.com/@okonetchnikov/make-linting-great-again-f3890e1ad6b8#.8qepn2b5l)
Nope.
> build: Add lint-staged with autofix eslint task as a pre-commit hook.

- CONTRIBUTING.md
- README.md
Only adds the roadmap to the readme, so we all have the clear goal of the project.
N/A
**Summary**
In order to have a clear Roadmap to all users and
contributors, adding now a section for it in the
Readme.
No
> docs: Add roadmap and format readme

- CONTRIBUTING.md
Updates the contributing guide grammar
N/A
N/A
**Summary**
N/A
No.
> (docs): Make the contributing guide grammar better

- lib/transformations/loaderOptionsPlugin/__snapshots__/loaderOptionsPlugin.test.js.snap
- lib/transformations/loaderOptionsPlugin/__testfixtures__/loaderOptionsPlugin-3.input.js
- lib/transformations/loaderOptionsPlugin/loaderOptionsPlugin.js
- lib/transformations/loaderOptionsPlugin/loaderOptionsPlugin.test.js
Bugfix
**Summary**
Solves #76, #69 
> fix: add safe traverse to loaderoptionsplugin

- lib/creator/transformations/entry/__snapshots__/entry.test.js.snap
- lib/creator/transformations/entry/__testfixtures__/entry-0.input.js
- lib/creator/transformations/entry/entry.test.js
- lib/transformations/defineTest.js
> Init ast/tests

- INIT.md
- lib/creator/yeoman/webpack-generator.js
Simple language clarification regarding entry points.
N/A
Yes
**Summary**
The existing verbiage was unclear as it stated the number of bundles vs entry points.
N/A
> Adjusted verbiage regarding entry points

- lib/creator/yeoman/utils/entry.js
I know it's super trivial, but boy my 11th grade teacher sure did permanently burn the spelling of that word into my head.
It fixes the spelling of "separated" in the one of the prompts in the `init` workflow.
I did not, but could probably give Mr. Kelly a call to confirm if you'd like.
Not relevant.
**Summary**
The motivation for making this change was to add polish for a very promising tool that countless users are likely to use. 
No.
> Fixed spelling of "separated"

- lib/transformations/__snapshots__/index.test.js.snap
- lib/transformations/__snapshots__/utils.test.js.snap
- lib/transformations/bannerPlugin/__snapshots__/bannerPlugin.test.js.snap
- lib/transformations/extractTextPlugin/__snapshots__/extractTextPlugin.test.js.snap
- lib/transformations/loaderOptionsPlugin/__snapshots__/loaderOptionsPlugin.test.js.snap
- lib/transformations/loaders/__snapshots__/loaders.test.js.snap
- lib/transformations/loaders/__testfixtures__/loaders-7.input.js
- lib/transformations/loaders/__testfixtures__/loaders-8.input.js
- lib/transformations/loaders/loaders.js
- lib/transformations/loaders/loaders.test.js
- lib/transformations/removeJsonLoader/__snapshots__/removeJsonLoader.test.js.snap
- lib/transformations/removeJsonLoader/__testfixtures__/removeJsonLoader-0.input.js
- lib/transformations/removeJsonLoader/__testfixtures__/removeJsonLoader-1.input.js
- lib/transformations/removeJsonLoader/__testfixtures__/removeJsonLoader-2.input.js
- lib/transformations/removeJsonLoader/__testfixtures__/removeJsonLoader-3.input.js
- lib/transformations/removeJsonLoader/removeJsonLoader.js
- lib/transformations/utils.js
- lib/transformations/utils.test.js
- package.json
bugfix
Yes
Not relevant
**Summary**
This PR is a bug fix for #90 
No
> Fix: loader transform should produce a valid config

- lib/creator/transformations/devServer/__snapshots__/devServer.test.js.snap
- lib/creator/transformations/devServer/__testfixtures__/devServer-0.input.js
- lib/creator/transformations/devServer/__testfixtures__/devServer-1.input.js
- lib/creator/transformations/devServer/devServer.js
- lib/creator/transformations/devServer/devServer.test.js
- lib/creator/transformations/index.js
- package-lock.json
- package.json
> ast for devServer

- lib/creator/transformations/devServer/devServer.test.js
- lib/creator/yeoman/webpack-generator.js
- lib/utils/package-manager.js
- lib/utils/package-manager.spec.js
- lib/utils/resolve-packages.js
> use yarn or npm for offline and/or default usage

- .babelrc
- MIGRATE.md
- lib/generators/init-generator.js
- lib/generators/utils/module.js
- package-lock.json
- package.json
Closes https://github.com/webpack/webpack-cli/issues/196
> Use env preset

- test/binCases/configFile/plugins-presedence/stdin.js
- test/binCases/entry/multi-file/stdin.js
- test/binCases/entry/named-entry/stdin.js
- test/binCases/entry/non-hyphenated-args/stdin.js
Bugfix existing tests.
Yes
No
**Summary**
Fixing some failing tests, probably due to the new version of webpack
No
> Fixing failing tests

- bin/config-yargs.js
- test/binCases/mode/none/index.js
- test/binCases/mode/none/stdin.js
- test/binCases/mode/none/test.opts
bugfix
yes
N/A
**Summary**
add `none` to choices of `--mode`
no
> cli(bugfix): Allow mode "none" in CLI

- lib/commands/init.js
- lib/init/transformations/index.js
- lib/utils/modify-config-helper.js
- package.json
> ast(init): fix init command

- .cz-config.js
- build/changelog-generator/index.js
Enhancement
**Summary**
Update commit type `new_feature` to `feat`.
Previous:
Now:
No
> Commitlint

- .cz-config.js
Fix
No
No
**Summary**
It adds `fix` to the whitelist of possible commit messages
No
The last PR broke the build because `fix` was not inside the whitelist. This should fix the problem
> fix: adding 'fix' to whitelist

- .gitignore
- lib/utils/package-manager.js
One code tweak and a change to the .gitignore file.
No.
n/a
**Summary**
Addresses a final piece of pr feedback from #265 and adds vim files to the gitignore.
No.
n/a
> Fix global path require & add vim swap files to gitignore

- SCAFFOLDING.md
Ench
Y
Y
**Summary**
Addition to scaffolding docs
> chore(scaffolding): update docs

- .cz-config.js
**Summary**
- cz-config
- `fix` type description
- reorder
- clean `deps` type
> misc(cz): fix type description

- package.json
Chore. Added reports to catch correctly the code coverage of the `cli`
No
No
**Summary**
Fixed codecoverage
No
> chore(coverage): added reporters inside package.json

- lib/generators/add-generator.js
Bugfix
**Summary**
`add` command generator configuration write to yeoman file
Example `yo-rc.json` after running adding `entry`:
No
Related #323
> cli(add): write configuration to yeoman file

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
> chore(templates): Update issue templates 

- .travis.yml
> chore(travis): run lockfile cmds on tests

- .travis.yml
Build related.
No, none needed.
No.
**Summary**
Node.js 10 was released and will become the new LTS branch so we should test webpack-cli on it too.
-
No.
> chore(travis): add Node.js 10

- .appveyor.yml
- .travis.yml
Bugfix for build / CI.
**Did you add tests for your changes?** 
No, none needed.
No.
**Summary**
Currently `npm install` runs on CI in addition to `npm ci`.
Only `npm ci` should run. For this the needed commands should be in the install task.
No.
> chore(travis): move npm ci to install task

- package-lock.json
- package.json
> chore(package): update jest-cli to version 23.0.1

- packages/utils/__snapshots__/recursive-parser.test.js.snap
- packages/utils/recursive-parser.test.js
> tests(parser): fix recursive-tests signature

- .eslintignore
- test/BinTestCases.test.js
- test/binCases/config-name/found-many/stdin.js
- test/binCases/config-name/found-one/stdin.js
- test/binCases/config-type/array/stdin.js
- test/binCases/configFile/plugins-precedence/stdin.js
- test/binCases/configFile/profile/stdin.js
- test/binCases/entry/cli-override/stdin.js
- test/binCases/entry/multi-file/stdin.js
- test/binCases/entry/named-entry/stdin.js
- test/binCases/entry/non-hyphenated-args/stdin.js
- test/binCases/env/complex/stdin.js
- test/binCases/env/string/stdin.js
- test/binCases/errors/issue-5576/stdin.js
- test/binCases/errors/parse/stdin.js
- test/binCases/mode/none/stdin.js
- test/binCases/output/output-argument/stdin.js
- test/binCases/stats/single-config/stdin.js
When running test on master locally all binTestCases failed. Refactored some things.
Y
na
**Summary**
Let's see what the CI says
naw
> fix(binTestCases): refactor to make tests pass

- .appveyor.yml
- .gitignore
- .travis.yml
- package-lock.json
- package.json
- packages/utils/npm-exists.test.js
- packages/utils/package.json
- packages/webpack-scaffold/package.json
- test/BinTestCases.test.js
Adds coverage and `binTestCases` to run before any mono-repo pkg gets tested.
Y
na
**Summary**
Let's wait for CI
nope
=)
> tests(coverage): fix coverage

- .travis.yml
- commitlint.config.js
- package-lock.json
- package.json
Adds more plugins to trigger versions et al.
na
na
**Summary**
Adds plugins to fine-grain publishes
no
=)
> chore(semantic): Semantic release plugins 

- bin/convert-argv.js
The new version of webpack-cli adds webpack to the global process object. 
This causes applications such as webpack-dev-derver to break since it assumes that `process.webpackModule` is available in the current process.
This pr simply reverts this assumption.
**Summary**
> require validateSchema and optionsValidationError from webpack

- packages/generators/init-generator.js
- packages/generators/utils/module.js
Some minor stuff that's left from refactoring efforts.
> cli(init): don't use uglify on prod config

- test/binCases/watch/info-verbosity-verbose/stdin.js
It fixes mixed tabs/spaces in a single test file.
No
Irrelevant.
**Summary**
Reading through the changelog for v3.0.5 it was quite clear to notice one of the files was indented with two spaces, I normalized it to tabs.
No
> tests: Fix mixed spaces/tabs in stdin.js

- .travis.yml
**Summary**
Greenkeeper supports lockfile updates starting from version 2.
[Ref](https://blog.greenkeeper.io/greenkeeper-support-for-lockfiles-9d9c282efcbe).
Fixes #509
> chore(greenkeeper): support for lockfiles

- package.json
Removes chore from pushing a patch.
N/a
n/a
**Summary**
n/a
no
=]
> misc: remove chore from pkg.json

- CHANGELOG.md
Fixes #495 
N/a
Yes
**Summary**
Adds a changelog for v3 
no
=)
> chore: add changelog for v3

- package.json
> chore: remove semantic-release

- .github/ISSUE_TEMPLATE/Bug_report.md
Chore
No
No
**Summary**
Fixed small bug inside the template for bugs
No
No
> chore(template): tiny fix for bug template

- test/binCases/configFile/plugins-precedence/stdin.js
- test/binCases/entry/multi-file/stdin.js
- test/binCases/entry/named-entry/stdin.js
> tests(fix): bin test outputs

- package.json
Chore 
No
No
**Summary**
Removed `inquirer` as it is not part of the plain cli.
No
> chore(deps): removing inquirer as default package

- packages/generate-loader/.npmignore
- packages/generate-plugin/.npmignore
Bugfix
**Summary**
We generate plugins and loader template from the `example` and `test` directories which were excluded previously from the npm package.
No
Fixes #572
> fix(generate-loader/plugin): include example template

- package-lock.json
- package.json
- packages/add/package-lock.json
- packages/generate-loader/package-lock.json
- packages/generate-plugin/package-lock.json
- packages/generators/package-lock.json
- packages/info/package-lock.json
- packages/init/package-lock.json
- packages/make/package-lock.json
- packages/migrate/package-lock.json
- packages/remove/package-lock.json
- packages/serve/package-lock.json
- packages/update/package-lock.json
- packages/utils/package-lock.json
- packages/webpack-scaffold/package-lock.json
Lerna version upgrade
No
Not relevant
**Summary**
lerna version upgrade
No
> fix(package): Bump lerna version

- README.md
This proposes a status badge in the README.md for the Azure Pipelines CI build.  Thank you for considering!
> Add a status badge for the azure pipelines CI build

- package.json
build related change 
NA
NA
**Summary**
Remove package-lock.json
No
NIL
> chore(fix): fix clean all script

- package-lock.json
- package.json
- packages/add/package-lock.json
- packages/generate-loader/package-lock.json
- packages/generate-plugin/package-lock.json
- packages/generators/package-lock.json
- packages/info/package-lock.json
- packages/init/package-lock.json
- packages/make/package-lock.json
- packages/migrate/package-lock.json
- packages/remove/package-lock.json
- packages/serve/package-lock.json
- packages/update/package-lock.json
- packages/utils/package-lock.json
- packages/webpack-scaffold/package-lock.json
Upgrade
**Summary**
Fixes the changes in husky major version upgrade
Fixes #610
> chore(deps): upgrade husky

- packages/init/README.md
documentation
N/A
Yes
**Summary**
No
> docs(init): update init documentation

- bin/cli.js
- bin/config-yargs.js
- packages/utils/npm-packages-exists.test.js
- packages/utils/recursive-parser.test.js
- test/binCases/watch/info-verbosity-verbose/stdin.js
Fixes #570
Yes
Yes
**Summary**
Closes #570 
No
💙
> fix(tapable): fix hook options

- CONTRIBUTING.md
- package.json
Docs and guide update
N/A
Yes
**Summary**
Simplifies setup process, add `postinstall` script to bootstrap packages.
No
Closes #619
> chore: update contributing docs, add script

- .travis.yml
Build related change 
**Summary**
Remove Node 7 check as it's not a LTS release and not officially supported.
No
As per discussed in #626
> chore(travis): remove node 7

- packages/init/README.md
> fix critical error

- package-lock.json
- package.json
- packages/generators/package-lock.json
- packages/generators/package.json
- packages/migrate/package-lock.json
- packages/migrate/package.json
- packages/utils/package-lock.json
Update dependencies
No
No
**Summary**
Pin webpack version to 4.x.x everywhere. If we include `~` or `^`, greenkeeper will try to update every new version of webpack.
> #655 Greenkeeper did not create a PR since the initial build failed and after updating to the newer version, it did not create a PR automatically, only updated the code on its branch.
No
Closes #655, #656
> chore(dependencies): pin to webpack 4.x.x

- azure-pipelines.yml
Fixes nproc on azure
Y
N/A
**Summary**
N/A
No
:)
> chore: add nproc in azure

- MIGRATE.md
- packages/generators/init-generator.ts
- packages/generators/utils/module.ts
- packages/migrate/loaders/__snapshots__/loaders.test.js.snap
- packages/migrate/loaders/__testfixtures__/loaders-7.input.js
Support for babel 7 and babel-loader 8
Yes
Yes
**Summary**
Fixes #676
> cli(loaders): support for babel 7, babel-loader 8

- packages/generators/add-generator.ts
- packages/remove/index.ts
- packages/update/index.ts
- packages/utils/modify-config-helper.ts
Fixes errors thrown when trying to invoke `update`, `remove` and scaffold commands with a config name.
Yea
N/A
**Summary**
N/A
No
Fixes #679
> cli: Fix file lookup on generators & missing module

- .travis.yml
Build related change
N/A
N/A
**Summary**
> chore(travis): add wait timer for installation, remove redundant script

- packages/webpack-scaffold/README.md
Update webpack-addon to `@webpack-cli/webpack-scaffold`
Left installation part for *First-time contributors*
Docs
N/A
Yes
**Summary**
Made just for quick navigation throughout readme
> docs: add Index and minor changes

- packages/README.md
Documentation
N/A
Yes
**Summary**
Solves #713
No
No
> docs: add packages README

- packages/generators/package.json
Security issue see #721 
No
No
No
> fixx: security vulnerability npm release 0.1.2 

- packages/generators/README.md
> docs: update generators README

- packages/webpack-scaffold/README.md
Documentation PR
No
yes
**Summary**
Updated documentation for webpack-scaffold installation #712 
No
Closes #712
> Add installation guide for packages/webpack-scaffold

- azure-pipelines-template.yml
- azure-pipelines.yml
- bin/cli.js
- bin/convert-argv.js
- junit.xml
- package-lock.json
- package.json
- scripts/opencollective.sh
- test/binCases/watch/info-verbosity-off/info-verbosity-off.test.js
- test/binCases/watch/info-verbosity-verbose/info-verbosity-verbose.test.js
- test/binCases/watch/multi-config-watch-opt/multi-config-watch-opt.test.js
- test/binCases/watch/multi-config/multi-config.test.js
- test/binCases/watch/single-config-watch-opt/single-config-watch-opt.test.js
- test/binCases/watch/single-config/single-config.test.js
Fixes #737  #743 and #739 
N/A
N/A
**Summary**
Emits logs to stderr, adds own bash script for opencollective to reduce library size and closes compiler to purge cache in webpack v5.
No
:)
> fix: close compiler, own sh script and output clearing

- package-lock.json
- package.json
- packages/info/package-lock.json
- packages/init/package-lock.json
- packages/migrate/package-lock.json
- packages/utils/package-lock.json
- packages/webpack-scaffold/package-lock.json
Upgraded vulnerable packages
N/A
N/A
**Summary**
No
> chore(deps): fix vulnerabilities

- package-lock.json
- package.json
Upgrade lerna to fix vulnerabilities
ISSUES CLOSED: #822
deps 🆙 
Yes
NA
**Summary**
Upgraded lerna to fix vulnerabilities, there are two more which will be fixed once `@commitlint/prompt-cli` is updated
No
NA
> chore(deps): upgrade lerna to fix vulnerabilities & update webpack-dev-server

- README.md
Links from webpack.js.org
documentation change
N/A
inception
**Summary**
> docs(README): update scaffolding links

- junit.xml
- packages/utils/defineTest.ts
- packages/utils/find-root.ts
- packages/utils/scaffold.ts
Refactoring
**What existing problem does the pull request solve?**
Refined codebase, better code readability.
Nopes
Feedback appreciated :+1:
> misc: Refactoring utils

- bin/cli.js
Fixes open collective prompt `EPERM` error.
I don't have access to a Linux machine at the moment, it would be nice if anyone could test this on Linux. [Here](https://github.com/fredj/webpack-atime)'s the repository. 
@sbrunner, @fredj :)
**Summary**
Closes #870
> fix(opencollective-prompt): fix EPERM error

- .github/FUNDING.yml
add sponsor button
ISSUES CLOSED: #894
added sponsor button
yes
NA
**Summary**
add github sponsor button
No
> chore(github): add sponsor button

- README.md
docs
yes
**Summary**
This PR fixes the link to `webpack-scaffold` in the readme.
no
> docs: fix link to webpack-scaffold

- packages/serve/index.ts
refactoring
Nope
Nope
**Summary**
This is an attempt to make the code-base a lot cleaner by removing redundant code.
Nope
> chore: refactor serve command action handler

- packages/migrate/removeDeprecatedPlugins/removeDeprecatedPlugins.ts
**Description**
While running all the tests in the for the repo, you might end up with a console error warning, like this :arrow_down: .
refactor
**Summary**
Errors while running the test.
No.
**Proposed  Behaviour**
> chore(migrate): fixes console error while running tests.

- package-lock.json
- package.json
bugfix
kinda
no
**Summary**
Updates pkg lock to see if pipeline is a single run error
naw
I like turtles
> chore: fix azure

- packages/info/index.ts
refactoring
Nope
Nope
**Summary**
Added type definitions for what `envinfo` returns.
Nope
> feat(chore): Added type definitions for the data returned by envinfo

- package-lock.json
- packages/generators/__tests__/add-generator.test.ts
- packages/generators/add-generator.ts
- packages/generators/init-generator.ts
- packages/generators/utils/index.ts
use all utils from root file in generators
refactor
NA
**Summary**
Import all utils from the utils root, much cleaner
No
> chore(refactor): use all utils from the root file in generators

- package.json
feature
yes
NA
**Summary**
Format staged code on precommit for both `.ts` and `.js` files
no
> [infra]: format staged code on precommit

- packages/generators/add-generator.ts
refactored the code to suppport for better user input handling
refactoring/bugfix
NA
NA
**Summary**
The reference of the discussion can be found in https://github.com/webpack/webpack-cli/pull/910#discussion_r290324895
and in this https://github.com/webpack/webpack-cli/issues/906
No
NA
> chore: refactored the add-generator

- packages/utils/ast-utils.ts
- packages/utils/modify-config-helper.ts
> chore(utils): refactor ast utils and output message

- .github/CONTRIBUTING.md
updated the docs for the test
For the sake of https://github.com/webpack/webpack-cli/issues/904
docs
> docs(contributing): updates the docs for the test

- packages/init/init.ts
- packages/utils/scaffold.ts
- packages/utils/types/Error.ts
- packages/utils/types/index.ts
refactor
Yes
NA
**Summary**
fixed wrong file names, single export
No
> [utils]: refactor export types to index file

- .github/CONTRIBUTING.md
See changes in action :point_right: https://github.com/pranshuchittora/webpack-cli/blob/docs/contributing/.github/CONTRIBUTING.md
docs/refactoring
**Summary**
The contributing doc was quite repetitive, as it included separate sections for npm & yarn environment. WIth this PR, I combined those into one.
> docs(contributing): combines separate sections for yarn and npm into one.

- bin/utils/prompt-command.js
refactoring/bugfix
NA
NA
**Summary**
removed the commented code
fixes #950 
No
NA
> Fix: command mismatching, running always init command

- packages/init/README.md
Documentation
NA
Yes
**Summary**
Added `--auto` in docs for `init` package
NA
NA
> docs: added auto flag in docs for init command

- test/binCases/config-type/array/array.test.js
Bugfix
No
No
**Summary**
There is a small typo in a test file.
No
> fix: change "usr strict" to "use strict"

- packages/README.md
Docs
N/A
Yes
**Summary**
Removed description of `add`, `remove`, `update` and `make` packages
No
*Changes in the documentation for **webpack-cli v3.x***
> docs: remove removed packages description

- packages/utils/scaffold.ts
fixed typo in the import statement
chore
Nopes
> chore(utils): Fix path in scaffold util

- packages/utils/npm-packages-exists.ts
Closes #1001 
N/A
N/A
**Summary**
No
No
> fix: make init resolve linked packges

- lib/groups/config.js
- package-lock.json
- package.json
bugfix
No
No
**Summary**
The package `command-line-usage` was missing for `webpack-cli help`. Also a mistake I found in calling a method.
No
Edit: Also upgraded `import-local` due to issue explained here: https://github.com/webpack/webpack-cli/pull/1009
> [NEXT]: fix missing package, fix bad function call

- packages/serve/index.ts
refactoring
N/A
N/A
**Summary**
Minor grammatical fix.
Nope
> fix(serve): minor grammatical correction

- cli.js
feature
Nope
N/A
**Summary**
Set the update interval to be 1 week.
As per this [comment](https://github.com/webpack/webpack-cli/pull/888#issuecomment-495177892)
Nope
related #888
> chore(notifier): update notifier frequency

- packages/generators/init-generator.ts
refactoring
Nope
N/A
**Summary**
Remove extraneous ternary logic.
Nope
N/A
> fix(chore): remove extraneous ternary logic

- README.md
Docs update
N/A
N/A
**Summary**
Minor enhancements to `Readme.md`
- Included a badge welcoming PR's
- Sorted the badge url's within `Readme.md` alphabetically
N/A
> feat(docs): Minor tweaks

- test/version/version-multi-args.test.js
- test/version/version-single-arg.test.js
refactoring
Yes
No
**Summary**
NA
NO
NO
> chore: update version test

- package-lock.json
- package.json
add missing dep
ISSUES CLOSED: #1040
added back the missing dep
Yep
NA
**Summary**
Added the missing dep to commit.
No
> fix(deps): add missing cz-customizable dep to allow committing

- lib/groups/help.js
fix var name
yes
NA
**Summary**
Follow up of - https://github.com/webpack/webpack-cli/pull/1036
Fixed the remaining instances.
No
NA
> chore(cli): fix var name to correct meaning

- lib/groups/help.js
refactor help
some refactoring to the  help class
Yes
NA
**Summary**
* remove unused fns
* destructured repeated fn to make it more readable
No
> chore(help): refactor help for more cleaner code

- lib/groups/stats.js
refactoring
Nope
N/A
**Summary**
Refactor code resulting in a much concise version.
N/A
N/A
> feat(stats): refactor code

- lib/bootstrap.js
refactoring
Nope
N/A
**Summary**
refactor code
N/A
> chore(bootstrap): refactor code

- packages/generators/addon-generator.ts
> chore: only output message on error

- lib/groups/advanced.js
refactoring
No, May need to though
NA
**Summary**
use webpack log for displaying error
No
No
> chore: replace console logs with webpack log

- test/utils/exec-in-directory.js
refactoring
Nope
N/A
**Summary**
Minor tweak to the existing code block.
Nope
N/A
> chore: minor tweak

- test/version/version-multi-args.test.js
typo fix
N/A
N/A
**Summary**
Fixed minor typo.
Nope
N/A
> chore: fix minor typo

- lib/utils/group-helper.js
refactoring
Nope
N/A
**Summary**
Beautify code.
Nope
N/A
> chore(GroupHelper): minor tweak

- packages/init/index.ts
refactoring
N/A
N/A
**Summary**
Rephrased the respective comment block which sounds better.
N/A
N/A
> chore(init): rephrase comment

- lib/utils/compiler.js
refactor emoji rendering
refactor emoji rendering logic, save loops.
No
NA
**Summary**
Compare one whether to render emojis or not
No
> chore(compiler): refactor emoji rendering logic in compiler

- lib/utils/group-helper.js
refactoring
Nope
N/A
**Summary**
minor code refactor
Nope
N/A
> feat: refactor logic

- lib/commands/external.js
refactoring
Nope
N/A
**Summary**
Refactored the specific code block resulting in concise code.
Nope
N/A
> chore: minor code refactor

- test/config/.gitignore
- test/config/config-type/array/a.js
- test/config/config-type/array/configArray.test.js
- test/config/config-type/array/webpack.config.js
- test/config/config-type/function/a.js
- test/config/config-type/function/configFunction.test.js
- test/config/config-type/function/webpack.config.js
- test/config/config-type/promise/a.js
- test/config/config-type/promise/configPromise.test.js
- test/config/config-type/promise/webpack.config.js
Tests
Yea
NA
**Summary**
https://github.com/webpack/webpack-cli/issues/1012
Added tests for the different export types of the config file. 
Types checked 
- Array
- Function
- Promise
No
> Tests: added tests with different config type

- bin/cli.js
Bugfix
No
Not required
**Summary**
This pull request is similar to this one: https://github.com/webpack/webpack/pull/6193 merged two years ago, but in Webpack main repository.
It fixes this issue: https://github.com/webpack-contrib/sass-loader/issues/759 
See the previous pull request for more details.
Related issues: 
https://github.com/nodejs/node/issues/17872 
https://github.com/webpack-contrib/sass-loader/issues/523
No
> fix: fix webpack hanging under certain circumstance

- package.json
- test/help/help-single-arg.test.js
Tests
No
No
**Summary**
Test color flag for help output
No
No
> test: add test for color in help

- commitlint.config.js
- lib/groups/config.js
typo fix
N/A
N/A
**Summary**
Minor typo fixes.
N/A
N/A
> chore: minor typographical fixes

- lib/groups/config.js
- lib/utils/compiler.js
- lib/utils/zero-config.js
- test/env/array/array-env.test.js
- test/env/object/object-env.test.js
refactoring
Nope
N/A
**Summary**
Minor stylistic code refactoring.
Nope
N/A
> chore: minor stylistic refactor

- packages/info/configParser.ts
- smoketests/watch/watch.array.smoketest.js
- smoketests/watch/watch.single.smoketest.js
Fix
No
N/A
**Summary**
Add missing types in `.ts` files and ignore redundant warnings for `.js` files.
Not connected but #940 can be closed after this as this PR intends to remove all warnings.
No
N?A
> fix: warnings on lint

- packages/webpack-scaffold/README.md
Documentation fix
Yup
Yup
**Summary**
Removed links that were not in scope of the heading they were in.
No
N/A
> docs(webpack-scaffold): remove unrelated links

- lib/utils/compiler.js
- test/utils/test-utils.js
Refactor
N/A
N/A
**Summary**
remove async/awaits where no promises were there to wait for
No
No
> refactor: remove redundant async/awaits

- lib/utils/compiler.js
- lib/utils/group-helper.js
- lib/utils/process-log.js
- lib/utils/zero-config.js
Minor code refactoring.
> Wow the PR number is binary format of `13`, just in case if you are curious 😉 
NA
NA
**Summary**
Few things will provide us minor performance wins and simply to get back in pace with the code base.
NA
> [Minor] code refactors 

- lib/utils/commands.js
- lib/webpack-cli.js
refactoring
Nope
N/A
**Summary**
Make use of object destructuring assignment approach and a couple of other minor tweaks.
Nope
N/A
> chore: minor code refactoring

- lib/bootstrap.js
- Refactor
- Not relevant
- Not relevant
**Summary**
Solves `SyntaxError: Identifier 'isCommandUsed' has already been declared`
No
> fix: Remove duplicate definition of function

- .gitignore
- packages/serve/package-lock.json
- packages/serve/package.json
- test/config/serve-basic/index.js
- test/config/serve-basic/node_modules/@webpack-cli/serve/index.js
- test/config/serve-basic/webpack.config.js
- test/serve/serve-basic.test.js
- test/utils/test-utils.js
Tests
Yes
N/A
**Summary**
/cc @evilebottnawi 
This adds basic tests for the `serve` command, confirming that it runs and applies the provided CLI flags.
There is a slightly hacky method I used to simulate having the package `@webpack-cli/serve` in your node_modules folder. Better ideas for how to do this are welcome.
No
> tests(serve): add serve tests

- lib/webpack-cli.js
- refactor
- Not relevant
- Not relevant
**Summary**
Remove the await keyword for synchronous function calls.
Nope.
> fix: Remove redundant await keyword

- lib/webpack-cli.js
- refactor
- Not relevant
- Not relevant
**Summary**
Minor change to use ES6 object initializer shorthand to add the mode type in WebpackCLI.resolveGroups method
no
> fix: Use ES6 object initializer shorthand

- lib/webpack-cli.js
- refactor
- not relevant
- not relevant
**Summary**
1. `this.groups.push(GroupInstance)` was common to both if and else clause
2. added one liner ternary operation instead of if else to set mode value.
- Nope.
<!-- If this PR introduces a breaking change, please describe the impact and a migration path for existing
> fix: refactor redundant code

- package.json
Update Dependences
N/A
N/A
**Summary**
Some unnecessary dependencies were added to the beta release. Removed it based on feedback provided here https://github.com/webpack/webpack/issues/9802#issuecomment-565820225
No
> chore: update dependences

- .github/workflows/nodejs.yml
CI
N/A
No
**Summary**
Closes #1149 
> chore(actions): add webpack version

- .github/workflows/nodejs.yml
bugfix
N/A
N/A
**Summary**
There was an error in actions workflow
> fix: update webpack installation

- package-lock.json
- package.json
Dependency update
Nope
Nope
**Summary**
Updated terser-webpack-plugin to `v2.3.2`
Nope
N/A
> chore(deps): Updated terser-webpack-plugin

- packages/serve/args-to-camel-case.ts
- test/serve/args-to-camel-case.test.js
tests
Yes
N/A
**Summary**
Add tests for a util that is used in the `serve` package
No
> tests(serve): add tests for args to camel case util

- package-lock.json
- package.json
- packages/generators/__tests__/init-generator.test.js
- packages/generators/init-generator.ts
fix and test
Yes
N/A
**Summary**
This makes use of the `yeoman-test` package, explained here: https://yeoman.io/authoring/testing.html.
It tests that the init generator is working as expected. For now, I only created one test, but I will add more to experiment with different configurations.
I also made changes to ensure that the init generator is behaving as expected, as there were some issues I found.
No, the changes are all fixes
> Add init-generator test for yeoman generator

- .cz-config.js
- INIT.md
- README.md
- packages/README.md
- packages/init/README.md
- test/version/version-multi-args.test.js
migrate init package docs
Ref - https://github.com/webpack/webpack-cli/issues/1154
docs migration for init package 
NA
Yes
**Summary**
* package docs for create command migrated from init
No
> docs(create): migrate init package docs

- lib/utils/cli-flags.js
feature
Nope
Nope
**Summary**
Added `link` field to rest of the cli flags which leads to the respective resource. Follow up of #1141
Nope
N/A
> chore: Updated CLI flags info with additional links

- test/help/help-commands.test.js
- test/help/help-flags.test.js
More tests corresponding to help for commands and flags
Yes
Not required
**Summary**
Add tests as describes above.
No
No.
> test(help): add more tests to help

- packages/init/index.ts
- packages/init/package-lock.json
- packages/utils/modify-config-helper.ts
handle package creation errors
ISSUES CLOSED: #1151
handle create package errors when
No, will add tests separately
NA
**Summary**
Handle package creation errs when working in a package dir
No
> fix(create): handle create package errors gracefully

- packages/utils/package-lock.json
- packages/utils/package.json
build related change
no
no
**Summary**
Move jest to dev-deps (closes #1190)
no
> Move jest to dev-deps

- test/node/node.test.js
test update
Yeah
N/A
**Summary**
Follow up of #1195
Nope
N/A
> chore: Added test case for providing unknown flags along with --node-args

- packages/generators/package-lock.json
- packages/generators/package.json
- packages/init/package-lock.json
- packages/utils/modify-config-helper.ts
- packages/utils/package-lock.json
- packages/utils/package.json
chore, refactor
not yet
N/A
**Summary**
This entirely fixes: https://github.com/webpack/webpack-cli/issues/901
It seems that yeoman stopped expecting the `name` property in `package.json` in a more recent version of their generator package.
No
> Upgrade yeoman in generators/utils, slight generator error handling changes

- test/node/node.test.js
test update
Yes
Nope
**Summary**
Added test cases for the following scenarios:-
- If the user didn't supplied a value to the `max-old-space-size` flag.
- If the user supplied an invalid value to the `max-old-space-size` flag.
Nope
N/A
> chore: test cases for --max-old-space-size passed along with --node-args flag

- test/default/default.test.js
test update
Yep
Nope
**Summary**
Added test case for passing in unknown flags.
Nope
N/A
> feat: test case for passing in unknown flags

- CHANGELOG_v3.md
Docs
Not needed
Yes, updated changelog of v3
**Summary**
Updated changelog of v3
> chore(cli): updated changelog of v3

- package-lock.json
- package.json
- packages/generators/__tests__/loader-generator.test.ts
add tests for loader generator
tests
Yes
NA
**Summary**
* Add tests for loader generator
No
Will write for plugin-generator after this.
> tests(loader-generator): add tests for loader generator

- package-lock.json
- test/source-map/object/source-map-object.test.js
Adds greater than for a parallel test
Yes
N/A
**Summary**
Sec patch and fix parallel test
N/A
> tests(sourcemap): fix flaky stats statement and patch versions

- .github/CONTRIBUTING.md
- .gitignore
> chore: ignore package-lock.json and remove its references

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
> chore: update Bug_report & Feature_request Templates

- packages/logger/package.json
Bugfix
No 
No
**Summary**
Fixes the files to push to npm for logger
No
> chore(logger): fix npm files to publish

- yarn.lock
yarn.lock file changed on setting up the repo as mentioned in CONTRIBUTING.md
Minor change in `yarn.lock` on `$ yarn bootstrap` while setting up the repo
N/A
N/A
No
> fix: yarn.lock diff on setup

- package.json
chore
Yes
NA
**Summary**
- remove stale entries from root package.json since we moved cli to it's own package
No
> chore: 🤖 remove stale entries from root package.json

- README.md
`webpack-cli` ~~`create`~~ `init`
NA
Yes
**Summary**
No
NA
> docs: ✏️ fix init command in README

- .github/workflows/nodejs.yml
- package.json
- packages/generate-loader/.npmignore
- packages/generate-loader/package.json
- packages/generate-plugin/.npmignore
- packages/generate-plugin/package.json
- packages/generators/.npmignore
- packages/generators/package.json
- packages/info/.npmignore
- packages/info/package.json
- packages/init/.npmignore
- packages/init/package.json
- packages/logger/.eslintrc
- packages/logger/.npmignore
- packages/logger/package.json
- packages/serve/package.json
- packages/utils/.npmignore
- packages/utils/package.json
- packages/webpack-cli/.npmignore
- packages/webpack-cli/package.json
- packages/webpack-scaffold/.npmignore
- packages/webpack-scaffold/package.json
- yarn.lock
It should fix files that are published on npm
Not needed
Not needed
**Summary**
> chore: fixes the publishing files while running npm

- README.md
> feat(README): Node CI badge added

- README.md
> docs(readme): reflect branch next

- packages/webpack-cli/lib/groups/ConfigGroup.js
refactor
NA
NA
**Summary**
removed stale imports from `ConfigGroup.js`
No
> chore(webpack-cli): remove stale imports from configGroup

- test/defaults/with-config-and-entry/default-with-config.test.js
- test/entry/config-entry/entry-with-command/entry-with-command.test.js
- test/entry/config-entry/entry-with-config/entry-with-config.test.js
It fixes the CI
Fixed them
Not needed
**Summary**
> tests: fix tests

- packages/serve/src/args-to-camel-case.ts
- packages/utils/src/ast-utils.ts
- packages/webpack-cli/lib/bootstrap.js
- test/env/array/array-env.test.js
- test/env/object/object-env.test.js
Fixes #1305 
NA
NA
**Summary**
Fixed all typos.
NO
NA
> chore: fix typos across the project

- CODE_OF_CONDUCT.md
docs: add a missing link to code_of_conduct.md
not required.
not required.
**Summary**
add https://github.com/orgs/webpack/teams/core-team to @webpack-core phrase
motivation: missing link fix.
no
resolves #1328
> docs: add core-team link to CODE_OF_CONDUCT.md

- .github/CONTRIBUTING.md
updated CONTRIBUTING.md table-of-contents.
NA
yes
**Summary**
NA
NA
> docs(contributing): update table of contents

- CODE_OF_CONDUCT.md
docs update
N/A
**Summary**
Use a consistent style for formatting. Follow up of #1331
Nope
N/A
> [Docs]: follow a consistent format

- README.md
NA
YES
**Summary**
Updated table of contents with missing `supported arguments and commands section`
NO
NA
> docs(readme): update table of contents

- .github/CONTRIBUTING.md
- README.md
- packages/generate-plugin/templates/src/_index.js.tpl
- packages/generators/__tests__/plugin-generator.test.ts
general corrections and improvements in documentation.
YES.
Yes
**Summary**
No
> docs: general corrections and improvements

- .eslintrc.js
- package.json
- packages/generate-loader/package.json
- packages/generate-plugin/package.json
- packages/generators/package.json
- packages/info/package.json
- packages/init/package.json
- packages/migrate/package.json
- packages/package-utils/package.json
- packages/serve/package.json
- packages/utils/package.json
- packages/webpack-cli/package.json
- packages/webpack-scaffold/package.json
- yarn.lock
rm unused deps, move common dev deps to root.
Not needed.
Not needed.
**Summary**
- Removed unused deps.
No
https://github.com/webpack/webpack-cli/pull/1339#issuecomment-603212598
> chore: rm unused packages

- packages/generators/package.json
- packages/generators/src/addon-generator.ts
- yarn.lock
dependency update
Nope
N/A
**Summary**
Nope
N/A
> chore: bump dependencies

- packages/generators/package.json
- yarn.lock
metadata update
Nope
Nope
**Summary**
`log-symbols` provide it's own type definitions. Follow up of #1378 
Nope
N/A
> chore: remove stub type definition

- README.md
docs
No need
yes
**Summary**
Remove unnecessary badges and reoder them
No
No
> docs: improve badges

- packages/generators/src/init-generator.ts
misc fix
No
No
**Summary**
Removed unused import and fixed type for what init generator extends
No
> misc(generators): remove unused import and fix type

- test/target/node/node-test.test.js
FIx, tests
Yes
NA
**Summary**
NA
NO
NA
> tests(webpack-cli): correct node-test

- packages/webpack-scaffold/__tests__/index.test.ts
add test cases
Yep
Nope
**Summary**
Added missing out test cases for `webpack-scaffold`
Nope
N/A
> tests: increase coverage for webpack-scaffold

- packages/webpack-cli/__tests__/init/generator/init-inquirer.test.js
- test/loader/.gitignore
- test/loader/loader.test.js
- test/utils/test-utils.js
tests
Yes
NA
**Summary**
- Add e2e tests for loader command
No
- Please suggest if any other cases can be handled.
> tests: add tests for loader command

- packages/generators/__tests__/utils/styleSupport.test.ts
test update
Yep
Nope
**Summary**
Follow up of #1471
Nope
N/A
> test(generators): Add test case for production CSS config

- packages/info/README.md
Docs
NA
YES
**Summary**
Updated usage of `--output` flag with `info`.
`--output-json` & `--output-markdown` are no longer valid.
No
> docs(info): update --output flag

- .github/ISSUE_TEMPLATE/Bug_report.md
Grammar fix.
NA
NA
**Summary**
NA
NO
NA
> chore: minor grammar fix in Bug_report.md

- test/utils/test-utils.test.js
test update
yep
Nope
**Summary**
Add test case to ensure writing to `stdin` works fine.
Nope
N/A
> tests: test case to ensure writing to stdin

- test/mode/dev/dev.test.js
- test/mode/mode-single-arg/mode-single-arg.test.js
- test/mode/mode-single-arg/src/index.js
Tests.
improved mode tests and added a missing test case for `--mode none`.
yes
NA
**Summary**
Added missing tests case for `--mode none`.
No
NA
> tests: add test case for mode value none

- packages/migrate/package.json
- packages/migrate/src/index.ts
Fix build, there is type inconsistency with webpack@next types, this should ignore that error for now, we need to enable this once it's fixed.
Yes
NA
**Summary**
- Fix build
No
NA
> fix: ignore type inconsistency for now, fix build

- .cz-config.js
- .github/CONTRIBUTING.md
- commitlint.config.js
chore.
NA
YES
**Summary**
allowed commit type `refactor` => `refactor: <msg>`
NO
> chore: allow commit type refactor

- packages/webpack-cli/lib/utils/Compiler.js
typo fix
NA
NO
**Summary**
fix typo ~~`Complilation`~~ `Compilation`
NO
no
> fix: typo in Compiler.js

- packages/webpack-cli/README.md
DOCS
NO NEED
yes
**Summary**
corrected `stats` type to `string`  
NO
> docs: correct stats type

- packages/webpack-cli/__tests__/AdvancedGroup.test.js
- packages/webpack-cli/lib/groups/AdvancedGroup.js
refactor and tests
yes
**Summary**
refactor AdvancedGroup, --hot and --prefetch flag implementation and corresponding tests
no
> fix: prefetch flag implementation

- package-lock.json
- package.json
Bump dependencies
Nope
Nope
**Summary**
Fix dependency vulnerabilities for an upcoming patch release.
Nope
N/A
> chore: bump dependencies for v3

- packages/webpack-cli/lib/utils/GroupHelper.js
chore, Follow up #1571 
NA
NA
**Summary**
plugin flag was removed.
No
> chore: remove plugin TODO

- packages/webpack-cli/lib/utils/Compiler.js
- test/progress/progress-flag.test.js
- test/progress/src/index.js
TEST
yes
No
**Summary**
added test case for `--progress` flag.
no
no
> tests: add test for progress flag

- setupTest.js
chore
**Summary**
https://github.com/webpack/webpack-cli/pull/1590#issuecomment-637506007
> chore: increase jest.setTimeout

- test/utils/cli-plugin-test/main.js
- test/utils/cli-plugin-test/plugin.test.js
- test/utils/cli-plugin-test/webpack.config.js
- test/utils/webpack-cli-test-plugin.js
tests
Yes
NA
**Summary**
Refers https://github.com/webpack/webpack-cli/pull/1548#discussion_r435944921
NO
NO
> tests: create WebpackCLITest Plugin

- test/hot/hot-flag.test.js
- test/hot/index.js
- test/hot/webpack.config.js
tests
yes
no
**Summary**
added tests for `--hot` flag.
no
no
> tests: add tests for --hot flag

- test/prefetch/prefetch.test.js
- test/prefetch/src/index.js
- test/prefetch/src/p.js
- test/prefetch/webpack.config.js
tests
Yes
NA
**Summary**
Adds tests for prefetch flag
No
> tests: add tests for prefetch flag

- packages/webpack-cli/__tests__/arg-parser.test.js
- packages/webpack-cli/lib/utils/arg-parser.js
yes
no need
**Summary**
for #1630 
no
> feat: parse Number flags

- setupTest.js
> chore: increase jest timeout

- .gitignore
- jest.config.js
- scripts/cleanupTest.js
- scripts/prepareSuite.js
- scripts/utils.js
feat/cleanup/test not sure
Yes
NA
**Summary**
- We're manually cleaning up data in multiple tests, this will take care of it at once after all tests run.
No
> feat: add scripts to cleanup stale test data

- test/utils/test-utils.js
refactoring
N/A
N/A
**Summary**
Remove stale code.
Nope
N/A
> chore: remove stale helper methods

- .github/CONTRIBUTING.md
docs
NA
Yes
**Summary**
Changed the yarn installation guide.
You should not guide how to install that is officially "generically not recommended".
It may break developer's environment.
Modified to refer to the official installation guide.
no
> docs: fix yarn installation guide

- packages/webpack-cli/lib/utils/arg-parser.js
- packages/webpack-cli/package.json
fix, chore
NA
NA
**Summary**
Fixes #1679 
no
> chore(deps): upgrade commander.js to v6

- test/utils/cli-plugin-test/plugin.test.js
- test/utils/cli-plugin-test/webpack.config.js
- test/utils/webpack-cli-test-plugin.js
tests
yes
NA
**Summary**
Now we can pass an array of config properties as an argument, to log those properties detailed values.
no
> tests: improve webpackCLITestPlugin

- test/env/array/array-env.test.js
- test/env/object/object-env.test.js
cleanup
Removes stale test cases
N/A
**Summary**
Follow up of #1693
Nope
N/A
> chore: remove stale test cases

- packages/serve/README.md
docs
N/A
Yup
**Summary**
Fixed the badge showing download stats.
Nope
N/A
> docs: show download stats for serve

- packages/init/README.md
docs update
N/A
Yup
**Summary**
Update docs to include information regarding the purpose of `--force` flag.
Nope
N/A
> docs(init): add info regarding force flag

- yarn.lock
chore
Yes
NA
**Summary**
Sync lock file as per the packages
No
No
> chore: sync lock file

- .github/workflows/nodejs.yml
- test/core-flags/optimization-flags.test.js
fix
No
NA
**Summary**
Conditionally install terser plugin for webpack@next
No
https://github.com/webpack/webpack-cli/pull/1731#issuecomment-668652172
> fix: conditionally install terser-webpack-plugin for webpack@next

- test/help/help-single-arg.test.js
- test/info/info-help.test.js
update metadata.
N/A
updates test metadata.
**Summary**
update test description.
Nope
N/A
> chore: rephrase test descriptions

- .github/workflows/nodejs.yml
chore
no
NA
**Summary**
No need terser manually, webpack released.
No
> chore: revert adding terser plugin in webpack@next

- packages/info/README.md
docs
NA
YES
**Summary**
Remove old flags that are not supported now.
NO
> docs(info): remove old flags

- test/config-format/coffee/coffee.test.js
- test/config-format/coffee/main.js
- test/config-format/coffee/package.json
- test/config-format/coffee/webpack.config.coffee
tests
Yes
No need
**Summary**
Add tests for coffeescript config support
No
> tests: add tests for coffeescript config

- test/info/info-output.test.js
test update
Yup
N/A
**Summary**
Added a test case to ensure that a warning shows up in case an invalid value is supplied with `webpack-cli info --output`.
Nope
N/A
> tests(info): --output flag handles invalid arg

- packages/webpack-cli/README.md
- test/core-flags/cache-flags.test.js
- test/core-flags/output-flags.test.js
tests
Yes
Yes
**Summary**
the latest release have breaking changes
NO
> fix: compatibility with webpack@next

- .eslintignore
- .gitignore
- jest.config.js
- lib/test/loader/error-test/src/index.d.ts
- package.json
- test/loader/loader.test.js
- test/migrate/config/migrate-config.test.js
- test/plugin/plugin.test.js
Disables tests for migrate, plugin and loader (scaffolding)
Yea
No
**Summary**
Since yarn will be fighting against the test cases to finish installing lockfiles for each testcase, I've disabled these.
No
N/A
> tests(plugin & loader): refactor tests

- packages/webpack-cli/README.md
- test/core-flags/snapshot-flags.test.js
tests
Yes
Yes
**Summary**
added tests for newly added `--snapshot-*` flags.
No
no
> tests: for snapshot config related flags

- packages/init/README.md
Docs update
N/A
**Summary**
Fixed a typo.
N/A
N/A
> docs(init): minor typographical fix

- packages/webpack-cli/lib/utils/Compiler.js
- packages/webpack-cli/lib/utils/CompilerOutput.js
Removes unused code
N/A
N/A
**Summary**
Removes unused code.
N/A
N/A
> misc(remove code): remove unused code

- lib/test/loader/error-test/src/index.d.ts
chore, cleanup
NA
NA
**Summary**
A temporary file created during testing was added in #1787 
No
No
> chore: remove temporaray files created during testing

- test/core-flags/module-flags.test.js
- test/core-flags/resolve-flags.test.js
tests
Yes
No
**Summary**
new config option `resolve.fallback` was introduced in `webpack@5.0.0-beta.31`
No
No
> tests: add test cases for resolve.fallback option

- test/stats/cli-flags/stats.test.js
Tests
Yes
No
**Summary**
Add test case for newly added preset summary in webpack 5.
No
No
> tests: add case for stats summary preset for webpack 5

- packages/migrate/src/index.ts
refactoring
N/A
N/A
**Summary**
https://github.com/webpack/webpack-cli/pull/1748#discussion_r477206515
Nope
N/A
> refactor: migrate to async/await

- packages/generate-loader/package.json
- packages/generate-plugin/package.json
- packages/generators/package.json
- packages/info/package.json
- packages/init/package.json
- packages/migrate/package.json
- packages/package-utils/package.json
- packages/serve/package.json
- packages/utils/package.json
- packages/webpack-cli/package.json
- packages/webpack-scaffold/package.json
> chore: bump all versions

- packages/webpack-cli/README.md
docs
no
yes
**Summary**
added `resolve-fallback-*` flags to docs.
No
No
> docs: add resolve.fallback config related flags

- packages/webpack-cli/lib/utils/cli-flags.js
chore
Yes
No need
**Summary**
- We've started moving away from group design, group definitions are no longer relevant 
No
> chore: remove group definitions of removed groups

- test/core-flags/optimization-flags.test.js
tests, ci fix
yes
no
**Summary**
updated tests as per `webpack@rc.2`
no
no
> tests: optimization-flags test updates for webpack-rc.2

- test/utils/test-utils.js
- test/utils/test-utils.test.js
refactor, chore
NA
NA
**Summary**
refactor `test-util.js`
No
No
> chore: remove redundant copyFile test-util

- packages/webpack-cli/lib/webpack-cli.js
refactor
Yes
NA
**Summary**
- Removes redundant resolver for config, use common resolver instead
No
> refactor: use base resolver to resolve config

- packages/webpack-cli/lib/groups/ConfigGroup.js
- test/config-name/config-name.test.js
- test/config-name/single-config.js
fix
Yes
NA
**Summary**
log warning if --config-name is used without multiple configs
No
No
> fix: log error if --config-name is used without multiple configs

- packages/webpack-cli/bin/cli.js
chore
No
No
**Summary**
Handle Promise rejection.
No
> chore: handle promise rejection

- test/watch/main.js
- test/watch/watch-flag.test.js
tests
Yes
NA
**Summary**
added test for `--watch` flag.
No
No
> tests: add test for --watch flag

- .gitignore
- package.json
chore/build/publish related change
No need
No need
**Summary**
No :smile: 
No need
No
> chore: improvement for publish

- .github/CONTRIBUTING.md
docs
NA
NA
**Summary**
- Added a release guide section
No
> docs: release guide

- lerna.json
- lint-staged.config.js
- package.json
- yarn.lock
cleanup + some improvements
**Summary**
> chore: cleanup

- .github/CONTRIBUTING.md
docs
No
Yes
**Summary**
update table of contents.
No
No
> docs: update table of contents in contributing.md

- packages/webpack-cli/lib/utils/arg-utils.js
- test/utils/test-utils.js
- test/utils/test-utils.test.js
chore, refactor
Yes
No
**Summary**
No
No
> tests: rm duplicate code for hypenToUpperCase util

- packages/webpack-cli/bin/cli.js
- packages/webpack-cli/lib/groups/resolveAdvanced.js
- packages/webpack-cli/lib/utils/Compiler.js
chore
NA
NA
**Summary**
Use the more appropriate method `logger.success`.
No
No
> chore: use logger.success

- .github/workflows/nodejs.yml
feat
Not yet
NA
**Summary**
- https://github.com/actions/cache/blob/main/examples.md#node---lerna
- Try to use cached deps to reduce CI time
No
> feat: CI - cache lerna dependencies

- package.json
- packages/package-utils/__tests__/index.test.ts
- packages/package-utils/package.json
- packages/serve/__tests__/startDevServer.test.ts
- packages/serve/package.json
- packages/serve/src/parseArgs.ts
- packages/serve/src/startDevServer.ts
- yarn.lock
chore, deps
NA
NA
**Summary**
move devDependencies from packages to root
no
no
> chore(deps): move devDependencies from packages to root

- test/watch/main.js
- test/watch/src/index.js
- test/watch/watch-flag.test.js
tests
yes
Not applicable
**Summary**
Added test for which will test simulating user and should run on windows as well.
No
No
> tests: improve watch tests and enable windows

- packages/package-utils/__tests__/index.test.ts
- packages/webpack-cli/lib/commands/resolveCommand.js
- packages/webpack-cli/lib/utils/arg-parser.js
refactoring
Nope
N/A
**Summary**
Remove stale code.
Nope
N/A
> refactor: remove stale code

- test/config-format/typescript/typescript.test.js
- test/entry/scss/scss.test.js
- test/loader/loader.test.js
- test/migrate/config/migrate-config.test.js
- test/plugin/plugin.test.js
chore
N/A
N/A
**Summary**
Using default timeout which is `240000` instead of `60000`(in ms)
No
These tests fail randomly on macos ci
> chore: use default timeout for every test

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
Miscellaneous 
N/A
N/A
**Summary**
Auto applies labels for `Bug_report` and `Feature_request` issue templates.
Nope
N/A
> auto apply labels for issue templates

- packages/webpack-cli/lib/utils/Compiler.js
- test/invalid-schema/invalid-schema.test.js
- test/stats/cli-flags/stats.test.js
test
No need
No need
**Summary**
debug windows test problems
No
No
> tests: windows

- packages/generate-loader/package.json
- packages/generate-plugin/package.json
- packages/generators/package.json
chore/fix
No need
No need
**Summary**
chore/fix
No, because webpack-cli@3 doesn't work with this
No
> chore: fix peerDependencies

- test/config-lookup/relative/a.js
- test/config-lookup/relative/basic-config.test.js
- test/config-lookup/relative/webpack.config.js
tests
Yes
No need
**Summary**
fixes #1924
No
All works fine, don't know the problem, so just tests
> tests: relative configs

- packages/info/package.json
- packages/utils/package.json
- packages/webpack-cli/package.json
- yarn.lock
bugfix
No need
No need
**Summary**
- reduce `info` size, we don't use these packages
- fixes #1941
No
No
> chore: reduce package size

- .eslintignore
- .prettierignore
- test/config/error/config-error.test.js
- test/config/error/src/index.js
- test/config/error/syntax-error.js
- test/config/error/webpack.config.js
tests
yes
**Summary**
added a test-case for the following issue.
Fixes #1980
No
No
> tests: for exit-code in case of error in config

- package.json
- packages/generators/__tests__/addon-generator.test.ts
- packages/generators/package.json
- packages/generators/src/addon-generator.ts
- packages/migrate/package.json
- packages/utils/package.json
- packages/webpack-cli/package.json
- packages/webpack-scaffold/package.json
- yarn.lock
update deps + remove mkdirp, because we don't need this package (built-in) in node
No
No need
**Summary**
update + reduce deps
No
No
> chore(deps): update

- packages/generators/README.md
docs
No
Yes
**Summary**
fix links.
No
> docs: update generators links

- packages/webpack-cli/__tests__/ConfigGroup/ConfigGroup.test.js
- packages/webpack-cli/__tests__/ConfigGroup/env.webpack.config.cjs
feat
Yes
NA
**Summary**
added tests for new env format in config group tests
No
NA
> tests: add tests for env in configGroup

- test/analyze/analyze-flag.test.js
tests update
yes updated
NA
**Summary**
remove `--watch` argument.
No
No
> tests: update anayze-flag test

- packages/info/src/index.ts
- test/info/info-output.test.js
fix
yes
NA
**Summary**
exit from the process after error with proper exit-code.
No
No
> fix(info): throw error and exit for invalid --output value

- packages/webpack-cli/README.md
- packages/webpack-cli/lib/plugins/WebpackCLIPlugin.js
- test/progress/progress-flag.test.js
chore
updated existing test.
updated docs for `--progress`.
**Summary**
improve error message.
no
no
> chore: improve error message for invalid progress value

- .prettierignore
chore
NA
No
**Summary**
add some temporary test files to `.prettierignore`
these files make lint fail in my local which creates noise in my workflow.
No
No
> chore: add more tmp test files to .prettierignore

- packages/webpack-cli/lib/utils/interactive.js
- packages/webpack-cli/package.json
chore
No need
No need
**Summary**
remove unused dep `ansi-escapes`
No
No
> chore(deps): remove unused ansi-escapes

- packages/webpack-cli/README.md
Documentation change
N/A
Yes
**Summary**
This readme is visible to the user of `npm` and places other than github.
Thus it doesn't align with readme(s) of other official webpack projects.
There are some sections with TODO in readme which should not be there in release.
No
https://www.npmjs.com/package/webpack-cli
> docs: cleanup readme

- packages/webpack-cli/README.md
docs
no
yes
**Summary**
add `configuration.externalsPrestes` related flags
No
No
> docs: add configuration.externalsPrestes related flags

- packages/webpack-cli/lib/utils/merge-strategies.js
- packages/webpack-cli/lib/webpack-cli.js
refactor
NA
NA
**Summary**
remove unused util.
No
No
> refactor: remove redundant merge-strategies util

- packages/webpack-cli/lib/utils/cli-flags.js
chore
Yes
NA
**Summary**
We've migrated from group design, no need
No
> chore: remove help group properties

- packages/webpack-cli/lib/utils/cli-flags.js
chore, improvement
no
no
**Summary**
add links related to flags to show them in help output.
no
no
> chore: add documentation links to cli-flags for help output

- .github/ISSUE_TEMPLATE.md
chore, metadata update
NA
NA
**Summary**
add an issue template. better than leaving it blank.
No
No
> chore: add ISSUE_TEMPLATE

- packages/webpack-cli/README.md
docs
No
Yes
**Summary**
update docs as per webpack latest.
No
`--stats-max-modules number` is not exported from core anymore
> docs: update stats option related flags

- INIT.md
docs
NA
YES
**Summary**
documentation update.
No
No
> docs: update INIT.md

- README.md
docs
Not required
Yup
**Summary**
Added codecov badge so that coverage is visible in main readme
No
No
> docs: add code coverage badge

- packages/webpack-cli/lib/utils/package-exists.js
fix
Yes
NA
**Summary**
Improve package exists package to simple return the module name instead of loading the library 
No
> fix: improve package-exists util

- packages/generators/src/init-generator.ts
- packages/init/README.md
- packages/init/src/index.ts
- packages/utils/src/modify-config-helper.ts
- packages/utils/src/scaffold.ts
- test/init/generate-path/init-generate-path.test.js
- test/init/generation-path/init-generation-path.test.js
feature
Yes
Nope
**Summary**
Added new `--generation-path` flag for `init` subcommand for scaffolding in a specified path. Addresses #2021
https://github.com/webpack/webpack-cli/issues/2021#issuecomment-722395490
> feat(init): add --generation-path flag

- packages/generate-plugin/README.md
- packages/generate-plugin/src/index.ts
- test/plugin/plugin.test.js
Enhancement
Yes
Nope
**Summary**
Added the ability to scaffold the `plugin` template in a specified path. Addresses #2021
Nope
https://github.com/webpack/webpack-cli/issues/2021#issuecomment-722395490
> feat(generate-plugin): scaffold in a specified path

- test/core-flags/entry-reset-flag.test.js
- test/core-flags/externals-flags.test.js
- test/core-flags/infrastructure-logging.test.js
- test/core-flags/parallelism-flag.test.js
- test/target/flag-test/target-flag.test.js
- test/target/flag-test/webpack.config.js
tests
Yes
No
**Summary**
increase coverage.
No
No
> tests: add more cases for core-flags tests

- packages/webpack-cli/README.md
docs
NA
yes
**Summary**
update types for `--target` & `--env`
No
No
> docs: update --env & --target types

- test/init/generation-path/init-generation-path.test.js
tests
Yes
N/A
**Summary**
Follow up of #2050
Nope
N/A
> tests(init): add test case for scaffolding in the current directory

- packages/utils/src/modify-config-helper.ts
- test/init/auto/init-auto.test.js
- test/init/force/init-force.test.js
- test/init/generator/init-inquirer.test.js
chore
Nope
N/A
**Summary**
<h3><ins>Before</ins></h3>
<h3><ins>After</ins></h3>
Nope
N/A
> chore(utils): remove duplicate log

- INIT.md
docs
NA
yes
**Summary**
recently added `--generation-path`
No
No
> docs: add --generation-path for init

- packages/webpack-cli/lib/utils/cli-flags.js
Enhancement
Nope
N/A
**Summary**
Added `flags` entry for `init` subcommand.
Nope
N/A
> feat(init): display available options as part of help information

- packages/webpack-cli/lib/utils/cli-flags.js
chore
Already present
N/A
**Summary**
Update usage information for subcommands.
Nope
N/A
> chore: update usage info for subcommands

- README.md
Docs
N/A
Yes
**Summary**
Update reference to subcommands.
Nope
N/A
> docs: update reference to subcommands

- packages/webpack-cli/README.md
docs
No
Yes
**Summary**
add `--ignore-warnings-*` related flags.
No
No
> docs: add configuration.ignoreWarnings related flags

- test/env/array/array-env.test.js
- test/env/array/webpack.config.js
- test/env/object/object-env.test.js
fix, tests
Yes
No
**Summary**
fix flaky tests. were failing on MacOS.
No
No
> tests: fix flaky env tests

- packages/webpack-cli/lib/utils/__tests__/get-package-manager.test.js
- packages/webpack-cli/lib/utils/get-package-manager.js
refactor.
yes updated.
NA
**Summary**
avoid multiple fs calls.
No
No
> refactor: get-package-manger logic for perf improvements

- test/colors/colors.test.js
typo fix
NA
NA
**Summary**
fix typo
No
> chore: fix typo

- test/config-lookup/dotfolder-array/.webpack/webpack.config.js
- test/config-name/function-config.js
- test/config-name/webpack.config.js
- test/config/function/multi-webpack.config.js
- test/config/multiple/webpack1.config.js
- test/config/multiple/webpack2.config.js
- test/config/type/array/webpack.config.js
- test/devtool/array/webpack.config.js
- test/devtool/object/webpack.eval.config.js
- test/devtool/object/webpack.source.config.js
- test/entry/scss/webpack.config.js
- test/target/flag-test/webpack.config.js
- test/target/node/webpack.config.js
- test/watch/watch-flag.test.js
refactoring tests
No need
No need
**Summary**
use `mode: 'development'` in many tests to reduce tests time
No
No
> tests: speedup

- packages/generators/__tests__/__snapshots__/init-generator.test.ts.snap
- packages/generators/__tests__/init-generator.test.ts
- packages/generators/templates/tsconfig.json.js
fix
yes
**Summary**
Fixes https://github.com/webpack/webpack-cli/issues/2106
No
No
> fix(init): add `files` field in tsconfig.json

- .github/ISSUE_TEMPLATE/Bug_report.md
chore
NA
NA
**Summary**
link to SO's guide for reproduction in the bug template.
https://stackoverflow.com/help/minimal-reproducible-example
No
No
> chore: link to SO's guide for reproduction in bug template

- packages/webpack-cli/lib/plugins/CLIPlugin.js
- test/stats/watch/stats-and-watch.test.js
- test/watch/watch-flag.test.js
minor fix to #2132 
No but CI is red after above mentioned PR. Can fix later.
No
**Summary**
Changed message displayed in the watch output to `Compiler is watching ...` from `Compilation is watching ...`
> chore: replace compilation to complier

- packages/webpack-cli/README.md
docs
No
Yes
**Summary**
add --no-devtool & --no-watch
No
No
> docs: add --no-devtool & --no-watch

- .eslintignore
chore
NA
NA
**Summary**
remove stale temporary files from .eslintignore
no
no
> chore: remove stale files from .eslintignore

- packages/utils/__tests__/global-packages-path.test.ts
- packages/webpack-cli/lib/utils/__tests__/get-package-manager.test.js
- packages/webpack-cli/lib/utils/__tests__/prompt-installation.test.js
chore
N/A
N/A
**Summary**
Remove unnecessary mocking of modules.
Nope
N/A
> chore: remove unnecessary mocking of modules

- package.json
- yarn.lock
chore
N/A
N/A
**Summary**
Remove `@types/cross-spawn`
Nope
N/A
> chore: remove stale type definition

- test/merge/config-absent/merge-config-absent.test.js
- test/merge/config/merge-config.test.js
tests
yes
Na
**Summary**
fix incorrect test
No
No
> tests: correct merge-config-absent test

- packages/webpack-cli/README.md
Docs update
N/A
Yes
**Summary**
A better description for negated flags.
N/A
N/A
> docs(webpack-cli): better description for negated flags

- test/core-flags/invalid-flag.test.js
chore
NA
NA
**Summary**
fix description.
No
No
> chore: fix invalid-flag test description

- packages/webpack-cli/lib/bootstrap.js
chore
Yes
No
**Summary**
Fix https://github.com/webpack/webpack-cli/issues/2164
No
No
> chore: fix args run method

- packages/webpack-cli/lib/utils/cli-flags.js
- test/help/help-flags.test.js
enhancement
NA
NA
**Summary**
improve help output for --merge
no
no
> chore: improve help output for --merge

- test/cache/cache.test.js
- test/cache/multi.config.js
- test/cache/webpack.config.js
- test/core-flags/cache-flags.test.js
tests
Yes
No need
**Summary**
Complex cache test
No
No
> tests: cache

- README.md
docs
NA
Yes
**Summary**
remove old commands references
No
NO
> docs: remove old commands references

- packages/webpack-cli/lib/webpack-cli.js
bugfix
Existing
No need
**Summary**
fixes #2120
No
No
> fix: size of json stats

- packages/info/__tests__/info.test.ts
- packages/info/src/index.ts
- packages/webpack-cli/__tests__/info.test.js
tests
Yes
NA
**Summary**
more tests
No
No
> tests: add more unit tests for info

- packages/webpack-cli/README.md
docs update
Already present
Yes
**Summary**
update output config related flags
No
No
> docs: update output config related flags

- .eslintignore
- test/config/error-array/config-array-error.test.js
- test/config/error-array/src/index.js
- test/config/error-array/webpack.config.js
tests
Yes
NA
**Summary**
- Tests for config errors
No
> tests: add test for array config err

- package.json
- test/core-flags/output-flags.test.js
- yarn.lock
chore
yes
No
**Summary**
update webpack to 5.10.0
no
Fixes https://github.com/webpack/webpack-cli/pull/2182
> chore: update webpack to 5.10.0

- test/config/type/array-function-with-argv/function-with-argv.test.js
- test/config/type/array-function-with-env/array-function-with-env.test.js
- test/config/type/function-with-argv/function-with-argv.test.js
tests 
Yes
NA
**Summary**
We recently migrated to use sync fs API for checking output, some got left due to rebase, this should migrate the rest.
No
> tests: use sync fs for output check

- packages/webpack-cli/__tests__/arg-parser.test.js
tests
yes
no
**Summary**
no
no
no
> tests: add tests for multitype flag

- packages/webpack-cli/lib/utils/cli-flags.js
fix
Nope
Already up to date
**Summary**
Update description for `--color` flag.
Nope
https://github.com/webpack/webpack-cli/pull/2180#discussion_r536747415
> fix: update description for --color flag

- .github/CONTRIBUTING.md
docs
NA
Yes
**Summary**
add example commit messages
No
fixes https://github.com/webpack/webpack-cli/pull/1344
> docs: add example commit messages

- test/config/type/array/array.test.js
- test/config/type/array/webpack.config.js
tests
yes
NA
**Summary**
Fixes https://github.com/webpack/webpack-cli/issues/2196
Nope
https://github.com/webpack/webpack/pull/12125#issuecomment-739494612
> tests: respect cli args when config is an array

- packages/webpack-cli/lib/groups/runHelp.js
- packages/webpack-cli/lib/utils/cli-flags.js
chore
Nope
Already up to date.
**Summary**
A better description for built-in negated flags.
Nope
N/A
> chore: better description for built-in negated flags

- packages/webpack-cli/lib/utils/cli-flags.js
enhancement
NA
NA
**Summary**
update usage for `--stats`, `--json` & `--progress`.
NO
NO
> fix: update usage of flags with multiple types

- yarn.lock
chore
N/A
N/A
**Summary**
Follow up of #2190
Nope
N/A
> build: update lock file

- packages/webpack-cli/__tests__/arg-parser.test.js
tests
yes
no
**Summary**
no
no
no
> tests: add tests for nested multitype flag

- packages/webpack-cli/__tests__/CLIPluginResolver.test.js
tests
yes
no
**Summary**
no
no
/cc @alexander-akait
> tests: add tests for cli plugin resolver

- packages/webpack-cli/__tests__/resolveArgs.test.js
- test/stats/config/stats.test.js
tests
yes
no
**Summary**
increase coverage
no
no
> tests: add more cases for stats tests

- packages/webpack-cli/lib/webpack-cli.js
- test/config-name/config-name.test.js
chore
Nope
N/A
**Summary**
Rephrased error message.
Nope
N/A
> chore: rephrase error message

- .eslintignore
CI lint is failing 
yep
no
**Summary**
no
no
no
> fix: ci lint

- packages/webpack-cli/lib/utils/cli-flags.js
chore
Nope
N/A
**Summary**
Update usage information for the `migrate` command.
Nope
N/A
> chore: update usage info for migrate command

- packages/info/README.md
docs
yes
no
**Summary**
no
no
no
> fix: info package docs

- .github/CONTRIBUTING.md
Same as short description
BREAKING CHANGE: 🧨 No
✅ Closes: #2256
**Summary**
> fix: 🐛 Fixed articles error in the CONTRIBUTING.md file

- packages/serve/src/index.ts
- test/serve/basic/serve-basic.test.js
- test/serve/basic/webpack.config.js
- test/utils/cli-plugin-test/plugin.test.js
- test/utils/webpack-cli-test-plugin.js
bugfix
Нуы
No need
**Summary**
Avoid applying plugin twice
No
No
> fix: do not apply HotModuleReplacement plugin twice

- package.json
- packages/utils/package.json
- packages/webpack-cli/package.json
- test/serve/basic/serve-basic.test.js
- yarn.lock
tests
Yes
No need
**Summary**
adding tests on fixing issue
No
No
> tests: open and serve

- packages/webpack-cli/lib/webpack-cli.js
- test/unknown/unknown.test.js
bugfix
WIP
No
**Summary**
fixes #2277
No
No
> Issue 2277

- packages/webpack-cli/package.json
bugfix
No, maybe we need some tests on installation (e2e)
No need
**Summary**
fix peer deps after union packages
No
No
> fix: peer dependencies

- .github/workflows/nodejs.yml
chore
No need
No need
**Summary**
fix coverage
No
No
> chore: fix ci coverage

- .github/ISSUE_TEMPLATE.md
typo fix
NA
NA
**Summary**
FIX A TYPO
NO
NO
> docs: fix typo

- packages/webpack-cli/lib/utils/cli-flags.js
fix
NA
NA
**Summary**
better description for `--no-watch-options-stdin`
No
No
> fix: better description for --no-watch-options-stdin

- packages/webpack-cli/README.md
docs
No
Yeah
**Summary**
Added documentation for internal commands to be displayed on NPM and elsewhere
No
No
> docs: usage and internal commands

- test/core-flags/ignore-warnings/ignore-warnings-flag.test.js
- test/core-flags/ignore-warnings/my-warning-loader.js
- test/core-flags/ignore-warnings/src/main.js
- test/core-flags/ignore-warnings/webpack.config.js
tests
yes
no
**Summary**
add test cases for --ignore-warnings
no
no
> tests: add test cases for --ignore-warnings

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/CONTRIBUTING.md
Development experience
N/A
Yes
**Summary**
Add support for dev containers for letting contributors to quickly setup development environment.
https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers
No
No
> feat: add support for dev containers

- test/init/force/init-force.test.js
- test/init/generator/init-inquirer.test.js
- test/init/multipleEntries/init-multipleEntries.test.js
chore
Updated `init` test suite.
N/A
**Summary**
Remove the extraneous argument supplied to `runPromptWithAnswers()`.
Nope
N/A
> chore: prevent unnecessary writes to stdin

- packages/webpack-cli/__tests__/CLI.test.js
- packages/webpack-cli/lib/webpack-cli.js
- test/help/help.test.js
bugfix
yes
No need
**Summary**
fixes #2290
No
No
> fix: double commands output in help

- .eslintignore
- .prettierignore
chore
NA
NA
**Summary**
ignore build files from `eslint` and `prettier`.
No
NO
> chore: ignore build files from lint

- packages/generators/__tests__/utils/styleSupport.test.ts
- packages/generators/src/utils/styleSupport.ts
- test/init/auto/init-auto.test.js
- test/init/force/init-force.test.js
- test/init/generation-path/init-generation-path.test.js
- test/init/generator/init-inquirer.test.js
- test/init/language/css/init-language-css.test.js
- test/init/language/js/init-language-js.test.js
- test/init/multipleEntries/init-multipleEntries.test.js
test update
Updated `init` test suite.
N/A
**Summary**
Updated the `init` test suite to make sure that `webpack.config.js` is not empty.
Nope
#2110 #2247
> tests(init): assert for webpack config file content

- packages/generators/__tests__/__snapshots__/init-generator.test.ts.snap
- packages/generators/src/init-generator.ts
closes #404
remove adding splichunk config, using default from webpack by default.
WIll update along the way
No
**Summary**
removed addition of splitchunks
No
No
> fix: remove splitchunks

- packages/webpack-cli/bin/cli.js
fix
no
no
**Summary**
Earlier it was -
NO
No
> fix: webpack installation prompt message

- INIT.md
- packages/generators/__tests__/__snapshots__/init-generator.test.ts.snap
- packages/generators/src/init-generator.ts
- test/init/force/init-force.test.js
- test/init/generator/init-inquirer.test.js
- test/init/language/css/init-language-css.test.js
- test/init/language/js/init-language-js.test.js
- test/init/multipleEntries/init-multipleEntries.test.js
feat
not yet
NA
**Summary**
- Gives option for users to select plugins they want instead of applying them by default
No
/cc @alexander-akait
> feat: flexible init scaffolding

- packages/generators/__tests__/__snapshots__/init-generator.test.ts.snap
- packages/generators/src/init-generator.ts
bugfix
Nope
Nope
**Summary**
Fixed the generated webpack config.
Nope
N/A
> fix(init): regression with webpack config

- packages/webpack-cli/__tests__/applyCLIPlugin.test.js
- packages/webpack-cli/lib/webpack-cli.js
tests
yes
NA
**Summary**
- Adds tests to check whether CLI plugin is applied correctly to multi compiler setup
no
> tests: multi compiler CLI plugin test

- packages/generators/src/utils/tooltip.ts
chore
Nope
N/A
**Summary**
Remove stale helpers.
Nope
N/A
> chore: remove stale helpers

- packages/serve/src/startDevServer.ts
- packages/serve/src/types.ts
fix 
already present
NA
**Summary**
fix types and ts warnings
No
No
> fix(serve): ts types and warnings

- .github/workflows/nodejs.yml
- package.json
fix
N/A
N/A
**Summary**
Fixes coverage problems.
Reverts #2318 
No
No
> fix: create sourcemaps on ci

- OPTIONS.md
- package.json
- test/core-flags/module-flags.test.js
- test/entry/flag-entry/entry-with-flag.test.js
- test/serve/basic/serve-basic.test.js
- yarn.lock
update webpack, fix ci issues
WIP
YES
**Summary**
update webpack
No
Fixes  https://github.com/webpack/webpack-cli/pull/2333
> chore: update webpack to 5.12.2

- packages/generators/__tests__/__snapshots__/init-generator.test.ts.snap
- packages/generators/__tests__/init-generator.test.ts
- packages/generators/src/init-generator.ts
test update
Yup
N/A
**Summary**
Increase test coverage.
Nope
N/A
> tests(init): increase coverage

- test/entry/flag-entry/entry-with-flag.test.js
- test/serve/help/serve-help.test.js
tests
yes
NA
**Summary**
Adds test case for help in serve command to ensure we output both cli and serve flags
No
> tests: serve help

- packages/webpack-cli/package.json
refactoring
No need
No need
**Summary**
configtest command available by default
No
I think we forget to do it in the original PR
> refactor: `configtest` is the part of webpack-cli

- packages/init/src/index.ts
- packages/utils/src/modify-config-helper.ts
- packages/utils/src/resolve-packages.ts
chore
N/A
No
**Summary**
Remove redundant parameter from modifyHelperUtil.
No
No
> chore: remove redundant action

- .github/workflows/nodejs.yml
- .prettierignore
- OPTIONS.md
- package.json
- packages/generators/__tests__/init-generator.test.ts
- packages/generators/__tests__/loader-generator.test.ts
- packages/generators/__tests__/plugin-generator.test.ts
- packages/generators/__tests__/utils/scaffold-utils.test.ts
- packages/generators/package.json
- packages/serve/src/index.ts
- smoketests/missing-packages/webpack-dev-server.test.js
- smoketests/missing-packages/webpack.test.js
- yarn.lock
chore
No need
No
**Summary**
- update deps
- update ts
- fix options
- enable smoketests to catch and fix problems
No
No
> chore: update deps

- packages/info/src/index.ts
- packages/init/src/index.ts
- packages/serve/src/index.ts
- packages/webpack-cli/__tests__/CLI.test.js
- packages/webpack-cli/lib/utils/capitalize-first-letter.js
- packages/webpack-cli/lib/webpack-cli.js
- packages/webpack-cli/package.json
- test/config/type/function-with-env/function-with-env.test.js
- test/defaults/output-defaults.test.js
- test/info/info-unknown.test.js
- test/output/output-named-bundles.test.js
- test/prefetch/prefetch.test.js
- test/serve/basic/serve-basic.test.js
- test/target/flag-test/target-flag.test.js
- test/unknown/unknown.test.js
- yarn.lock
chore
No need
No need
**Summary**
Update commander
No
We have some new abilities (WIP on them)
- Before `error: unknown option '--foo'`, now `[webpack-cli] Error: Unknown option '--foo'` (prefix and color)
> chore: update `commander`

- packages/webpack-cli/lib/webpack-cli.js
refactor
Existing
No
**Summary**
prepare before https://github.com/webpack/webpack-cli/issues/2356
No
We can return syntax `webpack ./one.js ./two.js ./two.js [options]`, also for `watch`/`build`/`serve` commands
> refactor: code

- CHANGELOG.md
documentation
no
yes
**Summary**
Version `4.0.0-beta.9` removed the `-p` flag. I was searching for this, but the changelog didn't contain the text `"-p"`. It did have `--prod`, but I didn't know about that pseudonym. Anyway, this should help others.
Related: https://github.com/webpack/webpack.js.org/issues/4465
no
none
> Mention `-p` in the changelog

- OPTIONS.md
- package.json
- test/build-errors/errors.test.js
- test/build-warnings/warnings.test.js
- test/colors/colors.test.js
- test/core-flags/context-flag.test.js
- test/core-flags/output-flags.test.js
- test/core-flags/stats-flags.test.js
- test/defaults/output-defaults.test.js
- test/entry/defaults-empty/entry-single-arg.test.js
- test/entry/flag-entry/entry-with-flag.test.js
- test/mode/mode-single-arg/mode-single-arg.test.js
- test/prefetch/prefetch.test.js
- test/zero-config/entry-absent/zero-config.test.js
- yarn.lock
update webpack
Yes
Yes
**Summary**
update webpack to the latest version.
No
~currently blocked by https://github.com/webpack/webpack/issues/12608~ resolved
fixes #2418
> chore: update webpack

- .github/workflows/nodejs.yml
build, chore
No
No
**Summary**
webpack-5 is already installed with the dependencies installation step.
No
No
> build: do not install webpack 5 again

- packages/generators/src/types/index.ts
- packages/generators/src/utils/modify-config-helper.ts
chore
Nope
N/A
**Summary**
Remove stale property.
Nope
N/A
> chore(generators): update types

- README.md
- packages/configtest/README.md
- packages/info/README.md
update docs
NO
YES
**Summary**
update commands.
Add README.md for `@webpack-cli/configtest`.
No
No
> docs: update commands

- packages/configtest/src/index.ts
refactor
yes
NA
**Summary**
- We now have error validation in CLI, no need for redundant methods
no
> refactor: use error validation from cli

- packages/generators/src/utils/__tests__/run-prettier.test.ts
- packages/generators/src/utils/run-prettier.ts
- packages/generators/src/utils/scaffold.ts
fix
No
No
**Summary**
- improve error message when prettier is not found
no
Fix https://github.com/webpack/webpack-cli/issues/2253
> fix: improve prettier message

- test/bail/bail.test.js
- test/serve/basic/serve-basic.test.js
- test/serve/serve-variable/serve-basic.test.js
- test/serve/with-custom-port/serve-custom-config.test.js
- test/stats/watch/stats-and-watch.test.js
- test/utils/test-utils.js
refactoring
No need
No need
**Summary**
Refactor test utils
No
No
> Test refactor

- test/config-format/mjs/mjs.test.js
- test/config-lookup/custom-name/custom-name.test.js
- test/config/defaults/mjs-config/default-mjs-config.test.js
- test/config/error-mjs/config-error.test.js
chore
skipped flaky tests
no
**Summary**
fix ci behaviour
no
no
> chore: skip flaky tests for windows

- .github/CONTRIBUTING.md
docs
No
Yes
**Summary**
Remove `migrate` references.
No
No
> docs: remove migrate references

- packages/webpack-cli/README.md
docs
No
Yes
**Summary**
Change `You display basic commands and arguments -`  **to** ` To display basic commands and arguments -`
No
No
> docs: Grammatical error in webpack-cli commands and arguments usage

- .github/CONTRIBUTING.md
docs
No
Yes
**Summary**
Removed an extra line space in the commit message format guide.
No
No
> docs: fix a typo at contrbuting readme file

- .github/CONTRIBUTING.md
docs 
No
Yes
**Summary**
Fixes #2472 
No
No
> docs: update bootstrap command

- package.json
- test/core-flags/module-flags.test.js
- test/core-flags/output-flags.test.js
- yarn.lock
update webpack
Yes, updated tests.
No
**Summary**
Fixes #2496 
No
No
> chore: update webpack to v5.25.0

- smoketests/missing-command-packages/generator.test.js
test
Yup
**Summary**
Added smoke test for init when generators package is unavailable.
No
Part of #2493
> test: smoketest for init without generators

- smoketests/index.js
- smoketests/missing-command-packages/serve.test.js
test
Yup
**Summary**
Part of #2493 
No
No
> test: add serve smoketest

- smoketests/index.js
- smoketests/missing-command-packages/info.test.js
test
Yup
No
**Summary**
Part of #2493
No
N/A
> test: add smoketest for missing info

- package.json
- yarn.lock
fix
NA
NA
**Summary**
- Don't know how this package made it in dependencies, it should be in devDeps 
No
Also no
> chore: fix types package dep

- smoketests/index.js
- smoketests/missing-packages/webpack-bundle-analyzer.test.js
Test
yes
No
**Summary**
Refers https://github.com/webpack/webpack-cli/issues/2493
No
Nothing.
> test: for missing `webpack-bundle-analyzer`

- smoketests/index.js
- smoketests/missing-command-packages/configtest.test.js
Smoke tests
Update smoke test suite.
N/A
**Summary**
Add smoke test for the `configtest` package.
Nope
N/A
> test: add smoketest for configtest package

- packages/generators/init-template/default/postcss.config.js
- packages/generators/init-template/default/webpack.configjs.tpl
- packages/generators/src/handlers/default.ts
- test/init/init.test.js
Add postcss support as well to default template
WIP
N/A
**Summary**
Add PostCSS support as well to default template because it is popular.
No
/cc @alexander-akait
> feat: add postcss support to default template

- test/init/init.test.js
Test update
Update `init` test suite.
N/A
**Summary**
Add checks to make sure that `package.json` and `webpack.config.js` are correctly configured
Nope
N/A
> test: assert for config file content

- test/init/__snapshots__/init.test.js.snap
- test/init/init.test.js
Tests
Update test suite.
N/A
**Summary**
Use snapshot testing to assert for the generated webpack config content.
Nope
N/A
> test: use snapshot testing for the init test suite

- test/init/__snapshots__/init.test.js.snap.webpack4
- test/init/__snapshots__/init.test.js.snap.webpack5
- test/init/init.test.js
Test update
Yes
N/A
**Summary**
Update `init` test suite.
Nope
N/A
> test: configures html-webpack-plugin as opted with init

- packages/info/README.md
- packages/info/src/index.ts
- test/help/__snapshots__/help.test.js.snap.webpack4
- test/help/__snapshots__/help.test.js.snap.webpack5
fix grammar issue, update docs
Yes updated snapshots
Yes
**Summary**
fix grammar issue.
No
No
> fix(info): grammar in description of `--output`

- .github/workflows/nodejs.yml
- packages/info/src/index.ts
build
NA
NA
**Summary**
run `yarn lerna bootstrap` on CI.
No
> build: add bootstrap step in workflow

- .github/workflows/nodejs.yml
- test/init/__snapshots__/init.test.js.snap.webpack4
- test/init/__snapshots__/init.test.js.snap.webpack5
Update test snapshots
Update test snapshots
N/A
**Summary**
Fix CI
#2544
Nope
N/A
> test: update snapshots

- packages/generators/src/init-generator.ts
fix
No
No
**Summary**
exit code `1` is used for errors from the webpack.
Maybe
https://github.com/webpack/webpack-cli#exit-codes-and-their-meanings
> fix(generators): use correct exit code

- package.json
- yarn.lock
build
NA
NA
**Summary**
Upgrade lerna to v4
verifying
> chore: upgrade lerna to v4

- test/version/__snapshots__/version.test.js.snap.webpack4
- test/version/__snapshots__/version.test.js.snap.webpack5
- test/version/version.test.js
tests
yep updated snapshots
NA
**Summary**
migrate version tests to snapshots
no
> test: migrate version tests

- packages/generators/__tests__/addon-generator.test.ts
- packages/generators/__tests__/loader-generator.test.ts
- packages/generators/__tests__/plugin-generator.test.ts
- packages/generators/src/addon-generator.ts
- packages/generators/src/index.ts
- packages/generators/src/init-generator.ts
fix
Yes
NA
**Summary**
- No not import from webpack-cli, use instance
- 
no
> fix: imports in generator

- packages/generators/init-template/default/webpack.configjs.tpl
- test/init/__snapshots__/init.test.js.snap.webpack4
- test/init/__snapshots__/init.test.js.snap.webpack5
feat and chore
WIP
**Summary**
Made file extensions insensitive to case in webpack config for default template
No
> feat: make extention case insensitive

- packages/generators/init-template/default/webpack.configjs.tpl
- test/init/__snapshots__/init.test.js.snap.webpack4
- test/init/__snapshots__/init.test.js.snap.webpack5
fix
Yes 
NO
**Summary**
Fixes #2575 
No
No
> fix: webpack config for `babel-loader` and `ts-loader`

- scripts/snapshotResolver.js
chore
No need
NA
**Summary**
CI gets spammed by version log in each test when we already log it at the top
no
> chore: remove version logging spam in each test

- test/build/build-variable/build-variable.test.js
- test/init/init.test.js
CI fix
no
no
**Summary**
CI broke in https://github.com/webpack/webpack-cli/pull/2571, failing in master
no
> chore: fix CI

- test/build/cache/cache.test.js
- test/build/config-format/mjs/mjs.test.js
- test/build/config-lookup/custom-name/custom-name.test.js
- test/build/config/defaults/mjs-config/default-mjs-config.test.js
- test/build/config/error-mjs/config-error.test.js
- test/build/core-flags/cache-flags.test.js
- test/build/node/node.test.js
> test: resolve todos

- test/serve/basic/serve-basic.test.js
test
yes
no
**Summary**
check for exit code too.
none
no
> test: add assertion for exit code

- packages/generators/init-template/default/webpack.configjs.tpl
- test/init/__snapshots__/init.test.js.snap.webpack4
- test/init/__snapshots__/init.test.js.snap.webpack5
fix
yeah, updated snapshots
No
**Summary**
Fixes #2597 
No
No
> fix: broken URL in generated webpack.config.js

- jest.config.js
- package.json
- smoketests/helpers.js
- smoketests/missing-packages/webpack-dev-server.test.js
> test: coverage

- jest.config.js
remove test folder from code coverage result
> test: remove test folder from code coverage result

- packages/generators/src/index.ts
- test/help/__snapshots__/help.test.js.snap.webpack4
- test/help/__snapshots__/help.test.js.snap.webpack5
refactor
Yes updated snapshots
It was never documented.
**Summary**
Remove `--no-force` as: 
-  It was never supported intentionally.
-  It's kind of useless.
Maybe
No
> refactor: remove `--no-force` option for `init`

- test/init/__snapshots__/init.test.js.snap.webpack4
- test/init/__snapshots__/init.test.js.snap.webpack5
- test/init/init.test.js
Test update
Update snapshots
N/A
**Summary**
Add snapshot entry for generated `package.json` file content.
Nope
#2547 #2526
> test: add missing snapshot entry

- packages/serve/src/types.ts
fix
NA
NA
**Summary**
update types for `devServer` option.
No
No
> fix: update devServerOptions type

- README.md
- packages/webpack-cli/README.md
docs
NA
yes
**Summary**
- Adds init aliases
no
> docs: add init aliases

- test/build/config/type/array-function-with-argv/webpack.config.js
- test/build/config/type/array-function-with-env/webpack.config.js
- test/build/config/type/function-with-argv/webpack.config.js
- test/build/core-flags/watch-flags.test.js
chore, refactor
No
No
**Summary**
remove unnecessary console log statements.
No
No
> chore: remove spammy console statements

- OPTIONS.md
- README.md
- SERVE-OPTIONS.md
- packages/serve/src/index.ts
- packages/webpack-cli/README.md
- packages/webpack-cli/lib/webpack-cli.js
- setupTest.js
- test/build/unknown/unknown.test.js
- test/help/__snapshots__/help.test.js.snap.webpack4
- test/help/__snapshots__/help.test.js.snap.webpack5
- test/help/help.test.js
Feature
Yes
Yes
**Summary**
Add `server` alias for `serve` command. 
Usage - `webpack serve|server|s [entries...] [options]`
No
No
>  feat: add `server` alias for `serve` command

- INIT.md
Docs
N/A
Yes
**Summary**
Update `init` generator questions.
Nope
N/A
> docs: update init generator questions

- packages/generators/init-template/default/webpack.configjs.tpl
- test/init/__snapshots__/init.test.js.snap.webpack4
- test/init/__snapshots__/init.test.js.snap.webpack5
fix typo in webpack.config.js
`obout` -> `about`
> fix : fix comment typo in webpack.config.js template file

- packages/generators/package.json
- yarn.lock
chore
N/A
N/A
**Summary**
Follow up of #2623
Nope
N/A
> chore: remove stale deps

- packages/configtest/package.json
- packages/generators/package.json
- packages/info/package.json
- packages/serve/README.md
- packages/serve/package.json
- packages/webpack-cli/README.md
- packages/webpack-cli/package.json
docs
NA
Yes
**Summary**
Fix links, improve npm page contents.
Fixes #2552 
No
> docs: fix links on npm

- packages/generators/init-template/default/webpack.configjs.tpl
- packages/generators/src/handlers/default.ts
- test/init/__snapshots__/init.test.js.snap.webpack4
- test/init/__snapshots__/init.test.js.snap.webpack5
Feature
WIP, after implementation
WIll do if needed
**Summary**
Allow using MiniCSSExtractPlugin only for production if user opts for it.
No
Merge this after #2640
> feat: allow extract plugin for production only

- test/build/core-flags/experiments-flag.test.js
- test/build/core-flags/externals-flags.test.js
- test/build/core-flags/module-flags.test.js
- test/build/core-flags/optimization-flags.test.js
- test/build/core-flags/output-flags.test.js
- test/build/core-flags/performance-flags.test.js
- test/build/core-flags/resolve-flags.test.js
- test/build/core-flags/snapshot-flags.test.js
- test/build/core-flags/stats-flags.test.js
- test/build/core-flags/watch-flags.test.js
- test/utils/test-utils.js
Gets flags from `webpack.cli.getArguments` function
No
No
> test: refactor core-flags

- smoketests/helpers.js
Fix
N/A
N/A
**Summary**
clear timeouts when redundant
No
No
> fix: handle redundant timeouts in smoketest helpers

- package.json
- test/configtest/with-config-path/__snapshots__/with-config-path.test.js.snap.webpack4
- test/configtest/with-config-path/__snapshots__/with-config-path.test.js.snap.webpack5
- test/configtest/with-config-path/syntax-error.config.js
- test/configtest/with-config-path/with-config-path.test.js
- test/configtest/without-config-path-custom-extension/__snapshots__/without-config-path.test.js.snap.webpack4
- test/configtest/without-config-path-custom-extension/__snapshots__/without-config-path.test.js.snap.webpack5
- test/configtest/without-config-path-custom-extension/without-config-path.test.js
- test/configtest/without-config-path-error/__snapshots__/without-config-path-error.test.js.snap.webpack4
- test/configtest/without-config-path-error/__snapshots__/without-config-path-error.test.js.snap.webpack5
- test/configtest/without-config-path-error/without-config-path-error.test.js
- test/configtest/without-config-path-multi-compiler-mode/__snapshots__/without-config-path-multi-compiler-mode.test.js.snap.webpack4
- test/configtest/without-config-path-multi-compiler-mode/__snapshots__/without-config-path-multi-compiler-mode.test.js.snap.webpack5
- test/configtest/without-config-path-multi-compiler-mode/without-config-path-multi-compiler-mode.test.js
- test/configtest/without-config-path-no-configuration/__snapshots__/without-config-path-no-configuration.test.js.snap.webpack4
- test/configtest/without-config-path-no-configuration/__snapshots__/without-config-path-no-configuration.test.js.snap.webpack5
- test/configtest/without-config-path-no-configuration/without-config-path-no-configuration.test.js
- test/configtest/without-config-path/__snapshots__/without-config-path.test.js.snap.webpack4
- test/configtest/without-config-path/__snapshots__/without-config-path.test.js.snap.webpack5
- test/configtest/without-config-path/without-config-path.test.js
- test/utils/test-utils.js
- test/watch/analyze/analyze-flag.test.js
- test/watch/watch-variable/watch-variable.test.js
- yarn.lock
tests
it is tests
**Summary**
cc @webpack/cli-team We need to rewrite most of our tests on snapshot testing, here example how we should do it, just improve normalized and add this lines everywhere 
No
No
> test: snapshots more

- test/build/hot/__snapshots__/hot-flag.test.js.snap.webpack4
- test/build/hot/__snapshots__/hot-flag.test.js.snap.webpack5
- test/build/hot/hot-flag.test.js
- test/build/output/__snapshots__/output-named-bundles.test.js.snap.webpack4
- test/build/output/__snapshots__/output-named-bundles.test.js.snap.webpack5
- test/build/output/output-named-bundles.test.js
- test/build/stats/flags/__snapshots__/stats.test.js.snap.webpack4
- test/build/stats/flags/__snapshots__/stats.test.js.snap.webpack5
- test/build/stats/flags/stats.test.js
- test/build/target/flag-test/__snapshots__/target-flag.test.js.snap.webpack4
- test/build/target/flag-test/__snapshots__/target-flag.test.js.snap.webpack5
- test/build/target/flag-test/target-flag.test.js
- test/build/target/node/__snapshots__/node-test.test.js.snap.webpack4
- test/build/target/node/__snapshots__/node-test.test.js.snap.webpack5
- test/build/target/node/node-test.test.js
- test/build/unknown/__snapshots__/unknown.test.js.snap.webpack4
- test/build/unknown/__snapshots__/unknown.test.js.snap.webpack5
- test/build/unknown/unknown.test.js
tests and refactor
yes
NA
**Summary**
More snapshots.
No
None
> test: more snapshot testing

- test/api/get-package-manager.test.js
- test/api/prompt-installation.test.js
- test/build/entry/scss/webpack.config.js
- test/build/mode/mode-with-config/mode-with-config.test.js
- test/build/mode/mode-with-config/webpack.config2.js
- test/build/mode/mode-with-config/webpack.config3.js
chore
yep
NA
**Summary**
Cleanup warnings from lint and logs in tests
no
> chore: cleanup CI logs

- test/api/capitalizeFirstLetter.test.js
- test/api/prompt.test.js
- test/build/config/type/function-with-env/function-with-env.test.js
tests added
Improve code coverage
No
No
> test: update

- README.md
docs
No need
Yes
**Summary**
fixes #2663
No
/cc @webpack/cli-team anybody can check webpack docs on this stuff, we need remove it too
> docs: remove `webpack-scaffold`

- .github/dependabot.yml
tooling
can't
NA
**Summary**
Upgrades to GitHub native dependabot
no
Fix https://github.com/webpack/webpack-cli/pull/2676
> feat: upgrade to GitHub native dependabot

- OPTIONS.md
- package.json
- test/build/core-flags/output-flags.test.js
- yarn.lock
fix, test
yes
yet to
**Summary**
- upgrade webpack with latest flags
- 
no
Fix https://github.com/webpack/webpack-cli/pull/2701
> chore: upgrade webpack

- test/init/__snapshots__/init.test.js.snap.webpack4
- test/init/__snapshots__/init.test.js.snap.webpack5
- test/init/init.test.js
Test update
Update test suite
N/A
**Summary**
Eliminate redundancy in `init` test suite descriptions.
No
N/A
> test(init): update descriptions

- INIT.md
- packages/generators/src/index.ts
- test/help/__snapshots__/help.test.js.snap.devServer3.webpack4
- test/help/__snapshots__/help.test.js.snap.devServer3.webpack5
- test/help/__snapshots__/help.test.js.snap.devServer4.webpack4
- test/help/__snapshots__/help.test.js.snap.devServer4.webpack5
- test/init/__snapshots__/init.test.js.snap.webpack4
- test/init/__snapshots__/init.test.js.snap.webpack5
- test/init/init.test.js
Feature
Yes
Yes
**Summary**
- `webpack-cli init -t, --template <value>`
- `webpack-cli init -f, --force`
- `webpack-cli loader -t, --template <value>`
- `webpack-cli plugin -t, --template <value>`
No
N/A
> feat(generators): add aliases for options

- packages/info/README.md
- packages/info/src/index.ts
- test/help/__snapshots__/help.test.js.snap.devServer3.webpack4
- test/help/__snapshots__/help.test.js.snap.devServer3.webpack5
- test/help/__snapshots__/help.test.js.snap.devServer4.webpack4
- test/help/__snapshots__/help.test.js.snap.devServer4.webpack5
- test/info/info-output.test.js
Feature
Yes
Yes
**Summary**
`webpack-cli info -o, --output <format>`
No
N/A
> feat(init): add alias for --output

- .husky/commit-msg
fix
yes
no
**Summary**
fix husky config - https://typicode.github.io/husky/#/?id=husky_git_params-ie-commitlint-
no
> fix: husky config

- test/loader/loader.test.js
- test/plugin/plugin.test.js
Test update
This PR aims at updating the test suite
N/A
**Summary**
#2700
No
N/A
> test: increase coverage

- test/build/core-flags/experiments-flag.test.js
test, refactor;
NA
NO
**Summary**
No
No
> test: fix warning

- INIT.md
- packages/generators/init-template/default/template.html
- packages/generators/init-template/default/template.html.tpl
- packages/generators/init-template/default/webpack.configjs.tpl
- packages/generators/src/handlers/default.ts
- test/init/__snapshots__/init.test.js.snap.webpack4
- test/init/__snapshots__/init.test.js.snap.webpack5
- test/init/init.test.js
Feature
Yes
Yes
**Summary**
#2430
Added a prompt for [workbox-webpack-plugin](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin) as part of `init-generator`.
No
N/A
> feat(init-generator): configure workbox-webpack-plugin as opted

- .eslintrc.js
- packages/generators/src/handlers/default.ts
- packages/webpack-cli/lib/webpack-cli.js
- smoketests/helpers.js
- test/build/core-flags/snapshot-flags.test.js
- test/plugin/plugin.test.js
refactor
N/A
N/A
**Summary**
- Ensure consistency across the codebase.
- Enforce `prefer-const` ESLint rule https://github.com/webpack/webpack-cli/pull/2729#discussion_r636044622
- Remove unused `eslint-disable` directives.
No
N/A
> refactor: ensure consistency

- .github/workflows/nodejs.yml
chore
no
no
**Summary**
run tests on node v16
no
> chore: add node 16 on CI

- .github/workflows/nodejs.yml
Reverts webpack/webpack-cli#2758
> Revert "chore: add node 16 on CI"

- test/init/init.test.js
- test/loader/loader.test.js
- test/plugin/plugin.test.js
refactoring
Updates test suite.
N/A
**Summary**
Make use of helpers to eliminate redundancy.
No
N/A
> refactor: leverage helpers

- packages/generators/src/addon-generator.ts
- packages/generators/src/init-generator.ts
> chore(generators): do not prompt if multiple installers are not available

- OPTIONS.md
docs
No
Yes
**Summary**
update docs
no
no
> docs: update options

- test/help/__snapshots__/help.test.js.snap.devServer3.webpack4
- test/help/__snapshots__/help.test.js.snap.devServer3.webpack5
- test/help/__snapshots__/help.test.js.snap.devServer4.webpack4
- test/help/__snapshots__/help.test.js.snap.devServer4.webpack5
- test/help/help.test.js
chore
NO
No
**Summary**
Duplicate test case.
https://github.com/webpack/webpack-cli/blob/aa357c371763f2141fc10ec87d5dbd90862f3224/test/help/help.test.js#L265
https://github.com/webpack/webpack-cli/blob/aa357c371763f2141fc10ec87d5dbd90862f3224/test/help/help.test.js#L221
No
None
> test: remove duplicate testcase

- test/build/colors/colors.test.js
- test/build/colors/multi-stats-colors.webpack.config.js
- test/build/colors/stats-colors.webpack.config.js
test
Yes
No
**Summary**
add tests on `stats.colors`
No
https://github.com/webpack/webpack.js.org/pull/5217#issuecomment-884898144
> test: add more cases for colors test

- packages/serve/src/types.ts
refactor
yep
NA
**Summary**
update dev server types to be v4 compatible
no
> fix: update dev server types to v4 compatible

- .github/workflows/nodejs.yml
chore
NA
NA
**Summary**
- Use inbuilt node cache
- 
no
> chore: use default node cache

- .github/workflows/nodejs.yml
CI
No
No
**Summary**
migrate to `actions/setup-node@v2`, it seems this instance was left untouched in recent PRs.
No
No
> ci: migrate to `actions/setup-node@v2`

- .github/workflows/nodejs.yml
chore
NA
NA
**Summary**
updates the action
no
> chore: update commitlint action in CI

- test/build/core-flags/core-flags.test.js
tests
it is tests
**Summary**
test some rare options usage 
No
no
> test: more

- packages/serve/README.md
docs
NA
yes
**Summary**
update links
No
No
> docs: update serve options link

- .devcontainer/devcontainer.json
fix
No
No
**Summary**
`bootstrap` script was removed in favor of `yarn lerna bootstrap`
No
No
> fix: update `postCreateCommand` script for dev containers

- .github/ISSUE_TEMPLATE/Bug_report.md
docs
No
yes
**Summary**
Many times developers do not write about the version of packages they are using and we have to ask them manually. Adding it to the issue template will save the developer's time.
No
No
> docs: update bug report template

- packages/webpack-cli/README.md
docs
No
Yes
**Summary**
add `WEBPACK_DEV_SERVER_PACKAGE` variable
None
No
> docs: add `WEBPACK_DEV_SERVER_PACKAGE` variable

- .devcontainer/Dockerfile
chore
Not needed
Nope
**Summary**
updated image version for dev containers
Nope
> chore: update node image to 14

- README.md
docs
No
Yes
**Summary**
add links for `help` and `version` command
No
No
> docs: add links for commands

- SERVE-OPTIONS-v4.md
docs
No
Yes
**Summary**
update serve options as per `webpack-dev-server v4.2.0`
No
No
> docs: update serve options

- packages/generators/package.json
- packages/generators/src/init-generator.ts
- yarn.lock
refactor
No
No
**Summary**
webpack-cli already exports `colors`. No need for duplicate imports.
None
No
> refactor: use colors from cli

- package.json
- packages/configtest/src/index.ts
- packages/webpack-cli/lib/webpack-cli.js
- test/api/resolveConfig/resolveConfig.test.js
- test/build/stats/config/stats.test.js
- yarn.lock
refactor
no need
no need
**Summary**
Improve API, for the next major release we will do them public and documented
In theory yes, but it is internal api and should not be used
No
> Refactor code

- package.json
- packages/webpack-cli/lib/webpack-cli.js
- packages/webpack-cli/package.json
- yarn.lock
update dep
No
No
**Summary**
Update colorette,  now it provides `--color`/`--no-color` support out of the box so we don't need our own logic.
No
No
> chore: update colorette

- SERVE-OPTIONS-v4.md
docs
No
Yes
**Summary**
Update options for `serve` command.
No
No
> docs: upadte `server` options

- .github/workflows/nodejs.yml
CI.
No
**Summary**
use `yarn --frozen-lockfile` to avoid writing `yarn.lock` on CI, just like `npm ci`
None
No
> ci: use `yarn --frozen-lockfile` to install dependencies

- .github/workflows/nodejs.yml
CI
No
No
**Summary**
use node versions for CI jobs.
No
No
> ci: update lint job

- .github/workflows/nodejs.yml
**Summary**
Was already included in one part of the workflow, and this just adds it to the jobs that didn't have it
> chore: add Yarn cache to CI runs

- packages/serve/src/types.ts
**Summary**
They warning was being output onto the files tab of all PRs from the ESLint problem matcher
> chore: ignore eslint no-explicit-any warning

- .github/workflows/nodejs.yml
CI
No
No
**Summary**
Install `webpack-4` and `webpack-dev-server@latest` only when required.
> ci: do not install deps twice

- lint-staged.config.js
**Summary**
Since prettier is run across the whole repo as part of the lint job, this ensures that the files get run by the commit hook
> chore: expand lint-staged prettier glob

- .github/workflows/nodejs.yml
**Summary**
This is a duplicate of https://github.com/webpack/webpack-cli/pull/3014, but seeing if the comment that the latest core changes have addressed this are true
> ci: add Node 17

- .cspell.json
- .eslintignore
- .gitignore
- .prettierignore
chore
No
No
**Summary**
Remove stale entries from `.gitignore`, `.eslintignore`, and `.prettierignore`.
No
No
> chore: cleanup `.gitignore`, `.eslintignore`, and `.prettierignore`

- OPTIONS.md
docs
No
Yes
**Summary**
update webpack CLI options.
No
None
> docs: update webpack options

- .devcontainer/Dockerfile
chore
No
No
**Summary**
Use node v16 for dev containers.
No
No
> chore: update node image to 16

- .cspell.json
chore
No
No
**Summary**
update `cspell` configuration to ignore `node_modules` and `package-lock.json`. Otherwise it also checks for `node_modules` and `package-lock.json` files inside `test` directory.
No
No
> chore: update`cspell` configuration

- SERVE-OPTIONS-v4.md
docs
No
Yes
**Summary**
Update `server` options.
No
No
> docs: update server options

- .cspell.json
- .github/workflows/nodejs.yml
- package.json
- packages/generators/package.json
- yarn.lock
chore
No need
No need
**Summary**
Regenerate lock file
No
No
> chore: regenerate lock file

- .github/workflows/nodejs.yml
CI
No
No
**Summary**
Update workflow. Only one job for `devserver-3` and `webpack-4`.
None
No
> ci: update workflow jobs

- packages/generators/loader-template/default/test/test-utils.js.tpl
- packages/generators/loader-template/default/test/unit.test.js.tpl
- packages/generators/plugin-template/default/test/test-utils.js.tpl
- packages/generators/src/addon-generator.ts
removes bluebird from addon generator
tried in local and it worked
NA
**Summary**
as above
no
> chore: remove bluebird from installed deps in generators

- .cspell.json
- .github/workflows/nodejs.yml
- .github/workflows/update-docs.yml
- SERVE-OPTIONS-v4.md
- scripts/updateDocs.js
Enhancement, CI
No, I did manual testing on PR https://github.com/webpack/webpack-cli/pull/3210
Yes through the automation job itself.
This commit https://github.com/webpack/webpack-cli/pull/3211/commits/b1bb518d5ad31fff4ff3bcd97f1e351869b8e9ac was added automatically.
**Summary**
- Created `update-docs` CI job to update docs.
- Just add the `update docs` label to a PR and docs will be updated automatically.
No
No
> ci: add job to automate docs update

- packages/generators/src/handlers/react.ts
- test/init/__snapshots__/init.test.js.snap.webpack4
- test/init/__snapshots__/init.test.js.snap.webpack5
- test/init/init.test.js
bugfix
Yes
Fix generating recat template.
https://user-images.githubusercontent.com/46647141/168454856-65a7a436-1aef-4c43-b409-0638e67ac7f2.mov
https://user-images.githubusercontent.com/46647141/168454862-bfca4d74-02c6-498b-8c91-a805854332c9.mov
> fix: correct react template generation

- README.md
docs
NA
Yes
**Summary**
Rm outdated badge
no
> chore: remove broken deps url

- smoketests/helpers.js
chore
👍🏽 
N/A
**Summary**
Increase timeout
> chore: update smoketest

- package.json
- packages/webpack-cli/src/webpack-cli.ts
- test/build/config-format/typescript-esnext/tsconfig.json
- test/build/config-format/typescript-esnext/typescript.test.js
- yarn.lock
fix
No
No
**Summary**
Fix https://github.com/webpack/webpack-cli/pull/3262
Update typescript to v4.7.2
No
No
> chore: update typescript and fix build

- package.json
- packages/webpack-cli/package.json
Added funding field in package.json
N/A
**Summary**
No
> chore: update package.json

- README.md
docs
No
Yes
**Summary**
remove redundant link
No
No
> docs: remove redundant link

- open-bot.yml
chore
N/A
N/A
**Summary**
There is a spam label added in every PR with low changes. It doesn't serve any purpose.
Nope
N/A
> chore: remove spam label

- packages/configtest/README.md
- packages/info/README.md
- packages/serve/README.md
docs
Not needed
Bet
**Summary**
Update docs
Nope
N/A
> docs: update to use note syntax

- .cspell.json
- .devcontainer/devcontainer.json
chore
N/A
N/A
**Summary**
we don't need `lerna bootstrap` command in dev container.
Nope
N/A
> chore: remove unnecessary step

- .devcontainer/Dockerfile
chore
N/A
N/A
**Summary**
use `node:lts` image so that we don't need to update this again in future.
Nope
fixes #3244 
closes #3244
> chore: use node:lts image

- test/api/generators/helpers.test.js
Add tests for helper methods to improve coverage by little
yep
> test: add test for helpers

- .cspell.json
chore
**Summary**
Ignore the coverage directory for `cspell`, otherwise, we can have errors in local development.
No
No
> chore: ignore the coverage directory for `cspell`

- packages/configtest/package.json
- packages/generators/package.json
- packages/info/package.json
- packages/serve/package.json
- packages/webpack-cli/package.json
Breaking change.
No.
No.
**Summary**
Follow up https://github.com/webpack/webpack-cli/pull/3251
The minimum supported Node.js version is `14.15.0`.
BREAKING CHANGE: The minimum supported Node.js version is `14.15.0`
> refactor!: the minimum supported Node.js version is `14.15.0`

- .github/workflows/nodejs.yml
- test/serve/basic/function-with-argv.config.js
- test/serve/basic/function-with-env.config.js
- test/serve/basic/helper/base-dev-server.config.js
- test/serve/basic/log.config.js
- test/serve/basic/multi-dev-server-output-public-path.config.js
- test/serve/basic/multi-output-public-path.config.js
- test/serve/basic/output-public-path.config.js
- test/serve/basic/serve-basic.test.js
- test/serve/basic/serve.config.js
- test/serve/basic/stats.config.js
- test/serve/basic/watch.config.js
- test/serve/basic/webpack.config.js
- test/serve/serve-variable/serve-variable.test.js
- test/serve/with-custom-port/serve-custom-config.test.js
Refactor
Removed tests related to v3.
No
**Summary**
Drop `webpack-dev-server` v3 form CI and tests
No
No
> refactor: drop webpack-dev-server v3 form CI and tests

- packages/serve/src/index.ts
- packages/webpack-cli/src/webpack-cli.ts
refactor
Already present.
No.
**Summary**
Drop support for webpack-dev-server v3.
BREAKING CHANGE: The minimum supported `webpack-dev-server` version is `v4.0.0`
No
> refactor!: the minimun supported `webpack-dev-server` version is `v4.0.0`

- package.json
- test/api/get-default-package-manager.test.js
- yarn.lock
chore
No.
No.
**Summary**
Remove `@webpack-cli/migrate` dependency
No
No
> chore: remove `@webpack-cli/migrate` dependency

- packages/info/src/index.ts
Feature.
No
No.
**Summary**
Show information for webpack-cli packages by default
No
No
> feat(info): show information for webpack-cli packages by default

- test/help/help.test.js
- test/utils/test-utils.js
chore
No
No
**Summary**
Remove `isDevServer4` util.
No
No
> chore: remove `isDevServer4` util

- test/build/entry/flag-entry/entry-with-flag.test.js
- test/build/entry/flag-entry/entry.config.js
- test/build/entry/flag-entry/src/index.cjs
tests.
Yes.
No.
**Summary**
Add more tests for the `--entry-reset` flag.
No
No
> test: add test cases for `--entry-reset`

- yarn.lock
update lock file to fix tests
No need
No need
**Summary**
Above
No
No
> chore(deps): update lock file

- package.json
- yarn.lock
deps update.
No.
No.
**Summary**
Fix https://github.com/webpack/webpack-cli/pull/3391
No
No
> chore: update eslint to v8.23.0

- .github/workflows/nodejs.yml
- smoketests/missing-packages/prettier.test.js
CI
No.
No.
**Summary**
Add different jobs for smoke tests.
No
No
> ci: add separate job for smoketests

- .cspell.json
chore
No
No
**Summary**
Ignore log files. It throws lint errors locally otherwise.
No
No
> chore: ignore log files for cspell

- .github/workflows/nodejs.yml
CI
No
No
**Summary**
Update the `wagoid/commitlint-github-action` to v5.
No
No
> ci: update commitlint action

- package.json
- yarn.lock
chore
No
No
**Summary**
remove cz-customizable dependency, not used.
No
No
> chore: remove cz-customizable dependency

- README.md
Improve grammar of README
N/A
Yeah!
**Summary**
Revise donation section to be more approachable
N/A
> docs(readme): revise into more approachable naming

- .cspell.json
- package.json
- yarn.lock
chore
No
No
**Summary**
Update cspell to v6.
No
No
> chore: update cspell to v6

- packages/webpack-cli/package.json
- test/build/config-format/failure/failure.test.js
- test/build/config-format/failure/webpack.config.json5
- yarn.lock
chore
No.
No.
**Summary**
Update `interpret` dependency to v3.
https://github.com/gulpjs/interpret/releases/tag/v3.0.0
https://github.com/gulpjs/rechoir/releases/tag/v0.8.0
No
> chore: udpate `interpret` to v3 and `rechoir` to v0.8

- package.json
Chore
No need
No need
**Summary**
Nothing
No
One small line before publish
> chore: peer deps in root package

- packages/serve/src/index.ts
refactor.
No.
No.
**Summary**
Remove compatibility with the old stdin option for webpack-dev-server.
We already dropped compatibility with webpack-dev-server@v3 earlier.
No
> refactor: remove compatibility with old `stdin` option for `webpack-dev-server`

- .github/workflows/nodejs.yml
- .github/workflows/update-docs.yml
CI
No.
No.
**Summary**
Use the [Node.js LTS version syntax](https://github.com/actions/setup-node#supported-version-syntax) so we don't have to manually update the node version in the future.
No
No
> ci: use LTS node version in workflows

- packages/webpack-cli/src/webpack-cli.ts
- test/build/config/named-export/mjs.test.js
- test/build/config/named-export/webpack.config.mjs
bugfix
Yes
No need
**Summary**
fixes https://github.com/webpack/webpack-cli/issues/3684
No
No
> fix: error message for missing default export in configuration

- packages/generators/src/init-generator.ts
- smoketests/missing-packages/prettier.test.js
No
**Summary**
Fixes https://github.com/webpack/webpack-cli/issues/3719
> fix(init): don't ask to install prettier when using `--force`

- README.md
Docs
N/A
Yea
**Summary**
Changes into more informal first section
N/A
N/A
> chore(docs): revise wording

- packages/README.md
docs update
No need
No need
**Summary**
No need
No need
No need
> docs: update

- OPTIONS.md
- SERVE-OPTIONS-v4.md
- packages/webpack-cli/src/webpack-cli.ts
- test/help/__snapshots__/help.test.js.snap.devServer4.webpack5
- yarn.lock
Update lock file to run on new webpack-cli
Test
No need
**Summary**
No
No
No
> chore: update lock file

- package.json
- yarn.lock
Update typescript to v5
No need
No need
**Summary**
Just update
No
No
> chore: update typescript

- README.md
docs
No
No
**Summary**
Add the GitHub discussions badge and remove the Gitter badge.
No
No
> docs: add GitHub discussions badge

- .github/ISSUE_TEMPLATE.md
docs
No
No
**Summary**
Remove gitter in favor of GitHub discussions.
No
No
> docs: update issue template to refer to GitHub Discussions

- packages/configtest/src/index.ts
- packages/generators/src/addon-generator.ts
- packages/generators/src/custom-generator.ts
- packages/generators/src/handlers/default.ts
- packages/generators/src/handlers/react.ts
- packages/generators/src/index.ts
- packages/generators/src/init-generator.ts
- packages/generators/src/loader-generator.ts
- packages/generators/src/plugin-generator.ts
- packages/generators/src/types/index.ts
- packages/generators/src/utils/helpers.ts
- packages/generators/src/utils/scaffold-utils.ts
- packages/info/src/index.ts
- packages/serve/src/index.ts
- packages/webpack-cli/src/bootstrap.ts
- packages/webpack-cli/src/index.ts
- packages/webpack-cli/src/plugins/cli-plugin.ts
- packages/webpack-cli/src/types.ts
- packages/webpack-cli/src/utils/dynamic-import-loader.ts
- packages/webpack-cli/src/webpack-cli.ts
Refactor - use `type` - better readability + better perf
No need
No need
**Summary**
Above
No
Also extra class from types, because it is not a type
> refactor: use `type` for types

- packages/webpack-cli/src/plugins/cli-plugin.ts
- packages/webpack-cli/src/types.ts
Chore, fix eslint warnings
No need
No need
**Summary**
No need
No
No need
> chore: fix eslint warnings

- .cspell.json
- .github/CONTRIBUTING.md
Documentation on updating dependencies.
N/A
Yeah
**Summary**
Updates CONTRIBUTING.md and cspell word added.
No
N/A
> docs(contributing): add section on upgrading dependencies

- lint-staged.config.js
- package.json
- packages/generators/package.json
- packages/generators/src/handlers/default.ts
- test/utils/test-utils.test.js
- yarn.lock
chore and stability our tests
No need
No need
**Summary**
No need
No
No
> chore(deps): bump

- .github/workflows/dependency-review.yml
- .github/workflows/nodejs.yml
- .github/workflows/update-docs.yml
CI
NO
No
**Summary**
update github actions
No
No
> ci: update github actions

- packages/generators/init-template/default/webpack.configjs.tpl
- packages/generators/init-template/react/webpack.config.js.tpl
- test/init/__snapshots__/init.test.js.snap.webpack5
bugfix
Yes
No
**Summary**
Fixes https://github.com/webpack/webpack-cli/pull/3984
No
No
> fix(init): use strict checks intemplate configs

- jest.config.js
chore
No
No
**Summary**
- remove webpack v4 check
- [`node_modules` are ignored by default.](https://jestjs.io/docs/configuration#testpathignorepatterns-arraystring)
No
https://jestjs.io/docs/configuration#testpathignorepatterns-arraystring
> chore: remove webpack@4 check from `jest.config.js`

- OPTIONS.md
- package.json
- yarn.lock
docs
No
Yes
**Summary**
Update webpack and options in docs.
No
No
> chore: update webpack & options

- .github/workflows/nodejs.yml
- scripts/setup-test.js
- test/build/json/json.test.js
- test/build/unknown/unknown.test.js
- test/help/__snapshots__/help.test.js.snap.devServer4.webpack5
- test/help/__snapshots__/help.test.js.snap.devServer5.webpack5
- test/help/help.test.js
- test/loader/loader.test.js
- test/plugin/plugin.test.js
- test/serve/basic/serve-basic.test.js
- test/utils/test-utils.js
CI
No
No
**Summary**
add Node.js v21
No
No
> ci: add Node.js v21

- package.json
- packages/webpack-cli/src/webpack-cli.ts
- yarn.lock
chore
No
**Summary**
Update webpack. Fix #4089 
No
No
> chore: update webpack to v5.90.3

- .github/workflows/nodejs.yml
CI
No need
No need
**Summary**
Validate commits
No
No
> ci: commitlint

- .github/workflows/nodejs.yml
- test/utils/test-utils.js
No
No
**Summary**
Run tests on Node v22.
No
No
> ci: add Node v22

- README.md
> chore(funding): Update README.md

- yarn.lock
Reverts dependabot prs
N/A
N/A
**Summary**
N/A
N/A
N/A
> Fix: revert pkg upgrades because of CI failure

- packages/README.md
- test/build/config-format/typescript-esnext/typescript.test.js
- test/build/config-name/config-name.test.js
- test/create-webpack-app/test.utils.js
minor improvements
**Summary**
> minor improvements

- packages/create-webpack-app/package.json
- packages/create-webpack-app/src/generators/init/default.ts
- packages/create-webpack-app/src/generators/init/react.ts
- packages/create-webpack-app/src/generators/init/svelte.ts
- packages/create-webpack-app/src/generators/init/vue.ts
- packages/create-webpack-app/src/generators/loader/default.ts
- packages/create-webpack-app/src/generators/plugin/default.ts
- packages/create-webpack-app/src/index.ts
- packages/create-webpack-app/src/plopfile.ts
- packages/create-webpack-app/src/types.ts
- packages/create-webpack-app/src/utils/fileGenerator.ts
- packages/create-webpack-app/src/utils/logger.ts
- packages/create-webpack-app/src/utils/pkgInstallAction.ts
refactoring before release
Existing
No need
**Summary**
Small nitpics
No
We don't need `webpack-cli` as peer dep only for types, i.e. less install size
> refactor: create-webpack-app

- packages/configtest/package.json
- packages/info/package.json
- packages/serve/package.json
Fix https://github.com/webpack/webpack-cli/issues/4354
No
**Summary**
Fix peer dependencies. webpack-cli v6 & webpack v5.82.0 or later.
No
No
> fix: update peer dependencies

- CHANGELOG.md
docs
No
Yes
**Summary**
Fix https://github.com/webpack/webpack-cli/pull/4318#issuecomment-2561895412
> docs: update breaking changes for v6

- packages/webpack-cli/README.md
docs
NA
Yes
**Summary**
update options and commands to latest.
No
No
> docs: update CLI options & commands

- .github/workflows/nodejs.yml
- yarn.lock
ci
Existing
No need
**Summary**
test in windows node@24
No
No
> ci: node v24 windows

- packages/webpack-cli/src/types.ts
- packages/webpack-cli/src/webpack-cli.ts
refacotr, before we were using it in generators, but now we don't need this
No need
No
**Summary**
Just cleanup
Potential yes
No
> chore: remove unused code
