- bin/config-yargs.js
- bin/webpack.js
- example/neo-webpack.config.js
- example/webpack.config.js
- lib/migrate.js
- lib/transformations/defineTest.js
- lib/transformations/index.js
- lib/transformations/loaders/loaders.js
- lib/transformations/resolve/__testfixtures__/resolve.input.js
- lib/transformations/resolve/__testfixtures__/resolve.output.js
- lib/transformations/resolve/__tests__/resolve.test.js
- lib/transformations/resolve/resolve.js
- lib/transformations/safeTraverse.js
- package.json
Adds a raw implementation of migrate.
Adds transformation for resolve.root
Here's a gif of the change
Yes
**Summary**
No
> Feat - Adds basic code for implementing migrate command

- .eslintignore
- .eslintrc.json
- bin/convert-argv.js
- bin/process-options.js
- lib/parser/resolve-packages.js
- lib/parser/validateOptions.js
- lib/transformations/defineTest.js
- lib/transformations/loaders/__tests__/loaders.test.js
- lib/transformations/resolve/__tests__/resolve.test.js
- lib/transformations/safeTraverse.js
- package.json
- tests/__tests__/inquirer/inquirer.test.js
- tests/__tests__/parser/resolve.test.js
- tests/__tests__/parser/validate.test.js
build related change
Not needed
Not needed
**Summary**
https://github.com/mysticatea/eslint-plugin-node implements some useful checks that can preven bugs related to Node. One of my favorites is https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unsupported-features.md that checks our code againt `engines` field of package.json and doesn't allow using unsupported ES2015 features.
No
This is WIP!
> Feature: Add eslint-plugin-node and configure it

- bin/webpack.js
- lib/migrate.js
This PR is an ongoing work on #6 which enables to pass the path to webpack config as argument. It will overwrite it if confirmed by the user.
> fix: Use real paths from argvs instead of dummy hard-coded file

- __mocks__/inquirer/initialize.mock.js
- lib/inquirer-prompt.spec.js
- lib/parser/validate-options.spec.js
- lib/transformations/__snapshots__/index.test.js.snap
- lib/transformations/__snapshots__/utils.test.js.snap
- lib/transformations/bannerPlugin/__snapshots__/bannerPlugin.test.js.snap
- lib/transformations/extractTextPlugin/__snapshots__/extractTextPlugin.test.js.snap
- lib/transformations/loaderOptionsPlugin/__snapshots__/loaderOptionsPlugin.test.js.snap
- lib/transformations/loaders/__snapshots__/loaders.test.js.snap
- lib/transformations/removeDeprecatedPlugins/__snapshots__/removeDeprecatedPlugins.test.js.snap
- lib/transformations/removeJsonLoader/__snapshots__/removeJsonLoader.test.js.snap
- lib/transformations/resolve/__snapshots__/resolve.test.js.snap
- lib/transformations/uglifyJsPlugin/__snapshots__/uglifyJsPlugin.test.js.snap
- lib/utils/npm-exists.spec.js
- lib/utils/resolve-packages.spec.js
- lib/utils/validate-addons.spec.js
- package.json
> Upgrade to Jest 19

- lib/transformations/__snapshots__/utils.test.js.snap
- lib/transformations/outputPath/__snapshots__/outputPath.test.js.snap
- lib/transformations/outputPath/__testfixtures__/outputPath-0.input.js
- lib/transformations/outputPath/__testfixtures__/outputPath-1.input.js
- lib/transformations/outputPath/__testfixtures__/outputPath-2.input.js
- lib/transformations/outputPath/outputPath.js
- lib/transformations/outputPath/outputPath.test.js
- lib/transformations/utils.js
- lib/transformations/utils.test.js
This tries to address #73 
Yep
NA
**Summary**
To summarise, it tries to implement what was promised in #73
> feat: Adds a resolved path for output

- lib/transformations/defineTest.js
- lib/transformations/index.js
- lib/transformations/removeDeprecatedPlugins/__snapshots__/removeDeprecatedPlugins.test.js.snap
- lib/transformations/removeDeprecatedPlugins/__testfixtures__/removeDeprecatedPlugins-3.input.js
- lib/transformations/removeDeprecatedPlugins/removeDeprecatedPlugins.js
- lib/transformations/removeDeprecatedPlugins/removeDeprecatedPlugins.test.js
- package.json
bugfix
Yes
N/A
**Summary**
It fixes #83 and shows a nice error message for unsupported cases:
Nope
For now, only plugins instantiated in an array can be removed by deprecated plugins transform since this is safe.
> Fix: Only try to remove deprecated plugins from array expressions

- lib/transformations/removeDeprecatedPlugins/__snapshots__/removeDeprecatedPlugins.test.js.snap
- lib/transformations/removeDeprecatedPlugins/__testfixtures__/removeDeprecatedPlugins-4.input.js
- lib/transformations/removeDeprecatedPlugins/removeDeprecatedPlugins.js
- lib/transformations/removeDeprecatedPlugins/removeDeprecatedPlugins.test.js
Fix for the already merged #91
> Use safeTraverse where appropriate

- bin/webpack.js
- lib/migrate.js
- lib/transformations/__testfixtures__/failing.js
- lib/transformations/defineTest.js
- lib/transformations/index.js
- lib/transformations/index.test.js
- package.json
feature
Yes
N/A
**Summary**
This PR introduces better progress and error messages for failing transforms.
No
> Feature: Use listr to display progress and errors for transformations

- .travis.yml
This PR should enable the codecov reporting on PR during the Travis build
> build: Enable codecov integration during Travis build

- INIT.md
- README.md
- SCAFFOLDING.md
- bin/webpack.js
- lib/creator/yeoman/webpack-generator.js
- package.json
Updates documentation to use `webpack-cli init` instead of `webpack-cli --init` and fixes the `bin` folder accordingly.
> enhancements: update docs and fix bin

- lib/creator/yeoman/webpack-generator.js
Example of problem:
```
$ webpack-cli init
Insecure about some of the questions?
https://github.com/webpack/webpack-cli/blob/master/INIT.md
? Will you be creating multiple bundles? No
? Which module will be the first to enter the application? ./src
? Which folder will your generated bundles be in? [default: dist]:
? Are you going to use this in production? No
? Will you be using ES2015? No
? Will you use one of the below CSS solutions? No
? If you want to bundle your CSS files, what will you name the bundle? (press enter to skip)
? Name your 'webpack.[name].js?' [default: 'config']:
... (npm output) ...
Congratulations! Your new webpack configuration file has been created!
$ webpack
Invalid configuration object. Webpack has been initialised using a configuration object that does not match …
```
> ensure default output path is absolute

- lib/transformations/utils.test.js
Corrects a missused test function in the wrong test case.
> fix: use correct test function

- lib/creator/yeoman/webpack-generator.js
Bugfix
No (none in repo)
N/A
**Summary**
Raised in #135, but I didn't address this outstanding problem in the previous PR.
The config generated uses `presets: ['es2015']`, see: https://github.com/webpack/webpack-cli/blob/master/lib/creator/yeoman/utils/module.js#L8
... but are previously installing `babel-preset-env` instead, which results in: `Error: Couldn't find preset "es2015"` when user answers `'y'` to 'Will you be using ES2015?', then runs `webpack`.
No
> fix: Install correct (`es2015`) babel preset to match generated config

- CHANGELOG.md
Add CHANGELOG.md file.
Generated using cz-conventional-changelog cli tool.
This address issue #130
> docs: create initial CHANGELOG.md file

- CHANGELOG.md
Thank to @avivr for his help on this 🔥
> Initial Changelog

- package.json
build related change
Not relevant
Not relevant
**Summary**
Jest can be configured to run in Node env only without emulating browser with JSDOM: https://facebook.github.io/jest/docs/en/configuration.html#testenvironment-string
This improves tests running speed significantly:
```
Test Suites: 31 passed, 31 total
Tests:       1 skipped, 126 passed, 127 total
Snapshots:   110 passed, 110 total
Time:        24.577s
```
```
Test Suites: 31 passed, 31 total
Tests:       1 skipped, 126 passed, 127 total
Snapshots:   110 passed, 110 total
Time:        15.168s, estimated 19s
```
> chore(tests): Use node env for Jest to avoid JSDOM overhead

- lib/creator/yeoman/utils/entry.js
Add example when prompting for single / multiple entries.
No
No
**Summary**
Address issue #162 
No
Sample screenshot -
> feat: add examples for single and multiple entries prompt (#162)

- lib/creator/yeoman/utils/entry.js
Bugfix
N/A
N/A
**Summary**
When using `webpack-cli init` and answering the questions for 'multiple' entry files, the examples given are misleading.
The main issue is that following the format of one example will lead to a `.js.js` extension, so the resulting config will not be valid.
See [comments here](https://github.com/webpack/webpack-cli/commit/37c40f046bec586819263361e56fc90dc3309e08) for more details.
No
> fix: Give examples that are valid (and clearer).

- lib/transformations/__snapshots__/index.test.js.snap
- lib/transformations/loaderOptionsPlugin/__snapshots__/loaderOptionsPlugin.test.js.snap
- lib/transformations/loaderOptionsPlugin/__testfixtures__/loaderOptionsPlugin-1.input.js
- lib/transformations/loaderOptionsPlugin/__testfixtures__/loaderOptionsPlugin-2.input.js
- lib/transformations/loaderOptionsPlugin/loaderOptionsPlugin.js
`webpack.optimize.LoaderOptionsPlugin` should be `webpack.LoaderOptionsPlugin`
Closes #171 
bugfix
yes
n/a
**Summary**
See #171 
No
> fix(migrate): Fix migration of LoaderOptionsPlugin

- lib/creator/yeoman/webpack-generator.js
Always use `path.resolve()` when writing the `output.path`.
Nope.
Nope.
**Summary**
Previously, using the default value of "dist" would correctly use `path.resolve()` when specifying an output path, whereas specifying a custom path would use that path directly without `path.resolve()`. This PR should make it more consistent. 🤞 
Nope.
Fixes #177
> Use path.join() when specifying output directory

- MIGRATE.md
Documentation
No tests needed
Yes
**Summary**
This resolves issue #166 by adding documentation for the `migrate` command
No breaking changes
I have created a sandbox repo that documents the research / approach / testing done for this PR
https://github.com/thescientist13/webpack-migrate-sandbox
I created a PR that shows the "after" effect of running `webpack-cli migrate`
https://github.com/thescientist13/webpack-migrate-sandbox/pull/1
I also have a couple of questions / observations
1.  When running  `webpack-cli init`, the prompt for location could make it clearer that an extension …
> migrate documentation

- .gitignore
- CONTRIBUTING.md
Update Documentation for v2
_n/a_
yes
**Summary**
Removed any mention of `commit-validator` as it is no longer relevant.
I did see a task `prepare` is this a `prepublish` task? or should the docs now mention this?
n/a
> V2 docs/remove commit validator

- .travis.yml
- open-bot.yml
- package.json
Feature
No
No
**Summary**
Fixes https://github.com/webpack/webpack-cli/issues/195
No 
The configuration is copied from `webpack` repository and adapted to the current repository. The actions that the bot will do are:
- Adding labels `CI-ok` and `CI-not-ok` to the PRs **(labels needed)**
- Reporting error if linter and tests fail
- Reporting general error
- Adding label `PR: conflict` **(labels needed)**
- Adding labels `unreviewed`, `reviewed` and `review-outdated` to the PRs **(labels needed)**
- Adding label `PR: small` if the PR contains small changes **(label needed)**
- Adds a …
> [Feature] Open bot to the webpack-cli

- bin/config-yargs.js
- bin/convert-argv.js
- bin/webpack.js
N/A (?)
Will create issue and add to backlog from webpack/webpack
**Summary**
This disables `webpack in out` for entry and output properties now that `webpack` alone will generate the defaults. 
* Instead if you would like to pass an array of entries, and output, you must specify `-o`: `webpack entry1.js entry2.js -o "[name].js"`
* If a relpath is specified, the defaulted output.path property will be overridden with the specified relpath, and filename will be name of the file from relpath. If no `./` infront of value, then output.path will yield to webpack's default to `path.join(process.cwd(), "dist")` .
* mode will also be defaulted so mode checks …
> feat(0CJS): add remaining compat for new defaults to output path

- .appveyor.yml
- .editorconfig
- .gitignore
- .travis.yml
- bin/webpack.js
- package.json
- test/BinTestCases.test.js
- test/helpers/exec-in-directory.js
- yarn.lock
bugfix, CI
yes
N/A
**Summary**
fix coverage for binCases
fix prettier for bin and test
fix lint for windows users
improve reporting for CI
no
> fix CI coverage capturing and reporting

- bin/webpack.js
bugfix
Nope, wanted to extend tests for `--json` but couldn't find any. Should I do so? (tests are actually failing locally for me, even without my change)
nope, not needed IMHO
**Summary**
Fixes https://github.com/webpack/webpack/issues/6307
nope
> fix(json): json parameter now enables modules

- .eslintrc.js
- .gitignore
- bin/webpack.js
- test/binCases/errors/info-verbosity/stdin.js
- test/binCases/errors/info-verbosity/test.opts
- test/binCases/errors/info-verbosity/webpack.config.js
- test/binCases/watch/info-verbosity-off/stdin.js
- test/binCases/watch/info-verbosity-off/test.opts
- test/binCases/watch/info-verbosity-off/webpack.config.js
- test/binCases/watch/info-verbosity-verbose/stdin.js
- test/binCases/watch/info-verbosity-verbose/test.opts
- test/binCases/watch/info-verbosity-verbose/webpack.config.js
Adds `infoVerbosity` option which is set to `info` by default. In order for user to be able to control the amount of extra messaging output. 
Provides clear indication of when compilation had started and when it had finished if such verbosity is requested
Fixes webpack/webpack#6051 and webpack/webpack#5895
Yes
Also added PR for json schema validation of the option: webpack/webpack#6332
UPD: we wont add these to webpkac/webpack's schema, instead we can create our own in webpack-cli
*Not yet had been approved*
**Summary**
See webpack/webpack#6051 and webpack/webpack#5895
no
> Improvement: add an option to watch messaging. Add .idea to .gitignore

- .eslintrc.js
- bin/convert-argv.js
- bin/process-options.js
- bin/webpack.js
> refactor(convert-args): remove unused arguments

- package.json
Fixes #182
No
No
**Summary**
This is just a quick fix where we change the protocol `git://` to `https://` to allow most of the proxies to be able to download the cli. A further fix is to ask to release a new version with our patch.
No
> Change from git:// to https://

- bin/config-yargs.js
- bin/convert-argv.js
- bin/errorHelpers.js
- bin/process-options.js
- bin/webpack.js
Refactor bin directory to be aligned with code style according to node version support.
it is not necessary
**Summary**
no
> Refactor bin directory

- .gitignore
- bin/webpack.js
- test/binCases/help/help-output-no-command/stdin.js
Shows the full help content when no arguments are given to the CLI, and when the webpack build fails. 
Yes.
**Summary**
See https://github.com/webpack/webpack-cli/issues/124
Before, when running the webpack build without a config, the CLI runs webpack with the default config, and fails with an unhelpful, possibly confusing error message. The original issue suggests to show help to solve this issue.
The reasons behind these specific conditions is to allow the default configuration to run as-is without arguments.
No
> Show help on no command

- bin/config-yargs.js
- bin/webpack.js
- test/binCases/errors/info-verbosity/stdin.js
Validation in proper place
yes
**Summary**
FIxes #249 and small refactor of similar enum string options
> Issue 249 fixed and other enums refactored

- .appveyor.yml
- .cz-config.js
- .eslintignore
- .npmignore
- .travis.yml
- CHANGELOG.md
- build/changelog-generator/index.js
- build/changelog-generator/templates/commit.hbs
- build/changelog-generator/templates/header.hbs
- build/changelog-generator/templates/template.hbs
- commitlint.config.js
- package.json
- yarn.lock
Feature
n/a
n/a
**Summary**
Adds project utilities like commitlint, changelog 
> feat(chore): add project tools and utilities

- bin/convert-argv.js
- bin/prepareOptions.js
- bin/process-options.js
* small code duplication reduce
* use `process.exitCode = 1` vs `process.exit(1)` 
https://nodejs.org/dist/latest-v9.x/docs/api/process.html#process_process_exit_code
>Rather than calling process.exit() directly, the code should set the process.exitCode and allow the process to exit naturally by avoiding scheduling any additional work for the event loop:
no
not relevant
**Summary**
Progressing in the `bin` directory
no
none
> misc(refactor): reduce code duplication use process.exitCode instead of process.exit

- MIGRATE.md
- Improve migration output for sample webpack config.
- Comparison variable parity
Enhancement
**Summary**
Actual output:
No
> Improve sample migration output

- bin/config-yargs.js
Enhancement
**Summary**
Add missing description for `module-bind-post` and `module-bind-pre` arguments
Docs [link](https://webpack.js.org/api/cli/#module-options) for the same.
No
> misc(yargs): add description for module-bind-* args

- package.json
Dependencies definition, Fixes #295 
**Summary**
Adds webpack 4 as a peer dependency
No
Followed same versioning as [webpack-dev-server](https://github.com/webpack/webpack-dev-server/blob/master/package.json#L42)
> misc(dep): add webpack 4 as peer dependency

- schemas/webpackConfigurationSchema.json
- updates configuration schema to use `"instanceof": "Promise"` (webpack/webpack-cli#258)
feature/refactoring
Covered by existing tests.
n/a
**Summary**
Previously, validation for `Promise` configurations passed via `"instanceof": "Function"`, with `webpack@4+` (`ajv-keywords@3+`), we can do strict validation on `"instanceof": "Promise"`.
To accommodate this change we have to change the check to `anyOf` due to `Promise` passing `"type": "object"`.
```js
> const Ajv = require('ajv');
undefined
> const ajv = new Ajv;
undefined
> ajv.validate({type:'object'}, new Promise(res => res));
true
```
> [feature] strict Promise configuration validation

- bin/webpack.js
- lib/commands/serve.js
- lib/generators/add-generator.js
- lib/generators/init-generator.js
- lib/generators/remove-generator.js
- lib/generators/update-generator.js
- lib/generators/webpack-generator.js
- lib/init/index.js
- package.json
- yarn.lock
Fixes the issue with yeoman-generator fork. Fixes #291 :bug: 
- Update `yeoman-generator` module path in package.json to match the syntax [recommended by npm](https://docs.npmjs.com/files/package.json#repository). 
- Change the module name and usage from `"webpack-fork-yeoman-generator"` to `"yeoman-generator"` across all files.
**Tests**
All tests pass. :100: Also, did a quick test with:
```bash
mkdir test-dir && cd test-dir;
mkdir src && touch src/index.js;
webpack-cli init
```
> (Update): Added a temp `eslint-disable-line` to pass CI. For more description check comments.
**Summary**
Also, now we don't need to [published](https://www.npmjs.com/package/webpack-fork-yeoman-generator) the fork separately.
Related commit …
> fix: yeoman-generator fork issue

- README.md
Enhancement
**Summary**
The only way to currently check the latest release is hopping manually to [npmjs](https://www.npmjs.com/package/webpack-cli).
The [GitHub releases](https://www.npmjs.com/package/webpack-cli) are outdated too.
[![npm](https://img.shields.io/npm/v/webpack-cli.svg)](https://www.npmjs.com/package/webpack-cli)
Added a badge in readme for npm version. We should also update releases on GitHub.
No
> misc(readme): add npm badge

- bin/process-options.js
- bin/webpack.js
bugfix
n/a
**Summary**
`Tapable#apply` is deprecated.
no
Fix #304
> cli(taptable): Remove Tapable#apply calls

- lib/migrate/loaders/__snapshots__/loaders.test.js.snap
- lib/migrate/loaders/__testfixtures__/loaders-9.input.js
- lib/migrate/loaders/loaders.js
bugfix
Yes
NA
**Summary**
Fixes #159 
> fix(migrate): move options to use

- README.md
Documentation
N/A
Yes
**Summary**
This PR updates the README to remove inconsistent messaging about the old webpack CLI. See #327.
No
Fixes #327
> Update README to remove inconsistent CLI messaging

- lib/generators/init-generator.js
- lib/init/transformations/top-scope/__snapshots__/top-scope.test.js.snap
Enhancement
**Summary**
Code cleanup
- variable names parity
- ~`let`~ => `const`
- shorten code, use ternary operator
No
> misc(init-generator): cleanup

- lib/migrate/__snapshots__/index.test.js.snap
- lib/migrate/loaderOptionsPlugin/__snapshots__/loaderOptionsPlugin.test.js.snap
- lib/migrate/loaderOptionsPlugin/loaderOptionsPlugin.js
bugfix - removes `debug` in `migrate`.
No
n/a
**Summary**
Fixes [120](https://github.com/webpack/webpack-cli/issues/120) : removes `debug` after running `migrate` on a config that has debug
No
n/a
> fix: removes debug in migrate

- bin/process-options.js
- bin/webpack.js
- test/binCases/stats/build-delimiter/index.js
- test/binCases/stats/build-delimiter/stdin.js
- test/binCases/stats/build-delimiter/test.opts
Feature
Yes
N/A
**Summary**
This PR introduces a new `--build-delimiter` CLI option to add opt-in support for custom text after  normal build output. This feature is useful for tooling that parses `stdout`, originally arose from webpack/webpack#6002, and resolves #192.
No
I was unsure of the purpose of `bin/process-options.js` as it doesn't appear to be used anywhere. I noticed this file has been recently updated, so I added the CLI option to both `bin/process-options.js` and `bin/webpack.js`.
> Support --build-delimiter for opt-in output delimiter

- lib/generators/init-generator.js
- lib/generators/utils/module.js
> cli(init): fix init regexp

- lib/generators/init-generator.js
Bugfix
**Summary**
Current behaviour is `init` doesn't add `webpack-cli` dependency to the generated package.json which needs to added manually later.
This PR adds `webpack-cli` to the list of dependencies to be installed with `init` command.
No
> cli(init): fix webpack-cli dep

- .github/ISSUE_TEMPLATE.md
- bin/webpack.js
- lib/commands/info.js
- lib/index.js
- package-lock.json
- package.json
This adds a new feature: a `webpack-cli info` command which outputs something like this:
```
System:
OS: macOS High Sierra 10.13
CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
Binaries:
Node: 8.10.0
Yarn: 1.5.1
npm: 5.6.0
Browsers:
Chrome: 65.0.3325.181
Firefox: 58.0
Safari: 11.0
npmPackages:
webpack:
wanted: ^4.1.1
installed: 4.1.1
webpack-addons:
wanted: ^1.1.5
installed: 1.1.5
webpack-dev-server:
wanted: ^3.0.0
installed: 3.1.1
npmGlobalPackages:
webpack: 4.2.0
webpack-cli: 2.0.11
```
Not sure necessary - if any objections, I am open to looking into this. 
Updated ISSUE_TEMPLATE
**Summary**
Should help with issue reporting: see …
> feat: add envinfo as `webpack-cli info` command

- .cz-config.js
- CONTRIBUTING.md
New commit type `break`, for breaking changes
no
yes
**Summary**
Sometimes we would need to identify breaking changes
No
> Add break as commit type and listed the type of commit in the documentation

- lib/generators/init-generator.js
- lib/init/transformations/mode/__snapshots__/mode.test.js.snap
- lib/init/transformations/mode/mode.test.js
Bugfix
No
**Summary**
Currently, when using `init` command, we were not adding `mode` property to the generated config file.
This PR adds a `mode` property based on the answer to "Are you going to use this in production?".
The transformations for `mode` are already implemented and working.
No
> cli(init): mode support to config

- lib/generators/init-generator.js
Feature
No
No
**Summary**
The init command always asks "If you want to bundle your CSS files, what will you name the bundle? (press enter to skip)". However, the answer is not used if users answer "no" to the previous question "Are you going to use this in production?".      
This change skips the CSS bundle name question when the config is not used in production.
Also, fix #374 
No
> cli(init): use extractMiniCSSPlugin

- bin/config-yargs.js
Feature/Refactor
Not needed (?)
**Summary**
As requested in #391 , reading choices for mode directly from `webpack` options schema.
No.
> Retrieve information for CLI option from webpack schema options file

- lib/generators/init-generator.js
bugfix
no
no
**Summary**
According to [docs](https://webpack.js.org/configuration/output/#output-filename) for a single entry point, output bundle file should use a static name but on generating `config` file using `init` it uses a file named `[name].bundle.js` it should simply be called `bundle.js`.generated `config` [link](https://gist.github.com/anu-007/8c0384ff66f1efc2e25a99d701420e22#file-webpack-config-js-L18)
no
> fix: output bundle file name for single entry

- lib/commands/migrate.js
Feature/fix
Not needed.
**Summary**
As part of the update in the migrations that are happening, the message that is prompted to the user must reflect from which version to which one the migration works/happens.
Yes.
This Pr must be merged in conjunction with the other ones, related to the update on migrations.
Related issues:
#393 #395 #396 #389 #373
> Update versions on message prompted to user during migration

- lib/migrate/index.js
- lib/migrate/moduleConcatenationPlugin/__snapshots__/moduleConcatenationPlugin.test.js.snap
- lib/migrate/moduleConcatenationPlugin/__testfixtures__/.editorconfig
- lib/migrate/moduleConcatenationPlugin/__testfixtures__/moduleConcatenationPlugin-0.input.js
- lib/migrate/moduleConcatenationPlugin/__testfixtures__/moduleConcatenationPlugin-1.input.js
- lib/migrate/moduleConcatenationPlugin/__testfixtures__/moduleConcatenationPlugin-2.input.js
- lib/migrate/moduleConcatenationPlugin/moduleConcatenationPlugin.js
- lib/migrate/moduleConcatenationPlugin/moduleConcatenationPlugin.test.js
- lib/migrate/namedModulesPlugin/__snapshots__/namedModulesPlugin.test.js.snap
- lib/migrate/namedModulesPlugin/__testfixtures__/.editorconfig
- lib/migrate/namedModulesPlugin/__testfixtures__/namedModulesPlugin-0.input.js
- lib/migrate/namedModulesPlugin/__testfixtures__/namedModulesPlugin-1.input.js
- lib/migrate/namedModulesPlugin/__testfixtures__/namedModulesPlugin-2.input.js
- lib/migrate/namedModulesPlugin/namedModulesPlugin.js
- lib/migrate/namedModulesPlugin/namedModulesPlugin.test.js
- lib/migrate/noEmitOnErrorsPlugin/__snapshots__/noEmitOnErrorsPlugin.test.js.snap
- lib/migrate/noEmitOnErrorsPlugin/__testfixtures__/.editorconfig
- lib/migrate/noEmitOnErrorsPlugin/__testfixtures__/noEmitOnErrorsPlugin-0.input.js
- lib/migrate/noEmitOnErrorsPlugin/__testfixtures__/noEmitOnErrorsPlugin-1.input.js
- lib/migrate/noEmitOnErrorsPlugin/__testfixtures__/noEmitOnErrorsPlugin-2.input.js
- lib/migrate/noEmitOnErrorsPlugin/noEmitOnErrorsPlugin.js
- lib/migrate/noEmitOnErrorsPlugin/noEmitOnErrorsPlugin.test.js
- lib/utils/ast-utils.js
- package-lock.json
- package.json
- test/binCases/no-options/none/stdin.js
Feature
Yes
N/A
**Summary**
The `migrate` task didn't do anything with `webpack.NoEmitOnErrorsPlugin()`. This PR adds a transformation for this plugin that removes it and safely sets `optimizations: { noEmitOnErrors: true }`. Note that this PR has also been updated to migrate the `ModuleConcatenationPlugin` and the `NamedModulesPlugin`.
Resolves #394
Resolves #395
Resolves #396
No
> Add NoEmitOnErrorsPlugin transformation

- lib/utils/ast-utils.js
- lib/utils/validate-identifier.js
- lib/utils/validate-identifier.test.js
bugfix - adds a check for validity of an identifier
No
`generateIdentifierRegex` is based on [this](https://mathiasbynens.be/notes/javascript-identifiers-es6) article. A similar implementation can be seen in `esprima` [link](https://github.com/jquery/esprima/blob/master/tools/generate-identifier-regex.js).
**Summary**
`generateIdentifierRegex` generates a long regex for invalid keywords which is then checked in `ast-util.js`.
No
No
> fix: checks validity of an identifier

- lib/generators/utils/entry.js
Bugfix.
No, there wasn't an existing test suite for `lib/generators/utils/entry.js`.
No.
**Summary**
Fixes #397. Add same input processing code to single entry choice. There were three same code blocks, so I refactored it to a separate function. I'm not sure about adding a utility function to the top of `lib/genereators/utils/entry.js`. If it's better to move the function somewhere, please let me know!
No.
> fix(init): support non-string options for single entry

- lib/commands/migrate.js
bugfix
Not needed
**Summary**
Migration feedback was referencing a specific version of webpack. I kept that generic.
No
> fix: remove reference to specific version during migration

- lib/migrate/__snapshots__/index.test.js.snap
- lib/migrate/uglifyJsPlugin/__snapshots__/uglifyJsPlugin.test.js.snap
- lib/migrate/uglifyJsPlugin/__testfixtures__/uglifyJsPlugin-0.input.js
- lib/migrate/uglifyJsPlugin/__testfixtures__/uglifyJsPlugin-1.input.js
- lib/migrate/uglifyJsPlugin/__testfixtures__/uglifyJsPlugin-2.input.js
- lib/migrate/uglifyJsPlugin/__testfixtures__/uglifyJsPlugin-3.input.js
- lib/migrate/uglifyJsPlugin/__testfixtures__/uglifyJsPlugin-4.input.js
- lib/migrate/uglifyJsPlugin/uglifyJsPlugin.js
- lib/migrate/uglifyJsPlugin/uglifyJsPlugin.test.js
- lib/utils/__snapshots__/ast-utils.test.js.snap
- lib/utils/ast-utils.js
- lib/utils/ast-utils.test.js
- package.json
feature
**Summary**
This PR was already merged, but i went to look at the folder, and my PR was not in the commit history, nor the source code was updated, which is really strange.
#401 is the original PR. 
(different branch, same commits)
How this happened? If anyone has any idea... let me know.
> Update UglifyJS transformation

- lib/generators/init-generator.js
- lib/utils/package-manager.js
- lib/utils/package-manager.test.js
- package-lock.json
Bugfix
N/A
N/A
**Summary**
Correctly installs deps w.r.t packagers.
fixes #440 #431
> cli(init): revise installation steps

- bin/webpack.js
- test/binCases/entry/display-entrypoints/a.js
- test/binCases/entry/display-entrypoints/index.js
- test/binCases/entry/display-entrypoints/stdin.js
- test/binCases/entry/display-entrypoints/test.opts
- test/binCases/entry/display-entrypoints/webpack.config.js
Fix bug: https://github.com/webpack/webpack-cli/issues/463
Yes
No
**Summary**
Fix bug: https://github.com/webpack/webpack-cli/issues/463
NO
> fix(entry): fix a bug when `--display-entrypoints=false` does not hide entries

- package.json
Removes the `"workspaces"` key from the main package.json 
Nope, as no functionality has changed
Not relevant.
**Summary**
this monorepo uses `lerna bootstrap` with `npm` as a dependency manager, so the "workspaces" key is not used.
fixes https://github.com/webpack/webpack-cli/issues/479
No.
> fix: Remove workspaces key, as yarn workspaces is not in use

- packages/info/index.js
This PR fixes https://github.com/webpack/webpack-cli/issues/493
No
**Summary**
Currently `webpack-cli info` fails as it returns a promise which is not directly resolved.
Probably requires a Node.js version which supports async / await.
> fix: use async / await for info command

- package-lock.json
- packages/generate-loader/package-lock.json
- packages/generate-plugin/package-lock.json
- packages/generators/add-generator.js
- packages/generators/package-lock.json
- packages/generators/package.json
- packages/init/package-lock.json
- packages/migrate/package-lock.json
- packages/serve/package-lock.json
- packages/utils/package-lock.json
- packages/webpack-scaffold/index.js
> cli(prompts): Add autocomplete support for config props

- README.md
Add badge to `README.md` to display install size
No
No
**Summary**
See [this tweet](https://twitter.com/styfle/status/1006605750981021697)
No
This badge is already available on [webpack-command](https://github.com/webpack-contrib/webpack-command/blob/master/README.md) and [webpack](https://github.com/webpack/webpack/blob/master/README.md) readmes
> chore(badge): Add badge to display install size

- bin/cli.js
- test/binCases/watch/info-verbosity-off/stdin.js
- test/binCases/watch/info-verbosity-verbose/stdin.js
- test/binCases/watch/multi-config-watch-opt/stdin.js
- test/binCases/watch/multi-config/stdin.js
- test/binCases/watch/single-config-watch-opt/stdin.js
- test/binCases/watch/single-config/stdin.js
copy edit
No, but some tests may have to be fixed.
No.
**Summary**
According to [branding guideline](https://webpack.js.org/branding/#the-name):
> webpack should **always** be written in lower-case letters, even at the beginning of a sentence.
No, unless 3rd party tools depends on matching the CLI output.
N/A
> chore(branding): Uncapitalize webpack name following brand guideline

- .gitignore
- package-lock.json
- package.json
- packages/generators/package-lock.json
- packages/migrate/package-lock.json
- packages/utils/package-lock.json
- tsconfig.json
- tslint.json
Feature
**Summary**
Add initial TypeScript support for `@webpack-cli/init` package.
Use `npm run build` and `npm run watch` for dev.
#245
> feat(typescript): setup base infra

- packages/info/README.md
Documentation. Part of #247
No
yes
**Summary**
Created read me file for info sub package
No
> docs(pkg): readme info

- bin/cli.js
- package-lock.json
- packages/generators/remove-generator.js
- packages/info/index.ts
- packages/utils/__snapshots__/recursive-parser.test.js.snap
- packages/utils/__testfixtures__/fixture-3.input.js
- packages/utils/ast-utils.js
- packages/utils/modify-config-helper.js
- packages/utils/recursive-parser.js
- packages/utils/recursive-parser.test.js
Feature
No
No
**Summary**
[EDIT] Forgot to show that if there are more than one key in an object, it will keep other keys and if there are is one key in an object then it will delete the whole object.
No
Closes #500
> ast(parser): command remove

- .eslintignore
- package-lock.json
- package.json
- packages/generate-loader/package-lock.json
- packages/generate-plugin/package-lock.json
- packages/generators/package-lock.json
- packages/migrate/package-lock.json
- packages/utils/package-lock.json
- test/binCases/config-name/found-many/stdin.js
- test/binCases/config-name/found-one/stdin.js
- test/binCases/config-type/array/stdin.js
- test/binCases/configFile/plugins-precedence/stdin.js
- test/binCases/configFile/profile/stdin.js
- test/binCases/entry/cli-override/stdin.js
- test/binCases/entry/multi-file/stdin.js
- test/binCases/entry/named-entry/stdin.js
- test/binCases/entry/non-hyphenated-args/stdin.js
- test/binCases/env/complex/stdin.js
- test/binCases/errors/issue-5576/stdin.js
- test/binCases/errors/parse/index.js
- test/binCases/errors/parse/stdin.js
- test/binCases/mode/none/stdin.js
- test/binCases/output/output-argument/stdin.js
- test/binCases/stats/single-config/stdin.js
**Summary**
Fixed some linting issue but the tests are still failing due to some other issue (currently debugging)
> chore(build): fix ci

- SCAFFOLDING.md
The link provided in webpack scaffold your package section is missing. I have updated the link, Please verify and accept this PR.
As this is a documentation change, I assume no tests are required.
**Summary**
Trying to help with documentation.
No, it doesn't introduce a breaking change.
This is my first PR to open-source and i am really excited to contribute to webpack.
> Updated working link for webpack addon.

- packages/add/README.md
Documentation. Part of #247
No
yes
**Summary**
Created read me file for **add** sub package
No
> [WIP] docs(pkg): readme file for add package

- packages/add/README.md
- packages/generate-loader/README.md
- packages/generate-plugin/README.md
- packages/generators/README.md
- packages/info/README.md
- packages/init/README.md
- packages/make/README.md
- packages/migrate/README.md
- packages/remove/README.md
- packages/serve/README.md
- packages/update/README.md
- packages/utils/README.md
Enhancement
N/A
Yes
**Summary**
Adds README files to all our mono repo packages
no
=)
> docs(packages): add missing READMES to packages

- INIT.md
documentation of init feature
no
yes
no
Refers #247
> docs: init documentaion

- packages/utils/run-prettier.ts
Bugfix
No
No
**Summary**
Prettier shows warning currently that filePath and parser aren't specified.
It would throw errors in future major versions. [#4828](https://github.com/prettier/prettier/pull/4528)
This PR cleans the warning shown in the above image.
No
No
> fix(prettier): add parser, filePath

- MIGRATE.md
> docs: migrate documentaion

- CONTRIBUTING.md
Improve docs
**Summary**
As mentioned in #591 , the setup guidance is not clear enough for newcomers who setup the directory for the first time. The bootstrap command is necessary.
No
> docs: fix the setup workflow #591

- packages/generators/add-generator.ts
- packages/generators/remove-generator.ts
- packages/make/index.ts
- packages/migrate/index.ts
- packages/migrate/removeDeprecatedPlugins/removeDeprecatedPlugins.ts
- packages/serve/index.ts
- packages/utils/recursive-parser.ts
- packages/utils/resolve-packages.ts
- tslint.json
linting changes
NA
NA
**Summary**
we can switch off console.log warnings and removed that line length issue 
NA
NIL
> fix tslint warnings

- bin/config-yargs.js
avoid accessing definitions directly
bugfix
existing test should be fine
not relevant
**Summary**
refactor the way of accessing webpack's schema to not create a internal dependency on the exact structure of the schema.
No
see also https://github.com/webpack/webpack/pull/7232
> fix: resolve references in schema

- package.json
- packages/utils/package.json
Dependencies pin
No
No
**Summary**
We need to start pinning dependencies that need minimum Node 8 version so that greenkeeper stops updating them.
No
Closes #661, #662, #664
> chore(dependencies): pin versions to support node 6

- packages/utils/npm-packages-exists.ts
Refactoring `npmPackagesExists()` function
No, there is no API change
No
**Summary**
This makes the code more readable and avoids checking the boolean twice
No 
> Refactor npmPackagesExists() function

- bin/cli.js
Fix `--color` option to use [supports-color](https://github.com/chalk/supports-color) properly.
No.
N/A
**Summary**
The `--color` option’s default is set to return
```js
return require("supports-color").supportsColor
```
Added in supports-color 5.0.0 (chalk/supports-color#64), `supportsColor` is a function and not the test result. Because a function is truthy, colours are enabled irrespective of TTY and `FORCE_COLOR` settings.
```js
return require("supports-color").stdout
```
is the correct way to use supports-color. It [checks](https://github.com/chalk/supports-color/blob/ed0fe39d600ff1c286b3948abbef88eaef4f8f27/index.js#L50) `process.env.isTTY` so …
> cli(color): fix color option

- bin/cli.js
Add `--no-color` option to yargs so it shows in help.
No.
See webpack/webpack.js.org#2626.
**Summary**
[supports-color](https://github.com/chalk/supports-color) obeys both `--color` and `--no-color` options, but only `--color` is documented in help.
`--no-color` is a very useful feature and there’s no way to discover it without reading source code now.
No.
> cli(color): document --no-color option

- README.md
Simple documentation fixes.
NA
...yes :)
**Summary**
Fixes typos and changes wording for better readability – particularly the last sentence which I couldn't understand.
> [Docs]: Fix typos and improve intro wording

- packages/add/README.md
- packages/generate-loader/README.md
- packages/generate-plugin/README.md
- packages/info/README.md
- packages/init/README.md
- packages/migrate/README.md
- packages/remove/README.md
- packages/serve/README.md
- packages/update/README.md
README docs
**Did you add tests for your changes?** NA
**If relevant, did you update the documentation?** NA
**Summary**
I found out while playing around with the examples given in the doc.
We transpile the `ts` files using babel which converts 
`export default [func/variables]` 
to 
``` bash
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = default_1
```
**Does this PR introduce a breaking change?** No
> docs: correct use of individual package in node env

- test/test-utils.test.js
- test/testUtils.js
This PR adds support for extracting hash after running test. [Jest](https://github.com/facebook/jest/blob/master/e2e/__tests__/test_name_pattern_skipped.test.js#L19) is already doing it. We are trying to mimic it here, for our needs.
**Did you add tests for your changes?** Yes
**If relevant, did you update the documentation?** NA
**Summary**
This PR tries to address the feature-request issue #672 
Closes #672 
**Does this PR introduce a breaking change?** No
> feat(tests): add extractHash support in test-infra

- .travis.yml
Build related change
N/A
N/A
**Summary**
Since `lerna bootstrap` takes more than 10 minutes to complete especially on Node 6, the Travis build fails since no output is received for 10 minutes.
> `travis_wait` spawns a process and then writes a short line to the build log every minute for 20 minutes, extending the amount of time your command has to finish.
No
Closes ∞ issues
> chore(ci): increase travis wait timer

- packages/utils/modify-config-helper.ts
This is more of a **feasibility** kind of change for the benefit of Issue Raiser. Please feel free to close this PR if it adds a noise.
Currently, when we face any issue while running transformation we throw an error giving an URL
https://github.com/webpack/webpack-cli/issues
However, the bug reporter has to do one more hop to create an issue.
This PR changes that URL to  https://github.com/webpack/webpack-cli/issues/new?template=Bug_report.md
**Did you add tests for your changes?**  NA
**If relevant, did you update the documentation?** NA
**Does this PR introduce a breaking change?** NO
> misc: reduce hop for creating an issue

- packages/generators/init-generator.ts
As mentioned in #708 , we don't need to scaffold the "dist" property in output path if the entry is single and output path is not chosen by the user.
misc
N/A
**Summary**
No
> misc: not scaffold 'dist' if the user chooses default

- SCAFFOLDING.md
You can reconnect configurations with merge, which according to the current documentation in SCAFFOLDING.md is not given.
After several attempts and my question on stackoverflow, i found the problem show in link under comment.
[webpack-scaffold-webpackoptions-merge-not-work-why](https://stackoverflow.com/questions/54350271/webpack-scaffold-webpackoptions-merge-not-work-why)
Yes I am currently creating a complex scaffold with webpack and will upload it to github as soon as I get there ready.
Yes, I have updated the documentation, so this is about the documentation. Webpack-CLI works powerfully, thanks for that.
**Summary**
The change improves a wrong …
> docs(scaffolding): Correction of the webpack-merge configuration

- commitlint.config.js
- packages/migrate/bannerPlugin/__tests__/bannerPlugin.test.ts
- packages/migrate/commonsChunkPlugin/__tests__/commonsChunkPlugin.test.ts
- packages/migrate/extractTextPlugin/__tests__/extractTextPlugin.test.ts
- packages/migrate/index.ts
- packages/migrate/loaderOptionsPlugin/__tests__/loaderOptionsPlugin.test.ts
- packages/migrate/loaders/__tests__/loaders.test.ts
- packages/migrate/migrate.ts
- packages/migrate/moduleConcatenationPlugin/__tests__/moduleConcatenationPlugin.test.ts
- packages/migrate/namedModulesPlugin/__tests__/namedModulesPlugin.test.ts
- packages/migrate/noEmitOnErrorsPlugin/__tests__/noEmitOnErrorsPlugin.test.ts
- packages/migrate/outputPath/__tests__/outputPath.test.ts
- packages/migrate/removeDeprecatedPlugins/__tests__/removeDeprecatedPlugins.test.ts
- packages/migrate/removeJsonLoader/__tests__/removeJsonLoader.test.ts
- packages/migrate/resolve/__tests__/__snapshots__/resolve.test.ts.snap
- packages/migrate/resolve/__tests__/__testfixtures__/resolve.input.js
- packages/migrate/resolve/__tests__/resolve.test.ts
- packages/migrate/uglifyJsPlugin/__tests__/uglifyJsPlugin.test.ts
- packages/utils/__tests__/ast-utils.test.ts
Includes changes requested in #613 
**Summary**
Before committing I had to solve those issues:
- Removed [deprecated](https://conventional-changelog.github.io/commitlint/#/reference-rules?id=lang-deprecated) `lang: [0, "always", "eng"]` from commitlint configuration. It gave me errors preventing me from committing:
>RangeError: Found invalid rule names: lang. Supported rule names are: body-case, body-empty
- Fixed a tslint error:
```
ERROR: packages/migrate/index.ts:20:4 - Type literal has only a call signature — use 
`new(errors: string[]) => {
message: string;
},` instead.
```
Those are the actual changes:
1. Adds an interface to `transformations` in `packages/migrate/migrate.ts`
2. Refactor every test in `migrate/**/__tests__/**.test.ts` …
> tests(migration): including requested changes

- README.md
Add downloads badge from npm which shows downloads per week
[![npm](https://img.shields.io/npm/dw/webpack-cli.svg)](https://www.npmjs.com/package/webpack-cli)
ISSUES CLOSED: #778
docs/feat
Yes
Yes
**Summary**
* Just added a simple npm downloads badge in readme which shows weekly downloads, can do it total, by year or month too as per feedback.
* Also placed the heading below the webpack image in readme which imo looks better, please suggest if this should be reverted. 😄 
No
No
> docs(readme): add downloads badge

- .github/CONTRIBUTING.md
Add commands to install jest globally for running individual tests
ISSUES CLOSED: #775
Docs
NA
Yes
**Summary**
Added commands to install jest cli for running tests.
No
NA
> docs(contributing): commands to install jest globally

- packages/generators/init-generator.ts
Fixes #707 
Ya
N/A
**Summary**
Changes default name of config in scaffolding
N/a
> feat: use webpack.config as default name in dev scaffold

- bin/cli.js
ISSUES CLOSED: #762
Bugfix
Will be done by @dhruvdutt in #758 
N/A
**Summary**
`compiler.close` was not calling the compiler callback correctly and therefore stats were null. In addition compiler will never close in watch mode. Removed. 
> fix(bin): use compiler.close API correctly for stats

- CONTRIBUTING.md
Adds few lines to `CONTRIBUTING.md` about the undocumented `boostrap` npm script that should be run to set up the project
> docs(contributing): adds prebuild instructions

- .github/CONTRIBUTING.md
Improves formatting of the Setup instructions in CONTRIBUTING.md
**Before:**
**After:**
> docs(contributing): improve formatting

- INIT.md
- bin/prompt-command.js
bugfix
N/A
N/A
**Summary**
#741
No
> fix(init): fix init prompt installation

- README.md
docs/readme change
Not required
**Summary**
webpack-cli is using [lerna](https://lernajs.io/) that's why I think we should add lerna badge.
No
> docs: add lerna badge in README

- SCAFFOLDING.md
I've updated the SCAFFOLDING documentation to be more clean and structured.
[Here](https://github.com/misterdev/webpack-cli/blob/misterdev-format-scaffold/SCAFFOLDING.md) you can find it  visualized by github.
> docs(scaffolding): improved structure, formatting, typos

- INIT.md
- packages/generators/add-generator.ts
- packages/generators/init-generator.ts
- packages/generators/types/yeoman-generator.d.ts
- packages/generators/utils/entry.ts
- packages/webpack-scaffold/README.md
- packages/webpack-scaffold/__tests__/__snapshots__/index.test.ts.snap
- packages/webpack-scaffold/__tests__/index.test.ts
- packages/webpack-scaffold/index.ts
Slight improvement to the `webpack-cli init` user experience:
- improved defaults (see #788)
- improved messages
Yes
Yes, also improving formatting and descriptions
**Summary**
#788
> enh(webpack-scaffold): improve prompt and doc

- packages/generators/add-generator.ts
- packages/utils/scaffold.ts
BugFix For #795
No
No
**Summary**
#795
No
> fix(add): add handling for topScope

- packages/utils/find-root.ts
- packages/utils/package-lock.json
- packages/utils/package.json
- packages/utils/scaffold.ts
config file is generated at the project root
bugfix
yes
NA
**Summary**
Determine project root and create the file there.
No
Ref - #709
> fix(scaffold): config file is always generated at the project root

- .github/CONTRIBUTING.md
- package.json
- test/binCases/stats/single-config/single-config.test.js
- test/binCases/watch/info-verbosity-off/info-verbosity-off.test.js
- test/binCases/watch/info-verbosity-verbose/info-verbosity-verbose.test.js
- test/binCases/watch/multi-config-watch-opt/multi-config-watch-opt.test.js
- test/binCases/watch/multi-config/multi-config.test.js
- test/binCases/watch/single-config-watch-opt/single-config-watch-opt.test.js
- test/binCases/watch/single-config/single-config.test.js
ISSUES CLOSED: #808
Updated test regex to run all tests, added some helper scripts for running tests
Yes
Yes
**Summary**
* Updated tests regex to run all tests
* Added helper scripts to run cli and package tests separately
No
> chore(tests): updated test regex, some helper scripts

- packages/init/init.ts
Previously there was multiple `stdout.write` due to the presence of conditional statements. In this PR I have scrapped those repeating lines into a single `process.stdout.write`
Refactoring
No
Can't say
Probably not
> fix(init): refactored the init.ts success message

- bin/utils/prompt-command.js
- packages/serve/README.md
- packages/serve/index.ts
ISSUES CLOSED: #572
This PR introduces a bugfix for the serve package to export a default function, and a more useful error message when a package does not export a default function.
No, I could not seem to find any tests relating to the packages, eg. serve, init. If you would like me to write tests I can, I might just need some guidance.
No
**Summary**
I ran into this issue: https://github.com/webpack/webpack-cli/pull/589 while trying `webpack-cli serve`. The reason for the issue is that `serve` does not export a default function. There was a PR earlier about this that never got finished https://github.com/webpack/webpack-cli/pull/589. `serve` still …
> fix(bin, serve): force default package export, add serve default

- README.md
Adds a new shield to represent the count of contributors
[![GitHub contributors](https://img.shields.io/github/contributors/webpack/webpack-cli.svg)](https://github.com/webpack/webpack-cli/graphs/contributors)
docs
> docs(README): adds contributors shield

- packages/add/README.md
- packages/generate-loader/README.md
- packages/generate-plugin/README.md
- packages/generators/README.md
- packages/info/README.md
- packages/init/README.md
- packages/migrate/README.md
- packages/remove/README.md
- packages/serve/README.md
- packages/update/README.md
- packages/utils/README.md
- packages/webpack-scaffold/README.md
- Adds the image shield for total number downloads in the readme file of all packages.
- Updates `webpack-scaffold` API table.
Documentation
To know whether the package is popular or not, in order to plan for future upgrades.
> docs(packages): adds downloads/month img shield

- .github/CONTRIBUTING.md
Link to the migration docs was invalid, hence fixed
docs
> docs(contributing): fixes dead  link

- bin/config/optionsSchema.json
- packages/serve/README.md
update docs to use webpack-dev-server
ISSUES CLOSED: #846
docs
NA
yes
**Summary**
* Update serve package docs to use webpack-dev-server, webpack-serve is deprecated.
no
NA
> docs(serve): update docs to use webpack-dev-server

- README.md
fix typos, add summary of all commands in commands section
docs
NA
Yes
**Summary**
* fix some typos/grammars
* Add a quick summary of all commands in readme.
No
NA
> docs(readme): fix typos, add summary of all commands

- package-lock.json
- packages/generators/addon-generator.ts
refactor
yes
NA
**Summary**
* Move async gen to async await.
No
Not yet
> chore: addon generator to async/await

- .github/CONTRIBUTING.md
Docs
**Motivation**
- It was getting harder to reach the desired section in the doc.
- CI failing while modifying dependency (not committing the `package-lock.json`)
Hence everything sorted  :tada:
> docs(contribute): adds table of contents and info about dependencies.

- .travis.yml
Removes node:stable from Travis to fix the currently broken CI as discussed in #864 
**Summary**
Closes #864
> chore(travis): temporary remove node stable

- .github/CONTRIBUTING.md
- README.md
- packages/README.md
- packages/generate-loader/README.md
- packages/generate-plugin/README.md
- packages/generators/README.md
- packages/info/README.md
- packages/init/README.md
- packages/migrate/README.md
- packages/remove/README.md
- packages/serve/README.md
- packages/update/README.md
- packages/utils/README.md
Fixed indentation and corrected spellings
> chore(docs): minor fixes in the docs

- README.md
- bin/opencollective.js
Allows disabling the open collective prompt.
Following [opencollective-postinstall](https://github.com/opencollective/opencollective-postinstall/blob/master/index.js#L7), our prompt is disabled if `DISABLE_OPENCOLLECTIVE` or `CI` env variables are set to `true`
Yes
**Summary**
Closes #854 
This is an alternative PR to #856
> feat(opencollective prompt): add disable option

- bin/cli.js
bugfix
nope! I didn't see any existing tests for `processOptions`.
I did not, but this should make the current [docs on the watch options](https://webpack.js.org/api/cli/#watch-options) true for Webpack configs that are arrays.
**Summary**
webpack/webpack#4594 points out that watch options aren't being honored when the
Webpack config is an Array. In cases when it's an array, there may not
be a firstOptions.watchOptions, but there will be an options.watchOptions.
In the current implementation, when the Webpack compiler watch method is
called with watchOptions and the Webpack config is an array, watchOptions
will be `true` and not an object.
**I should …
> cli: fix watch options for array config

- SECURITY.md
> [sec]: Initial security policy

- packages/generators/__tests__/add-generator.test.ts
- packages/generators/add-generator.ts
- packages/generators/utils/plugins.ts
- tsconfig.base.json
refactoring/bugfix
Yes
NA
**Summary**
Changed the naming of the current naming of the webpack plugin in the `add-generator` to a better and standard way of naming. The earlier one was creating error name when passed something like `extract-text-webpack-plugin`, it would give the plugin in config file like this
**Bug**
```bash
plugins: new Extract() - textPlugin,
```
**With this refractor**
It will output the config file plugin with this
```bash
plugins: new ExtractTextWebpackPlugin(),
```
No
NA
> chore(add-generator): changed the naming of the plugin in config file

- bin/utils/convert-argv.js
bugfix
Nope
Nope
**Summary**
Made the `--config-register` flag resolve relative to the root path..
Fixes #746 
> fix(cli): made --config-register resolve relative to root path 

- packages/generators/init-generator.ts
- packages/generators/remove-generator.ts
- packages/migrate/commonsChunkPlugin/commonsChunkPlugin.ts
fix lint warnings
refactor to fix lint warnings
Yes
NA
**Summary**
fixed the lint warnings
No
> chore(lint): fix lint warnings

- bin/cli.js
improvement checking permission on open collective prompt EPERM error.
**Summary**
This error is related on https://github.com/webpack/webpack-cli/issues/870 and fixed https://github.com/webpack/webpack-cli/pull/876 but It looks not enough.
For example, It is happen EPERM when node_modules is owned by `root` and webpack-cli is executed by user excepted `root`.
It should check file and process owners are same because updating utime requires it.
> fix: improve checking file permission

- bin/utils/prompt-command.js
- packages/generators/init-generator.ts
- packages/generators/templates/package.json.js
- packages/generators/templates/template.html
- packages/generators/utils/webpackConfig.ts
- packages/utils/scaffold.ts
Better default settings for init generator
N/A
N/A
**Summary**
Sets better defaults if user is in production and if the user is using defaults.
N/A
After this is done, we can use the default config generated from `webpack init --auto` and use that as the default config for a webpack instance. After doing so, we can remove the `isUsingDefaults` logic from the generator (or most of it) and put it as a non-config requirement in the core cli.
- Prefetching
- other things that might come up
- More aggressive chunksplitting strategies on specialized builds
> feat: better defaults (0CJS) with config generation

- bin/cli.js
bugfix #944 
No
No
**Summary**
Update message reporting with more accurate details
No
> fix: module not found error

- README.md
chore(docs)
Yes
**Summary**
@evenstensberg  as the packages (`add`,`remove`,`update`) has been removes, so can you point the location for the underlying functions.
> chore(docs): fixes 404 URLs and unformatted table

- packages/generators/init-generator.ts
bugfix/refactoring
NA
NA
**Summary**
Added `await` in order to resolve the pending promise which was resulting in prompting error for 3rd question in init command
NA
NA
> chore: added await in order to resolve the pending promise

- .gitignore
- tsconfig.base.json
Enables the source maps for the ts compiled files for easy debugging.
https://code.visualstudio.com/docs/typescript/typescript-debugging#_javascript-source-map-support
feature
**Summary**
Setting breakpoints in the TS won't work as JS files are being used, with the help of source maps which has one to one mapping for each statement allows the editor to resolve the respective line in the JS file. 
While debugging ts files.
> chore(ts): enables source map in the ts

- package-lock.json
- package.json
bugfix
N/A
N/A
**Summary**
`prettier` is used during development of `webpack-cli` and does not need to be pulled in by all packages that use `webpack-cli`; thus it should be in `devDependencies`, not `dependencies`. (Bug introduced by #851.)
No.
> fix(deps): move prettier from dependencies to devDependencies

- packages/serve/index.ts
refactoring
Nope
N/A
**Summary**
Refactored the serve action handler to a more concise form.
Nope
N/A
> chore(serve): refactor code to be more concise

- lib/groups/config.js
bugfix
no
~**If relevant, did you update the documentation?**~
**Summary**
Fixes [#746](https://github.com/webpack/webpack-cli/issues/746#issuecomment-504755804) by first checking, if the dependency is a local file or a package. `module.paths` doesn't work for requiring local paths.
I couldn't think of any.
> fix: improve local configRegister file resolution

- lib/groups/output.js
bugfix
NA
NA
**Summary**
There was no `ArgsValidator` declared, and as far as the `resolveFileDirectory` is concerned, if it's being inherited from the `groupHelper` class then it should be  `resolveFilePath` , as there is no `resolveFileDirectory` declared as well 
No
N/A
> [NEXT] BugFix: changed the path resolver call

- lib/utils/compiler.js
- package-lock.json
- package.json
This PR replaces project dependency: `cli-table` with `cli-table3`
**Summary**
`cli-table` is a great package. However, it's not actively maintained (last commit was almost a year ago). `cli-table3` is a drop-in replacement, which is actively maintained and has some additional features, including:
* Ability to make cells span columns and/or rows.
* Ability to set custom styles per cell (border characters/colors, padding, etc).
* Vertical alignment (top, bottom, center).
* Automatic word wrapping.
* More robust truncation of cell text that contains ansi color characters.
* Better handling of text color that spans multiple lines.
* Exhaustive test suite including the entire original cli-table test suite.
**Does this PR introduce a breaking …
> cli: replace cli-table with cli-table3

- packages/utils/modify-config-helper.ts
fixes entry point issues in the newly generated webpack config
Closes #976
Bugfix
Nopes
Nopes
**Summary**
While generating new config I am surprised that the generated webpack.config.js doesn't have an entry point.
> fix(init): fixes config resolution on generating new configuration

- bin/utils/convert-argv.js
- package-lock.json
- package.json
Closes https://github.com/webpack/webpack-cli/issues/1023
Yes
N/A
**Summary**
Dupes out of resolving options if there are none to throw an error
No
N/A
> fix: resolve opts when no-config & fix vulns

- lib/groups/config.js
Feature.
Nope 😢 Tested it locally? Not sure how to add tests or what tests one would like to see.
Not necessary hopefully, since I imagine people want ES modules as config files to just work™.
**Summary**
This changes adds a `require` wrapper to the `config` group that allows it to detect and return the default export of ES modules. This is useful when your configuration is a TS(X) file or something that is being transpiled by babel.
Nope!
If one could possibly publish `webpack-cli@4.0.0-alpha-6` with these changes that would be 👌
> Support `export default` from configuration files.

- lib/groups/config.js
- lib/utils/group-helper.js
- test/utils/test-utils.js
refactoring
Nope
N/A
**Summary**
refactored existing code-base to use `includes()` method (check for existence of an item).
Nope
N/A
> chore: refactor

- lib/commands/external.js
colorize important things on the cli
Colorized command that will run and the package name that will be installed.
No
No
**Summary**
* Color the command that will run to install the packages, and the package name.
No
lmk if other colors are more preferred!
> chore(cli): colorize commands to run and package to be installed

- test/entry/entry-single-arg.test.js
- test/utils/test-utils.js
refactoring/bugfix
NA
NA
**Summary**
the current matching method, the test is failing in windows as the `Output Director` is as follows
```
\\Path-to\\webpack-cli\\test\\entry\\bin
``` 
and this is been matched with `entry/bin` which is failing .
So if we refactored the current to just check with the last two directory, we can make it to pass
No
Also disabled the `@typescript-eslint/explicit-function-return-type` for `test-utils` file as its causing to failed while committing.
> chore: changed the outDir to entry test

- .gitignore
- build/changelog-generator/index.js
- lib/bootstrap.js
- lib/utils/dev-config.js
- lib/webpack-cli.js
- packages/webpack-scaffold/index.ts
- test/config/basic/basic-config.test.js
- test/entry/defaults-empty/entry-single-arg.test.js
- test/entry/defaults-index/entry-multi-args.test.js
- test/utils/test-utils.js
Adds tests for entries, test if `./src/index.js` is present and set that default if it exists.
Yes bby
N/A
**Summary**
Adds tests, improves code
N/A
Keep in mind 1 of the cases fails, because we cannot override mixed arguments yet, I'll try to get that to work. For instance:
`webpack-cli --entry index.js entry index2.js` will fail because we have duplicate keys. Same goes for the opposite scenario or if we have `webpack-cli --entry index.js --entry index2.js`
in case of using `--` twice, we can convert those two into an array, which will be the best case, but for mixed arguments I …
> tests: add tests for entry defaults, try to set better defaults

- packages/migrate/index.ts
Fixes #1064 
no :(
This requires testing the CLI itself (as the issue is in index.ts), and currently there are no such tests. I saw there are other CLI tests (for other commands), but none of them test a command which expects user input.
I found the [inquirer-test](https://github.com/ewnd9/inquirer-test) package which might be helpful, so let me know how you think I should proceed here.
**Summary**
jscodeshift doesn't expose a default import, changed it to import the exported function correctly.
no
> Fix jscodeshift import (fixes #1064)

- packages/serve/index.ts
- packages/serve/startDevServer.ts
refactoring
No
No
**Summary**
I don't think there is a need for the `serve` package to return a Promise. Users should not be using the package for its API, and it is not logical exactly when the Promise should resolve.
As mentioned by @evilebottnawi here: https://github.com/webpack/webpack-cli/pull/1011#discussion_r329023815, there is no need to have an additional `onListening`.
Yes
> chore(serve): remove promise return from serve package

- bin/config/config-yargs.js
- bin/utils/convert-argv.js
- package-lock.json
Fixes https://github.com/webpack/webpack-cli/issues/1095
N/A
No, this needs to be done
**Summary**
Adds `no-cache` flag, (we do not check version here for setting the property)
No
- Might need to add validation against webpack version?
- Monorepo test are failing, might worth removing the entire mono repo at master branch? (Is that good for versioning against next? I think it's bad)
> feat: add new no-cache flag and patch sec dep

- lib/utils/cli-flags.js
- Refactor
- Not relevant
- Not relevant
**Summary**
The multiple property of the `optionDefinitions` object is set to true when the option expects multiple values to be passed via the command line. By default this property is `false`. There is no need to specify this explicitly. All the following `optionDefinitions` which do not expect multiple values don't specify it only this one does.
[Reference](https://github.com/75lb/command-line-args/blob/master/doc/option-definition.md#optionmultiple--boolean) to `command-line-args` docs.
Nope
> chore: Remove redundant multiple property of OptionDefinition cli-flags.js 

- lib/bootstrap.js
- lib/commands/external.js
- lib/groups/advanced.js
- lib/groups/basic.js
- lib/groups/config.js
- lib/groups/help.js
- lib/groups/output.js
- lib/groups/stats.js
- lib/utils/compiler.js
- lib/utils/development-config.js
- lib/utils/group-helper.js
- lib/utils/process-log.js
- lib/utils/production-config.js
- lib/utils/zero-config.js
- lib/webpack-cli.js
- test/serve/serve-basic.test.js
Fix
NA
NA
**Summary**
Ignore  warnings for .js files. Handling : https://github.com/webpack/webpack-cli/issues/940
No
After suppressing :
> fix: warnings on lint

- lib/groups/advanced.js
- lib/groups/config.js
- lib/groups/output.js
- lib/utils/cli-flags.js
- lib/utils/group-helper.js
- lib/webpack-cli.js
- package.json
- test/config-lookup/dotfolder-single/dotfolder-single.test.js
- test/config/type/promise/promise-config.test.js
- test/config/type/promise/webpack.config.js
- test/entry/defaults-index/entry-multi-args.test.js
- test/env/object/object-env.test.js
- test/global/global.test.js
- test/json/json.test.js
- test/merge/config/merge-config.test.js
- test/merge/defaults/merge-defaults.test.js
- test/output/defaults/output-defaults.test.js
- changed from `bundle.js` to `main.js`
- applied merging strategy in the correct moment
- fixed some tests
Bugfix of current tests
Yes
Nope, not needed for now
**Summary**
Fixed current tests. They are all passing now. I had to turn off the promise one. It requires some more work.
Nope
> fix:  various tests are now working

- lib/utils/cli-flags.js
- lib/utils/compiler.js
- package-lock.json
- package.json
- test/json/json.test.js
- test/target/node/main.js
- test/target/node/new.js
- test/target/node/node-test.test.js
- test/target/node/webpack.config.js
chores: removed colour from table head (red is not good) and emitted a more precise value of the bundle size
Closes #1169 
Yes
Not needed
**Summary**
I removed the target. Webpack already has a default which is `target: "web"` so the cli doesn't need to have it too.
Nope 
Added some chores around the emitted output
> fix: remove for now the default value of the target

- lib/webpack-cli.js
- packages/serve/index.ts
- packages/serve/package-lock.json
- test/serve/serve-basic.test.js
fix
Yes
**Summary**
I changed the `args` parameter to `...args`, because I realized I overlooked this earlier. The problem is that spread syntax is used to pass the CLI args to the function, so I was only passing the first of these strings along to the argument parser. I added a test that involves more CLI flags to check this is fixed.
I'm not sure why `serve` tests and command were temporarily removed, was there a particular reason?
Also, I don't think adding this line was needed:
```
process.argv = process.argv.filter(arg => arg !== 'serve');
```
No
> fix(serve): handle serve args as an array

- cli.js
- lib/bootstrap.js
- lib/commands/external.js
- lib/groups/advanced.js
- lib/utils/compiler.js
- lib/utils/logger.js
- lib/utils/process-log.js
Chores
No, not needed
No 
**Summary**
I moved the creation of the logger inside a different file and imported it everywhere we log something
I don't think it's a good practice to pollute the process object. 
Nope 
> chore: better logger

- packages/generators/templates/package.json.js
fix
No
N/A
**Summary**
Begins to fix: https://github.com/webpack/webpack-cli/issues/901
As explained here: https://github.com/forcedotcom/salesforcedx-vscode/issues/253, it seems that having a `name` field in the `package.json` when you run `webpack-cli create` prevents an error from being thrown. Thus, we can allow for `webpack-cli create` being run repeatedly by adding a `name` property to the generated `package.json`.
However, we should still either provide a more specific error or prompt the user to delete the `package.json` if the `name` parameter is missing, so this does not entirely close the previously mentioned issue. I will work on this other …
> fix(init): fixed package template to include name param

- packages/utils/.eslintrc
- packages/utils/modify-config-helper.ts
refactoring
Not yet
N/A
**Summary**
The way that yeoman generator works is that it reads from the user's `package.json` to get the "name" property of this file. When it writes data to `.yo-rc.json`, it sets that data such that the key is that "name" property. Therefore, I have changed the reading of the yeoman configuration data such that we grab the desired configuration from that "name" key.
N/A
> init generator: read name property from package.json

- lib/groups/StatsGroup.js
- lib/utils/Compiler.js
- lib/utils/CompilerOutput.js
- lib/utils/cli-flags.js
- test/help/__snapshots__/help-single-arg.test.js.snap
- test/standard/src/index.js
- test/standard/standard.test.js
feature.
It adds another flag `standard` which produce standard result
Yes.
No.
**Summary**
`--standard` outputs result of `stats.toString()`
N/A
No
> feat: adds standard output flag

- lib/bootstrap.js
- package.json
- packages/generators/package-lock.json
Fixes #1046 
intercept flag parsing and if any invalid flag is present, print a neat err.
Will add
NA
**Summary**
* Output pretty message when invalid flag is supplied.
No
> [cli]: show help when invalid flag is supplied

- lib/groups/AdvancedGroup.js
- lib/groups/BasicGroup.js
- lib/utils/Compiler.js
- lib/utils/interactive.js
- lib/utils/zero-config.js
Refactoring
No
No
**Summary**
- Object destructing to prevent deep level object refs (quite confusing and tedious to write)
- repeated else if to switch
No
> chore(lib): refactored lib utils and groups

- lib/groups/ZeroConfigGroup.js
- lib/utils/development-config.js
- lib/utils/production-config.js
- lib/utils/zero-config.js
- lib/webpack-cli.js
- packages/generators/__tests__/add-generator.test.js
- test/ZeroConfigGroup.test.js
- test/env/prod/index.js
- test/env/prod/prod.test.js
- test/env/prod/webpack.config.js
- test/output/named-bundles/output-named-bundles.test.js
Fixes #1215 
YEs
Nope
**Summary**
Making sure that the ZeroConfigGroup class is able to import the correct files.
> fix(cli): fix file resolution inside group helper

- INIT.md
- README.md
- lib/webpack-cli.js
- packages/README.md
fix invalid package name
ISSUES CLOSED: #1227
fix invalid package name when using init package.
Yes
**If relevant, did you update the documentation?** 
Updated.
**Summary**
No
> fix(init): fix the invalid package name

- packages/generators/__tests__/init-generator.test.ts
enable init generator test
enable init gen test.
Yay
NA
**Summary**
Enables init generator test with more timeout so travis has enough time to execute the test.
No
> tests(generator): enable init generator test

- packages/webpack-cli/lib/utils/Compiler.js
feature
No
No
**Summary**
Add a real progress bar for`--progress` flag.
Yes
> feat: add progress bar for progress flag

- README.md
> fix: correct supported arguments & commands link in README

- test/output/defaults/index.js
- test/output/defaults/output-defaults.test.js
Added a test case for --defaults flag
Yes
NA
**Summary**
* Added a case when --defaults flag is used to indicate compiler to use webpack defaults.
No
> tests(output): add test case for defaults flag

- .babelrc
- .gitignore
- package.json
- packages/webpack-cli/README.md
- packages/webpack-cli/__tests__/ZeroConfigGroup.test.js
- packages/webpack-cli/lib/groups/ZeroConfigGroup.js
- packages/webpack-cli/lib/utils/cli-flags.js
- test/help/__snapshots__/help-single-arg.test.js.snap
- test/mode/dev/dev.test.js
- test/mode/dev/src/index.js
- test/mode/prod/prod.test.js
- test/mode/prod/src/index.js
- yarn.lock
Feature, it adds back `mode` argument
Yes
Yes 
**Summary**
People asked to have back the `mode` argument.
No
> feat(webpack-cli): added mode argument

- SECURITY.md
- packages/webpack-scaffold/README.md
Bug Fix, fixes the issue #1245 
Yes, Security.md and webpack-scaffold/readme.md
**Summary**
Fixing the typos and grammatical errors in Readme files
No
> Fixing the typos and grammatical errors in Readme files

- .github/workflows/nodejs.yml
- package.json
- test/config/empty/empty-config.test.js
- test/entry/defaults-empty/entry-single-arg.test.js
- test/json/json.test.js
It adds webpack 4 to the CI plus some fix inside tests
Yes
Not needed 
**Summary**
`webpack-cli` v4 should still support the current webpack version. So we set up the CI in order to run `latest` and `next`
No
> chore: added webpack 4 to the matrix and changed tests

- packages/webpack-cli/bin/cli.js
- packages/webpack-cli/lib/bootstrap.js
- packages/webpack-cli/lib/runner.js
- packages/webpack-cli/lib/utils/cli-executer.js
feature
No
No
**Summary**
I am creating a CLI executer that will be used in case of invalid/unknown args.
Currently it looks like this
After this is merged, I would add this in appropriate places
No
Improving intractability with cli
> feat: create a cli executer

- .github/CONTRIBUTING.md
Made some enhancements in `CONTRIBUTING.md` .
NA
Yes
**Summary**
No
> docs: enhance CONTRIBUTING.md

- .github/CONTRIBUTING.md
angular commit guidelines have been moved to `DEVELOPERS.md`
minor docs change
N/A
N/A
**Summary**
Add the correct links for pointing to angular commit guidelines
Nope
> docs: fix links to angular commit guidelines

- package.json
- yarn.lock
Fix errors while running `$ yarn commit`. [reference](https://github.com/webpack/webpack-cli/blob/next/.github/CONTRIBUTING.md#commit-message)
BREAKING CHANGE: 🧨 No
bugfix
N/A
N/A
**Summary**
`$ yarn commit` won't work as `$ npm run commit` would (for `npx` like execution).
Instead having git-cz as a dev dependency fixes the error.
Nope.
> fix: 🐛 add git-cz as a dev dependency

- packages/webpack-cli/lib/utils/cli-executer.js
bugfix
Nope
N/A
**Summary**
closes #1268
**Does this PR introduce a breaking change?**\
Nope
N/A
> fix: handle promise rejection happening with cli-executor

- packages/webpack-cli/lib/utils/cli-flags.js
- test/mode/prod/prod.test.js
- test/mode/prod/src/index.js
Fixes #1282  
Yes.
Yes
**Summary**
Added validation for `mode` argument , now can only accept `development , production or none`
will promt a warning if set to any other value.
NO.
> feat(webpack-cli): add mode argument validation

- packages/package-utils/__tests__/index.test.ts
- packages/webpack-cli/lib/commands/ExternalCommand.js
bugfix
Nope
N/A
**Summary**
closes #1283 
Nope
N/A
> fix(webpack-cli): handle promise rejection with package installation

- packages/webpack-cli/lib/groups/ZeroConfigGroup.js
- packages/webpack-cli/lib/utils/none-config.js
Fixes #1302 
corresponding test ->  #1301 
**Summary**
NO
> fix: add configuration for mode option none

- .travis.yml
- packages/webpack-cli/README.md
- packages/webpack-cli/__tests__/StatsGroup.test.js
- packages/webpack-cli/lib/groups/StatsGroup.js
- packages/webpack-cli/lib/utils/Compiler.js
- packages/webpack-cli/lib/utils/CompilerOutput.js
- packages/webpack-cli/lib/utils/cli-flags.js
- test/.eslintrc
- test/config-lookup/dotfolder-array/dotfolder-array.test.js
- test/config-lookup/dotfolder-single/dotfolder-single.test.js
- test/config/basic/basic-config.test.js
- test/config/empty/empty-config.test.js
- test/config/type/array/array-config.test.js
- test/config/type/function/function-config.test.js
- test/defaults/output-defaults.test.js
- test/defaults/without-config-and-entry/default-without-config.test.js
- test/entry/defaults-empty/entry-single-arg.test.js
- test/entry/defaults-index/entry-multi-args.test.js
- test/global/global.test.js
- test/merge/config/merge-config.test.js
- test/merge/defaults/merge-defaults.test.js
- test/node/node.test.js
- test/output/named-bundles/output-named-bundles.test.js
- test/output/pretty/pretty.test.js
- test/standard/standard.test.js
- test/stats/.gitignore
- test/stats/index.js
- test/stats/package.json
- test/stats/stats.test.js
- test/stats/webpack.config.js
It implements the `stats` option for webpack via CLI.
Closes #1298
Yes
Yes
**Summary**
These options https://webpack.js.org/configuration/stats/#stats are now passed to the compiler via CLI.
I also removed the "fancy" output with the table. I had a discussion with the core maintainers about the library. The CLI should not alter the output of the compiler. I left `--pretty` as option, so we can still use but it is experimental.
Kind of because it removed `--standard` flag.
> feat(webpack-cli): stats

- packages/webpack-cli/__tests__/ZeroConfigGroup.test.js
Test
Yes
NA
**Summary**
Added one more test case for mode option none.
NO
TO BE MERGED AFTER #1303
> tests: add case for mode option none in ZeroGroupConfig

- packages/webpack-cli/package.json
- yarn.lock
Reduce package size
No need
No need
**Summary**
We don't use that package in our code
No
We don't need extra logger because webpack has own loggers
> chore: reduce install size

- test/entry/config-entry/entry-with-command/entry-with-command.test.js
- test/entry/config-entry/entry-with-config/entry-with-config.test.js
Test cases about entry and stats
already exist
NA
**Summary**
No
NA
> Remove the extractSummary methods in test case

- packages/generators/src/utils/languageSupport.ts
bugfix
no
no
**Summary**
Fixed the `regular expression` of loader's `test` field in `webpack.config.js` generated by `webpack-cli init`
no
the regex should be `\.jsx?$` or `\.(js|jsx)$`, the original string should be `"/\\.(js|jsx)$/"` instead of `/.(js|jsx)$/`
the same with `"/.(ts|tsx)?$/"` -> `"/\\.(ts|tsx)$/"`
```js
/.(ts|tsx)?$/.test("anystring") === true
/.(ts|tsx)$/.test("anystringts") === true
/\.(ts|tsx)$/.test("anystring.ts") === true
```
> [bugfix] webpack-cli init loader's test regex

- CODE_OF_CONDUCT.md
Doc change
**Summary**
Removed the team links as they're only visible to members of the webpack org, and fixed the code of conduct link
> chore: update code of conduct and fix links

- packages/webpack-cli/.eslintrc.js
chore
No need
No
**Summary**
For https://github.com/webpack/webpack-cli/pull/1345/
No
webpack-cli package do not use modules, don't know why we use that configuration
> chore: fix eslint configuration

- packages/webpack-cli/bin/cli.js
removed stale import-local
NA
NA
**Summary**
Fixes #1318 
NO
> chore(webpack-cli): improve import-local

- test/no-mode/no-mode.test.js
Minor fix. 
NA
**Summary**
Self Explanatory
No
> tests(webpack-cli): correct descriptions for no-mode test cases

- packages/serve/package.json
bugfix
No need
No need
**Summary**
Allow developers to install any webpack-dev-server version (3 or next) + move webpack-cli to peer dependencies, because it is peer dependency
Yes, you should add webpack-cli and webpack-dev-server to package.json and install them if you want to use `webpack serve`
No
> fix: peer dependencies for `webpack serve`

- yarn.lock
`yarn.lock` file is not up-to-date.
To reproduce the error -  
- reset the branch with `upstream/next`
- run `yarn`
- see differences
NA
NA
**Summary**
NA
NO
> fix: yarn.lock conflicts on setup

- test/utils/test-utils.js
A trivial jsdoc fix. Fixes docblock for a test util function `run`.
(chore)
> docs: Fix jsdoc comment for a test util function `run`

- package.json
- packages/generators/__tests__/init-generator.test.ts
- packages/generators/__tests__/loader-generator.test.ts
- packages/generators/__tests__/plugin-generator.test.ts
- packages/utils/package.json
- yarn.lock
fix/chore
no
N/A
**Summary**
Solves https://github.com/webpack/webpack-cli/issues/1386 for me
No
> chore(deps): upgrade jest

- packages/webpack-cli/lib/utils/cli-flags.js
enhancement, fix
No
No
**Summary**
Mode option accepts three values `production, development and none`, none was missing in usage. Hence added.
No
> fix(webpack-cli): add value none in mode usage

- packages/generate-loader/templates/src/_index.js.tpl
Doc updates in template 
No need
No need
**Summary**
- Rm deprecated docs link, update with new.
No
> docs: fix loading doc link in loader-generator

- packages/webpack-cli/README.md
- packages/webpack-cli/lib/bootstrap.js
- packages/webpack-cli/lib/utils/cli-flags.js
- test/version/version-multi-args.test.js
- test/version/version-single-arg.test.js
Feature. added alias for version.
YES
YES
**Summary**
Fixes #1368 
No
NA
>  feat(webpack-cli): add alias for version

- test/stats/stats.test.js
- test/zero-config/entry-absent/zero-config.test.js
- test/zero-config/entry-present/src/index.js
- test/zero-config/entry-present/zero-config.test.js
- test/zero-config/with-config/index.js
- test/zero-config/with-config/webpack.config.js
- test/zero-config/with-config/zero-config-entry.test.js
tests
Yes
NA
**Summary**
- Add some test cases for zero-config.
No
- Any suggestion on how to strengthen are appreciated.
> tests: add test for zero config

- packages/webpack-cli/lib/utils/cli-flags.js
> fix(webpack-cli): correct cli-flags usage

- packages/generators/__tests__/plugin-generator.test.ts
- packages/generators/__tests__/utils/plugins.test.ts
- packages/generators/src/utils/plugins.ts
tests
Yes
No
**Summary**
generators plugins util tests
No
> tests(generators): plugins util tests

- packages/webpack-scaffold/src/index.ts
refactoring
Nope
Nope
**Summary**
Follow up of #1452
Nope
N/A
> chore(webpack-scaffold): use default params

- packages/generators/__tests__/utils/styleSupport.test.ts
tests
Yes
No
**Summary**
`styleSupport` util tests in the generators package
The `isProd` property is never set to true anywhere in the `init-generator`. Any thoughts on if it should actually be used? Maybe this is suited for an issue, since on a broader level it is a question of exactly what the default generators should do.
No
> tests(generators): added style support tests

- package.json
small chore
No
No
**Summary**
Prettier sometimes fails when it hits `.yo-rc.json` files, so it would be nice to clean them out
No
> chore: remove yo-rc on clean command

- packages/webpack-cli/lib/utils/Compiler.js
This is a bugfix request. It aims to make the webpack Plugin name consistent throughout the codebase preventing any collision with webpack core plugin name.
Not yet, will add if needed
Not Yet
**Summary**
@evilebottnawi  requested to make the plugin name consistent throughout the code base. 
No
> fix: consistent webpack plugin name throughout

- packages/migrate/src/index.ts
- packages/utils/__tests__/run-prettier.test.ts
- packages/utils/src/run-prettier.ts
- test/init/generator/init-inquirer.test.js
- test/loader/loader.test.js
- test/migrate/config/bad-webpack.config.js
- test/migrate/config/migrate-config.test.js
- test/migrate/config/webpack.config.js
- test/output/named-bundles/output-named-bundles.test.js
- test/utils/test-utils.js
fix/tests
Yes (still need to add tests for runPrettier)
I'm not exactly sure how the migrate command is supposed to work. Could someone give an example of a webpack config that it should make modifications to?
No
**Summary**
@jamesgeorge007 Sorry for taking over, just couldn't debug `runPromptWithAnswers` without using your changes. It seems that execa does not like an empty `input` string option.
- Fixes `runPromptWithAnswers`
- Fixes migrate
- Fixes issues with `runPrettier`
Slightly with how `runPrettier` works
> Fix migrate command

- test/entry/flag-entry/entry-with-flag.test.js
- test/output/named-bundles/output-named-bundles.test.js
Tests.
Refers #899 
Yes
NA
**Summary**
this ensures `entry` and `output` resolve the path the same way
NO
> tests: add case to ensure entry and output resolve path same way

- packages/webpack-cli/lib/groups/StatsGroup.js
- packages/webpack-cli/lib/utils/cli-flags.js
- test/stats/stats.test.js
- test/verbose/index.js
- test/verbose/verbose-flag.test.js
fixes verbose flag implementation.
Yes
NA
**Summary**
Fixes #1542 
No
> fix(webpack-cli): verbose flag functionality

- test/init/language/css/init-language-css.test.js
- test/init/language/js/init-language-js.test.js
refactoring
Nope
Nope
**Summary**
- Checks whether `webpack.config.js` is generated as a result of `init`.
- Got rid of the extraneous instruction intended to mock user behavior.
Nope
N/A
> tests: check for the existence of webpack config file

- packages/webpack-cli/__tests__/OutputGroup.test.js
Test
YES
**Summary**
Added unit test for OutputGroup
NO
> tests: create unit test for OutputGroup

- packages/webpack-cli/__tests__/StatsGroup.test.js
- packages/webpack-cli/lib/groups/StatsGroup.js
- test/json/json.test.js
fix
YES
NA
**Summary**
Fixes #1586 
no
> fix(webpack-cli): remove invalid stats warning with json flag

- packages/init/src/index.ts
- packages/utils/src/modify-config-helper.ts
- packages/utils/src/scaffold.ts
- test/init/force/init-force.test.js
- test/init/generator/init-inquirer.test.js
Feature and refactors
Yes, WIP
No
**Summary**
Part of #1509 
- Addition of `--force` flag to force config generation (in case of 0CJS as well).
No.
**Work In Progress**,
> feat(init): add features and refactor

- packages/webpack-cli/lib/utils/cli-executer.js
enhancement
Nope
Nope
**Summary**
An in-house warning shows up if the user doesn't supply a value for required flags as part of `cli-executer`.
Nope
N/A
> feat(cli-executer): validate user input

- test/config/multiple/.webpack/webpack.config.dev.js
- test/config/multiple/.webpack/webpack.config.prod.js
- test/config/multiple/index.js
- test/config/multiple/multiple-config.test.js
tests
Yes
NA
**Summary**
- Add tests when there are multiple configs present in dotfolder
No
> tests: add test for multiple config in dotfolder

- package.json
- packages/utils/src/modify-config-helper.ts
- yarn.lock
With this PR I aim to upgrade typescript to the latest. 
Testing notes:
- All linters passed ✅
- All builds passed ✅
- Unit tests 9 failed, but believe this to be a windows issue. 
- There was only 1 code change required, and was due to a fundamental type mismatch. I've noted that in the [line-comment](https://github.com/webpack/webpack-cli/pull/1636/files#r441183817). 
fixes #1617
> chore: upgrades typescript to the latest

- packages/webpack-cli/README.md
- packages/webpack-cli/__tests__/arg-parser.test.js
- packages/webpack-cli/lib/bootstrap.js
- packages/webpack-cli/lib/groups/BasicGroup.js
- packages/webpack-cli/lib/utils/arg-parser.js
- packages/webpack-cli/lib/utils/cli-flags.js
- test/entry/flag-entry/entry-with-flag.test.js
- test/entry/multiple-entries/multi-entries.test.js
- test/entry/multiple-entries/src/a.js
- test/entry/multiple-entries/src/b.js
- test/entry/multiple-entries/src/c.js
- test/init/auto/init-auto.test.js
- test/init/force/init-force.test.js
- test/init/generator/init-inquirer.test.js
- test/init/multipleEntries/init-multipleEntries.test.js
Feature
YES
YES
**Summary**
Now we can provide multiple entry files via CLI using  -
- `webpack --entry=a.js --entry=b.js` 
- `webpack ./a.js ./b.js`
Refers #717
Fixes #1454 
> feat(webpack-cli): allow multiple entry files

- packages/webpack-cli/__tests__/AdvancedGroup.test.js
- test/target/flag-test/index.js
- test/target/flag-test/target-flag.test.js
- test/target/flag-test/webpack.config.js
Tests
Yes
No
**Summary**
added tests for --target
NO
NO
> tests: add tests for --target flag

- packages/webpack-cli/lib/groups/HelpGroup.js
- packages/webpack-cli/lib/utils/cli-flags.js
enhancement
Nope
Nope
**Summary**
- Added aliases for all available commands.
- Updated the help information to show up command aliases.
Nope
N/A
> feat: add aliases to all available commands

- packages/webpack-cli/lib/groups/HelpGroup.js
- packages/webpack-cli/lib/utils/cli-flags.js
- test/help/help-commands.test.js
- test/help/help-flags.test.js
- test/help/help-multi-args.test.js
- test/info/info-help.test.js
enhancement
Updated existing tests.
Nope
**Summary**
Help information for individual `cli-flags` shows up the corresponding alias if it exists.
Nope
N/A
> feat: show up cli flag aliases with webpack help <arg>

- packages/webpack-cli/__tests__/arg-parser.test.js
- packages/webpack-cli/lib/groups/HelpGroup.js
- packages/webpack-cli/lib/groups/StatsGroup.js
- packages/webpack-cli/lib/utils/arg-parser.js
- packages/webpack-cli/lib/utils/cli-flags.js
- test/stats/stats.test.js
- test/stats/webpack.config.js
Feature.
WIP
WIP
**Summary**
Refers #717 
Allow multiple types for stats argument, i.e.
`webpack --stats (means stats: true)`,
`webpack --stats=verbose (means: stats: verbose)`
No
> feat(webpack-cli): allow multiple types for --stats

- packages/webpack-cli/lib/groups/HelpGroup.js
- packages/webpack-cli/lib/utils/arg-parser.js
- packages/webpack-cli/lib/utils/commands.js
- test/version/version-external-packages.test.js
bugfix
yup
Nope
**Summary**
`webpack-cli plugin | loader --version` shows up the respective information.
Nope
N/A
> fix: show version information for plugin and loader subcommands

- packages/webpack-cli/lib/groups/HelpGroup.js
- test/version/version-external-packages.test.js
enhancement
Yup
N/A
**Summary**
Support command aliases with `webpack-cli version`
```bash
webpack-cli c version
@webpack-cli/init 1.0.1-alpha.5
webpack-cli 4.0.0-beta.8
webpack 4.43.0
```
Nope
N/A
> feat: support command aliases with webpack-cli version

- packages/webpack-cli/lib/groups/ConfigGroup.js
- packages/webpack-cli/lib/webpack-cli.js
- test/config/type/promise/promise-config.test.js
fix
Yes
NA
**Summary**
- Promise config support wasn't working and tests were all skipped, enabled them
No
> fix: promise support in config

- .gitignore
- test/config/multiple/all/multiple-config.test.js
- test/config/multiple/multiple-location/multiple-location-config.test.js
- test/config/multiple/none and dev/dev-none-config.test.js
- test/config/multiple/with-mode/multiple-config.test.js
- test/entry/scss/.gitignore
- test/mode/mode-with-config/.gitignore
- test/output/named-bundles/output-named-bundles.test.js
- test/prefetch/prefetch.test.js
- test/stats/cli-flags/.gitignore
- test/stats/config/.gitignore
- test/typescript/.gitignore
chore
Yes
No need
**Summary**
- We now have scripts which handle the test directory removal, this is redundant 
- Remove test level gitignores, easy is to handle at root
> chore: rm redundant test dir cleanup, rm test level gitignore and handle at root

- scripts/cleanupTest.js
- test/init/auto/init-auto.test.js
- test/init/force/init-force.test.js
- test/init/generator/init-inquirer.test.js
- test/init/language/css/init-language-css.test.js
- test/init/language/js/init-language-js.test.js
- test/init/multipleEntries/init-multipleEntries.test.js
- test/loader/loader.test.js
- test/migrate/config/migrate-config.test.js
- test/plugin/plugin.test.js
cleanup
N/A
N/A
**Summary**
Follow up of #1669
N/A
> chore: remove redundant instructions

- packages/info/src/index.ts
- test/info/info-help.test.js
- test/info/info-output.test.js
- test/info/info-unknown.test.js
- test/utils/test-utils.js
enhancement
Yes
N/A
**Summary**
- The existing strategy for handling unknown args with `webpack-cli info` didn't work as expected. Fixed it!
- A new helper method `runInfo()` to be consumed across test suites.
```bash
$ webpack-cli info --unknown
Unknown argument: --unknown
System:
OS: macOS 10.15.5
CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
Memory: 131.43 MB / 8.00 GB
Binaries:
Node: 13.11.0 - /usr/local/bin/node
Yarn: 1.22.4 - /usr/local/bin/yarn
npm: 6.14.6 - /usr/local/bin/npm
Browsers:
Brave Browser: 83.1.10.97
Safari: 13.1.1
Packages:
webpack: ^4.43.0 => 4.43.0
Global Packages:
webpack-cli: 4.0.0-beta.8
```
**Does this PR introduce a …
> chore: handle unknown args and improve test suite for info

- packages/webpack-cli/__tests__/ZeroConfigGroup.test.js
tests
yes
NA
**Summary**
more test cases
no
no
> tests: add more cases in ZeroConfigGroup test

- .github/workflows/nodejs.yml
chore
N/A
N/A
**Summary**
Enables `workflow_dispatch` event so that the workflow can be triggered manually.
Nope
https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
> chore: enable workflow_dispatch event

- packages/webpack-cli/lib/groups/ConfigGroup.js
- packages/webpack-cli/lib/utils/cli-flags.js
- test/config/type/function-with-env/a.js
- test/config/type/function-with-env/function-with-env.test.js
- test/config/type/function-with-env/webpack.config.js
feat
Yes
Yes
**Summary**
Having multiple env is a common use case so a single arg won't suffice, hence added support for multiple
No
> feat: support multiple env params

- packages/generate-plugin/templates/src/_index.js.tpl
- test/plugin/plugin.test.js
bugfix
YES
NA
**Summary**
Fixes #1623, the closing brace (`}`) was missing.
No
> fix: generated plugin template

- test/entry/config-entry/entry-with-index/entry-with-config.test.js
- test/entry/config-entry/entry-with-index/src/app.js
- test/entry/config-entry/entry-with-index/src/index.js
- test/entry/config-entry/entry-with-index/src/print.js
- test/entry/config-entry/entry-with-index/webpack.config.js
tests
Yes
NA
**Summary**
A case was reported by a user https://github.com/webpack/webpack-cli/issues/1222#issuecomment-665555817 so added tests for that behaviour
No
https://github.com/webpack/webpack-cli/issues/1222#issuecomment-665555817
> tests: add tests for entry in config

- packages/serve/src/index.ts
- test/help/help-commands.test.js
- test/serve/basic/serve-basic.test.js
bugfix
yup
N/A
**Summary**
- `webpack-cli serve help` should throw an error.
- Added a test case to ensure that `serve` respects `--no-color` flag.
Nope
N/A
> fix(serve): supplying help or version as an arg should throw

- test/core-flags/module-flags.test.js
tests
NA
NA
**Summary**
removed `--module-rules-options` instances as it has been excluded for cli from core schema. 
NO
https://github.com/webpack/webpack/pull/11171
> tests: remove --module-rules-options instances

- packages/serve/src/index.ts
- packages/webpack-cli/lib/bootstrap.js
- packages/webpack-cli/lib/groups/HelpGroup.js
- packages/webpack-cli/lib/utils/logger.js
- test/hot/hot-flag.test.js
- test/no-hot/no-hot.test.js
chore, refactor
Already in place
NA
**Summary**
Align logging with `console`. 
https://github.com/webpack/webpack-cli/pull/1681#discussion_r467863959
> chore: use console for logging

- packages/info/src/index.ts
- test/info/info-help.test.js
- test/info/info-unknown.test.js
bugfix
Generic test cases were added as part of #1694
N/A
**Summary**
Follow up of #1694
Nope
N/A
> fix(info): throw an error if help or version is passed as an arg

- packages/webpack-cli/__tests__/ZeroConfigGroup.test.js
- packages/webpack-cli/lib/groups/ZeroConfigGroup.js
- test/mode/mode-single-arg/mode-single-arg.test.js
- test/mode/mode-single-arg/src/index.js
- test/mode/mode-single-arg/src/main.js
chore
YES
NA
**Summary**
webpack already validates the config. No need to do double work.
NO
> chore: remove --mode flag validation

- README.md
- packages/package-utils/__tests__/packageUtils.test.ts
- packages/package-utils/src/packageUtils.ts
- packages/utils/src/modify-config-helper.ts
- packages/utils/src/npm-packages-exists.ts
- packages/webpack-cli/lib/groups/HelpGroup.js
- packages/webpack-cli/lib/utils/process-log.js
fix, docs,
Yes
Yes
**Summary**
Use appropriate exit codes and document their meanings.
No
NA
> fix: use appropriate exit codes

- packages/webpack-cli/README.md
- packages/webpack-cli/lib/groups/ConfigGroup.js
- packages/webpack-cli/lib/utils/cli-flags.js
- test/config-name/config-name.test.js
- test/config-name/src/first.js
- test/config-name/src/second.js
- test/config-name/src/third.js
- test/config-name/webpack.config.js
Feature
Yes
Yes
**Summary**
Addition of `--config-name` flag.
No
Fixes #1657
> feat: add --config-name flag

- packages/webpack-cli/lib/groups/ConfigGroup.js
fix
Yes
No need
**Summary**
- Remove unnecessary filtering
- We filter all the config based on the available extensions in interpret which is not right and files should fallback to the default node require when they don't have a module needed.
No
Question -> when we pass some file which doesn't exist ex `-c webpack.testconfig.js` we fallback to default config `webpack.config.js`, should we allow that considering the user already passed a config they want to use or should we throw err that config not found?
> fix: allow unknown files to use default require as fallback

- packages/webpack-cli/README.md
- packages/webpack-cli/__tests__/ConfigGroup/ConfigGroup.test.js
- packages/webpack-cli/__tests__/ConfigGroup/webpack.config.cjs
- packages/webpack-cli/lib/groups/ConfigGroup.js
- packages/webpack-cli/lib/utils/cli-flags.js
- test/help/help-flags.test.js
- test/merge/config-absent/merge-config-absent.test.js
- test/merge/config/merge-config.test.js
feat/fix
Yes
Yes
**Summary**
- Merges all configurations together instead of single file
- Merge flag is a boolean now
- You can now do `webpack -c 1.js -c 2.js -c 3.js --merge` which was not possible before 
No
> feat: add support for merging multiple configurations

- packages/webpack-cli/lib/utils/Compiler.js
- test/progress/progress-flag.test.js
Design Bug Fix
Yes
N/A
**Summary**
Using webpack's default handler for progress plugin instead of providing one in CLI.
No
> fix: use compiler.apply for Progress Plugin

- test/progress/index.js
- test/progress/progress-flag.test.js
- test/progress/src/index.js
- test/progress/webpack.progress.config.js
tests
yes
no need
**Summary**
- Add tests to ensure we're only applying progress plugin once
no
Fixes https://github.com/webpack/webpack-cli/issues/1497
> tests: ensure progress plugin is applied only once

- packages/generators/src/addon-generator.ts
- packages/generators/src/init-generator.ts
- packages/info/src/index.ts
- packages/migrate/package.json
- packages/migrate/src/index.ts
- packages/migrate/src/removeDeprecatedPlugins/removeDeprecatedPlugins.ts
- packages/utils/__tests__/run-prettier.test.ts
- packages/utils/package.json
- packages/utils/src/modify-config-helper.ts
- packages/utils/src/recursive-parser.ts
- packages/utils/src/resolve-packages.ts
- packages/utils/src/run-prettier.ts
- packages/utils/src/scaffold.ts
- packages/webpack-cli/lib/bootstrap.js
- packages/webpack-cli/lib/groups/BasicGroup.js
- packages/webpack-cli/lib/groups/HelpGroup.js
- packages/webpack-cli/lib/utils/cli-executer.js
- packages/webpack-cli/lib/utils/logger.js
- test/entry/flag-entry/entry-with-flag.test.js
- test/migrate/config/migrate-config.test.js
refactoring
N/A
N/A
**Summary**
Follow up of #1740
N/A
> refactor: use logger

- packages/webpack-cli/lib/groups/HelpGroup.js
refactoring
N/A
N/A
**Summary**
Remove duplicate invocation of methods.
Nope
N/A
> refactor: remove duplicate invocation

- .yarnrc
Adds latency to yarnrc
N/A
N/A
**Summary**
https://github.com/webpack/webpack-cli/pull/1791 fails due latency
No
> chore: add network timeout in yarnrc

- packages/package-utils/package.json
Bug fix
N/A
N/A
**Summary**
This PR fixes the first issue of #1815 by declaring default command packages (included in `webpack-cli`) as optional peer dependencies of `@webpack-cli/package-utils` to enable it to resolve them.
No
> fix: declare default commands as optional peer dependencies

- packages/webpack-cli/__tests__/resolveMode.test.js
- packages/webpack-cli/lib/groups/resolveMode.js
- packages/webpack-cli/lib/webpack-cli.js
- test/mode/mode-single-arg/mode-single-arg.test.js
- test/mode/mode-with-config/mode-with-config.test.js
- test/mode/mode-with-config/webpack.config3.js
- test/utils/test-utils.js
fix
Yes
Yes
**Summary**
Fix mode priority 
- mode form flag
- config
- NODE_ENV
Nay
> fix: mode behaviour

- packages/utils/package.json
- packages/utils/src/run-prettier.ts
- yarn.lock
chore
No
No
**Summary**
Make prettier a peer dep meta as prettier is generally available to the user.
People will now have to install prettier on there own to use init
Based of recent feedbacks
> chore: make prettier peer dependency meta

- packages/package-utils/package.json
- packages/webpack-cli/bin/cli.js
- packages/webpack-cli/lib/utils/Compiler.js
- packages/webpack-cli/lib/utils/cli-flags.js
fix
no
no
**Summary**
prompt to install `webpack` if it's not present already.
No
Refers https://github.com/webpack/webpack-cli/issues/1383#issuecomment-608225508
Fixes https://github.com/webpack/webpack-cli/issues/1383
> fix: check webpack installation before running cli

- packages/info/src/options.ts
- packages/webpack-cli/__tests__/arg-parser.test.js
- packages/webpack-cli/lib/bootstrap.js
- packages/webpack-cli/lib/groups/HelpGroup.js
- packages/webpack-cli/lib/groups/runVersion.js
- packages/webpack-cli/lib/utils/arg-parser.js
- packages/webpack-cli/lib/utils/arg-utils.js
- packages/webpack-cli/lib/utils/cli-flags.js
- packages/webpack-cli/lib/webpack-cli.js
Refactor
Yes
**Summary**
- Changes version to a simple fn and takes a single param and move out of help group, remove instance from `webpack-cli`
- Cleaned up redundant args in arg parser
- Only invoke once in bootstrap.js, instead of multiple places
No
> chore: cleanup version invocation, argParser

- package.json
- packages/webpack-cli/README.md
- packages/webpack-cli/__tests__/resolveAdvanced.test.js
- packages/webpack-cli/lib/groups/resolveAdvanced.js
- packages/webpack-cli/lib/utils/cli-flags.js
- packages/webpack-cli/package.json
- test/analyze/analyze-flag.test.js
- test/analyze/main.js
- test/analyze/webpack.config.js
- test/utils/test-utils.js
- yarn.lock
Feature
WIP
WIP
**Summary**
Invoke `webpack-bundle-analyzer` plugin via `--analyze` flag.
No
Fixes #1838
> feat: add --analyze flag

- .github/workflows/nodejs.yml
- test/node/node.test.js
build
NA
NA
**Summary**
Trying running CI on Node 14
No
> feat: bump CI Node to 14

- package.json
- packages/webpack-cli/lib/utils/Compiler.js
- test/watch/watch-flag.test.js
fix
yes
NA
**Summary**
Logs compilation lifecycle during watch mode.
No
Fix https://github.com/webpack/webpack-cli/issues/1902
> fix: add compilation lifecycle in watch instance

- packages/webpack-cli/lib/utils/flag-defaults.js
- packages/webpack-cli/lib/webpack-cli.js
- test/cache/cache.test.js
- test/cache/webpack.config.js
- test/core-flags/cache-flags.test.js
- test/core-flags/src/index.js
- test/core-flags/webpack.cache.config.js
- test/core-flags/webpack.config.js
feat
Yes
NA
**Summary**
https://webpack.js.org/configuration/other-options/#cachebuilddependencies
- After resolving core flags, assigns the configs as a build dep which is invalidated when configs change
No
> feat: assign config paths in build dependencies in cache config

- packages/webpack-cli/__tests__/cli-executer.test.js
- packages/webpack-cli/lib/bootstrap.js
- packages/webpack-cli/lib/utils/arg-parser.js
- packages/webpack-cli/lib/utils/cli-executer.js
bugfix
Updated existing tests.
N/A
**Summary**
closes #1901 
Nope
N/A
> fix: cli-executer supplies args further up

- packages/README.md
- packages/webpack-cli/README.md
docs
Yes
Yes
**Summary**
Removes ref to `package-utils` which is a deprecated package.
No
> docs: remove reference to package-utils (deprecated)

- packages/webpack-cli/lib/groups/ConfigGroup.js
- test/config-lookup/custom-name/a.js
- test/config-lookup/custom-name/config.webpack.js
- test/config-lookup/custom-name/custom-name.test.js
bugfix
Yes
**Summary**
fixes #1925
No
context should not be changed never
> fix: support any config name

- package.json
- packages/webpack-cli/lib/utils/Compiler.js
- test/build-errors/errors.test.js
- test/build-warnings/warnings.test.js
- test/cache/cache.test.js
- test/colors/colors-false.webpack.config.js
- test/colors/colors-true.webpack.config.js
- test/colors/colors.test.js
- test/colors/no-stats.webpack.config.js
- test/colors/src/index.js
- test/colors/stats-boolean.webpack.config.js
- test/colors/stats-string.webpack.config.js
- test/core-flags/cache-flags.test.js
- test/watch/watch-flag.test.js
- yarn.lock
fix
yes
No need
**Summary**
fixes #1915
No
No
> fix: colored output

- packages/utils/package.json
Bugfix (this doesn't fix any bugs, but in terms of semver I think it should be a fix)
N/A
N/A
**Summary**
In #1816, default commands packages were added to peer dependencies of `@webpack-cli/package-utils`, as they were required by `packageExists` in order to fix #1815.
However, in #1822, `packageExists` was moved directly into `webpack-cli` not `@webpack-cli/utils`, so `@webpack-cli/utils` doesn't require them.
No
Note #1815 has been fixed by #1822.
> fix: remove unnecessary optional peer dependencies

- packages/webpack-cli/lib/utils/__tests__/package-exists.test.js
- packages/webpack-cli/lib/utils/arg-parser.js
- packages/webpack-cli/lib/utils/resolve-command.js
- packages/webpack-cli/package.json
bugfix
No need
No
**Summary**
fixes #1916
No, because we ask to install it if you need, maybe we will refactor it in future and reduce deps more
No
> fix: move init command to separate package

- packages/webpack-cli/bin/cli.js
bugfix
hard to tests, but I think we can improve it in future, manual testing
No
**Summary**
Let's run webpack-cli after webpack installation
No
> fix: run CLI after webpack installation

- packages/webpack-cli/lib/groups/ConfigGroup.js
- packages/webpack-cli/lib/utils/arg-parser.js
- packages/webpack-cli/lib/utils/cli-flags.js
- test/config/type/function-with-env/function-with-env.test.js
- test/config/type/function-with-env/webpack.env.config.js
- test/config/type/promise-function/promise-function.test.js
feat/fix
Yes
Need to reflect in docs
**Summary**
- Allow passing strings to env flag which is passed to config
- You can now do - 
`webpack --env platform=app --env production`
which will pass `{ platform: "app", production: true }` to the config
Nope
Fixes https://github.com/webpack/webpack-cli/issues/1932
> feat: allow passing strings in env flag

- packages/webpack-cli/lib/plugins/WebpackCLIPlugin.js
- packages/webpack-cli/lib/utils/cli-flags.js
- test/progress/progress-flag.test.js
feature
Yes
No
**Summary**
request from @sokra 
No
No
> feat: progress supports string argument

- packages/generators/__tests__/__snapshots__/init-generator.test.ts.snap
- packages/generators/__tests__/init-generator.test.ts
- packages/generators/src/utils/webpackConfig.ts
fix 
Yes
No
**Summary**
Fixes #2003 
`optimization.splitChunks.name: true` is not allowed for webpack-5.
No
> fix(generators): correct optimization.splitChunks option in config

- packages/webpack-cli/lib/bootstrap.js
- packages/webpack-cli/package.json
- test/unknown/unknown.test.js
feature
Yup
N/A
**Summary**
Refers #1261 
Suggest the closest match for an unknown flag.
Nope
N/A
> feat: suggest the closest match based on the Levenshtein distance algorithm

- packages/generate-loader/src/index.ts
- packages/generate-plugin/src/index.ts
- packages/generators/__tests__/addon-generator.test.ts
- packages/generators/src/addon-generator.ts
- packages/generators/src/init-generator.ts
- packages/info/src/index.ts
- packages/migrate/src/index.ts
- packages/migrate/src/removeDeprecatedPlugins/removeDeprecatedPlugins.ts
- packages/serve/src/parseArgs.ts
- packages/utils/__tests__/global-packages-path.test.ts
- packages/utils/src/global-packages-path.ts
- packages/utils/src/modify-config-helper.ts
- packages/utils/src/recursive-parser.ts
- packages/utils/src/resolve-packages.ts
- packages/utils/src/run-prettier.ts
- packages/utils/src/scaffold.ts
- packages/utils/src/spawn-child.ts
- packages/webpack-cli/lib/index.js
- packages/webpack-cli/lib/utils/__tests__/get-package-manager.test.js
- packages/webpack-cli/lib/utils/__tests__/prompt-installation.test.js
- packages/webpack-cli/lib/utils/get-package-manager.js
- packages/webpack-cli/lib/utils/prompt-installation.js
- packages/webpack-cli/lib/webpack-cli.js
- packages/webpack-cli/package.json
feat
Yes
NA
**Summary**
Exported some utils which are used by other packages so we won't depend on the file structure as it can change in core hence it will break other packages.
No
NA
> feat: export utils from core for other packages

- packages/webpack-cli/lib/webpack-cli.js
fix
Yes
NA
**Summary**
https://github.com/webpack/webpack-cli/pull/2009#discussion_r515927500
Nope
> fix: handle core flags for webpack 4

- .github/workflows/nodejs.yml
- jest.config.js
- scripts/globalSetup.js
- test/progress/progress-flag.test.js
chore
Yes
NA
**Summary**
This display running webpack version during tests, useful to check if the CI cache is working correctly and locally to ensure we're running tests on correct env.
No
> chore: display running webpack version during tests

- .codecov.yml
- .nycrc
feature
N/A
No
**Summary**
Configure reporting of codecov
No
related to #1899
> feat: configure codecov reporting

- test/core-flags/context-flag.test.js
tests
yes
NA
**Summary**
add a case for invalid context value
No
No
> tests: add a case for invalid context value

- packages/serve/__tests__/createConfig.test.ts
- packages/serve/src/createConfig.ts
- packages/serve/src/index.ts
- packages/serve/src/parseArgs.ts
- packages/serve/src/startDevServer.ts
- test/serve/basic/serve-basic.test.js
- test/utils/test-utils.js
fix
Yes
Need update 
**Summary**
- Fix how `hot` flag is resolved in serve package
No
Fixes #2004
> fix: resolve dev server hot options correctly

- packages/serve/__tests__/__snapshots__/parseArgs.test.ts.snap
- packages/serve/src/index.ts
- packages/serve/src/parseArgs.ts
- test/serve/serve-variable/serve-basic.test.js
- test/serve/serve-variable/src/index.js
- test/serve/serve-variable/webpack.config.js
Add WEBPACK_SERVE variable in environment and in main process if `webpack serve` is used.
Yes
No
**Summary**
Fixes #1973 
Yes,
1. Exposing `WEBPACK_SERVE` variable which was earlier `WEBPACK_DEV_SERVER` when dev server was not integrated into CLI.
2. New variable `WEBPACK_SERVE` is now accessable only through `env` argument supplied to webpack configuration of type `function`.
> feat: add WEBPACK_SERVE environment variable

- packages/webpack-cli/lib/groups/resolveConfig.js
- packages/webpack-cli/lib/utils/flag-defaults.js
- packages/webpack-cli/lib/webpack-cli.js
- test/core-flags/cache-flags.test.js
fix
WIP
NA
**Summary**
We assign config path in cache properties passed to the compiler, it didn't take into account the default configs which are resolved so this should fix it.
Nope
Tests WIP
> fix: assign cache value for default configs

- packages/webpack-cli/lib/utils/__tests__/get-package-manager.test.js
- packages/webpack-cli/lib/utils/__tests__/prompt-installation.test.js
- packages/webpack-cli/lib/utils/get-package-manager.js
- packages/webpack-cli/lib/utils/prompt-installation.js
feature
Yes
No
**Summary**
add `pnpm` support for package installation
No
No
> feat: add pnpm support for package installation

- packages/webpack-cli/lib/utils/cli-flags.js
fix
NA
NA
**Summary**
Remove the default value of some flags since they are invalid and not used in most cases.
No
> fix: remove default value for devtool

- packages/serve/src/startDevServer.ts
fix
No, not sure how to test this behaviour
NA
**Summary**
- Catch dev server import when importing from webpack-dev-server, in future if FS in dev-server side changes, this can potentially break, so we need to catch this behaviour.
No
No
> fix: catch dev server import during webpack serve

- packages/generators/__tests__/__snapshots__/init-generator.test.ts.snap
- packages/generators/src/init-generator.ts
fix
Updated snapshots
No
**Summary**
- Using contenthash is preferred for long term caching, clear todo
Shouldn't
> fix: use content hash for css assets in init-generator

- packages/generate-loader/README.md
- packages/generate-loader/src/index.ts
- test/loader/loader.test.js
Enhancement
Yes
Nope
**Summary**
Added the ability to scaffold `loader` template in a specified path. Addresses #2021
Nope
https://github.com/webpack/webpack-cli/issues/2021#issuecomment-722395490
> feat(generate-loader): scaffold in a specified path

- packages/serve/__tests__/__snapshots__/parseArgs.test.ts.snap
- packages/webpack-cli/lib/bootstrap.js
- packages/webpack-cli/lib/utils/cli-flags.js
- packages/webpack-cli/lib/webpack-cli.js
- test/colors/colors.test.js
- test/colors/multiple-configs.js
- test/colors/src/first.js
- test/colors/src/second.js
- test/config/type/function-with-argv/function-with-argv.test.js
- test/json/json.test.js
- test/unknown/unknown.test.js
bugfix
Yes
no
**Summary**
`stats` colors should be disabled if we use `--no-color`.
Fixes #2038  as well
Nope
No
> fix: allow to disable stats color via --no-color

- packages/webpack-cli/lib/utils/__tests__/resolve-command.test.js
- packages/webpack-cli/lib/utils/resolve-command.js
- packages/webpack-cli/lib/utils/run-command.js
fix
Nope
Nope
**Summary**
user logger for error
No
No
> fix: use logger to throw error with proper exit code

- packages/utils/__tests__/global-packages-path.test.ts
- packages/utils/package.json
- packages/utils/src/global-packages-path.ts
- yarn.lock
chore
Updated existing tests.
Nope
**Summary**
Remove extraneous dependency `cross-spawn`.
Nope
N/A
> chore(utils): remove cross-spawn

- packages/webpack-cli/lib/webpack-cli.js
- test/stats/watch/multi-webpack.config.js
- test/stats/watch/src/index.js
- test/stats/watch/stats-and-watch.test.js
- test/stats/watch/watch.test.js
- test/stats/watch/webpack.config.js
bugfix
Yes
No
**Summary**
fixes #2052
No
webpack@4 doesn't return `compier` when `watch: true` in the config, fixed in webpack@5
> fix: respect `stats` from the config for webpack@4

- packages/webpack-cli/lib/webpack-cli.js
- test/build-warnings/warnings.test.js
- test/colors/colors-false.webpack.config.js
- test/colors/colors-true.webpack.config.js
- test/colors/multiple-configs.js
- test/colors/stats-boolean.webpack.config.js
- test/colors/stats-string.webpack.config.js
- test/colors/webpack.config.js
- test/defaults/output-defaults.test.js
- test/merge/config/merge-config.test.js
- test/mode/mode-single-arg/mode-single-arg.test.js
- test/stats/watch/webpack.config.js
- test/watch/watch-flag.test.js
fix
Yes
Not needed I think
**Summary**
- Defer setting default mode to core so it can print warnings and stuff
Nope
> fix: defer setting default mode to core

- .github/workflows/nodejs.yml
Bugfix
N/A
N/A
**Summary**
> The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
No
> chore(ci): upgrade to using environment files

- packages/serve/__tests__/createConfig.test.ts
- packages/serve/src/createConfig.ts
- packages/serve/src/startDevServer.ts
Bug fix and refactor
Unit tests. Integration tests will be possible once after webpack-dev-server v4 has been released.
N/A
**Summary**
With https://github.com/webpack/webpack-dev-server/pull/2845, webpack-dev-server will handle setting the default port.
Depends on the PR above.
N/A
> fix(serve): do not default port in webpack-dev-server v4

- packages/serve/src/startDevServer.ts
Bug fix
Integration tests will be possible once after webpack-dev-server v4 has been released.
N/A
**Summary**
https://github.com/webpack/webpack-cli/pull/2126#discussion_r529471961
With https://github.com/webpack/webpack-dev-server/pull/2869, it'd be possible to pass `undefined` as the host to let `listen()` handle the address to bind to.
Depends on the PR above.
N/A
> fix(serve): do not default host in webpack-dev-server v4

- packages/serve/__tests__/mergeOptions.test.ts
- packages/serve/__tests__/startDevServer.test.ts
- packages/serve/src/startDevServer.ts
- packages/serve/src/types.ts
Resolves https://github.com/webpack/webpack-dev-server/issues/2873. This fixes a regression where `webpack serve` is not equivalent to the older `webpack-dev-server` command.
No, since the serve plugin's tests only run on webpack-dev-server@3 and my changes only apply to webpack-dev-server@4. If there is a way to run certain tests against different versions of webpack-dev-server, I'm happy to add tests.
N/A
**Summary**
webpack-dev-server adds a new entry point which loads the webpack-dev-server webpack client. The entry has a resource query which determines the host, port, and protocol of the websocket connection. That resource query must be created …
> fix(serve): set client port when using default port

- packages/webpack-cli/lib/webpack-cli.js
- packages/webpack-cli/package.json
This PR changes the approach for stats stringify to use stream instead of JSON.stringify() + sync write. No API or functionality is changed.
No
Not needed
**Summary**
It makes stats available for huge projects. Changes has the follow effects:
- Memory
- Allows to avoid max string length limit of V8 engine (500MB). In other words, stats becomes available for huge projects, whose stats exceed 500MB.
- Reduces memory consumption on serialization.
- Adds time penalty. However, this make sense for huge stats only and seems to be an acceptable, given that otherwise stats may be unavailable (due max string limit hit or out of memory).
- Adds new dependency …
> Stringify stats using streaming approach

- test/target/flag-test/target-flag.test.js
tests
yes
no
**Summary**
cover more cases.
No
No
> tests: add more cases for target

- packages/webpack-cli/lib/plugins/CLIPlugin.js
- packages/webpack-cli/lib/utils/logger.js
- packages/webpack-cli/lib/webpack-cli.js
- test/build-errors/errors.test.js
- test/build-warnings/warnings.test.js
- test/json/json.test.js
- test/json/logging.config.js
bugfix
WIP
No need
**Summary**
fixes #1535
No
No
> fix: the `--progress` option is working with `--json`

- packages/serve/__tests__/__snapshots__/startDevServer.test.ts.snap
- packages/serve/src/startDevServer.ts
- packages/serve/src/types.ts
- test/serve/basic/dev-server-output-public-path.config.js
- test/serve/basic/multi-dev-server-output-public-path.config.js
- test/serve/basic/multi-dev-server.config.js
- test/serve/basic/multi-output-public-path.config.js
- test/serve/basic/multi.config.js
- test/serve/basic/multiple-dev-server.config.js
- test/serve/basic/output-public-path.config.js
- test/serve/basic/serve-basic.test.js
- test/serve/basic/src/other.js
tests
Yes
No need
**Summary**
fixes #2242
No
WIP, need set `devServer.publicPath` when publicPath is passed
> tests: publicPath

- packages/webpack-cli/lib/webpack-cli.js
- test/config-format/failure/failure.test.js
- test/config-format/failure/webpack.config.coffee
bugfix
Yes
No need
**Summary**
useful error
No
fixes #1993
> fix: error message on not installed module loaders for configuration

- packages/webpack-cli/lib/index.js
- packages/webpack-cli/lib/webpack-cli.js
feature
No, it is for future tests and public API
No need right now, it is not public
**Summary**
For tests
No
Fix export, bevause we don't have commands right now, and we should pass `cli` instance to commands instead export utils
> feat: allow to pass parseOption to CLI class

- OPTIONS.md
Docs update
N/A
Yup
**Summary**
Remove redundant command entires.
Nope
#2298
> docs: remove redundant command entries

- packages/generators/__tests__/__snapshots__/init-generator.test.ts.snap
- packages/generators/__tests__/init-generator.test.ts
- packages/generators/src/init-generator.ts
- test/init/language/css/init-language-css.test.js
bugfix
Updated existing test suite.
N/A
**Summary**
Do not use `style-loader` and `mini-css-extract-plugin` together in the loaders chain.
closes #2308 
Nope
N/A
> fix(init): remove style-loader from the loader chain

- README.md
- packages/README.md
Docs update
N/A
Yup
**Summary**
`generate-plugin` and `generate-loader` packages were unioned into the `generators` package; however, docs had outdated references.
Nope
N/A
> docs: fix broken references

- .github/workflows/nodejs.yml
- package.json
chore
No
No
**Summary**
remove duplicate build script
No
No
> chore: remove duplicate build script

- .eslintignore
- .prettierignore
- OPTIONS.md
- packages/configtest/package.json
- packages/configtest/src/index.ts
- packages/configtest/tsconfig.json
- packages/webpack-cli/README.md
- packages/webpack-cli/lib/webpack-cli.js
- packages/webpack-cli/package.json
- test/configtest/configtest.test.js
- test/configtest/error.config.js
- test/configtest/src/index.js
- test/configtest/syntax-error.config.js
- test/configtest/webpack.config.js
- test/help/help.test.js
- tsconfig.json
feature
WIP
WIP
**Summary**
Syntax - `webpack configtest <path-to-config>`
No
Fixes https://github.com/webpack/webpack-cli/issues/803
> feat: implement new configtest command

- packages/generators/__tests__/__snapshots__/init-generator.test.ts.snap
- packages/generators/__tests__/init-generator.test.ts
- packages/generators/src/init-generator.ts
- test/init/auto/init-auto.test.js
- test/init/force/init-force.test.js
- test/init/generation-path/init-generation-path.test.js
- test/init/generator/init-inquirer.test.js
fix
yes
NA
**Summary**
- Fixed the default logic in the init generator which was broken
- Removed pasting sw.js since workbox plugin does that already in webpack build pipeline, no need to copy manually.
No
> fix: improve init generator

- packages/webpack-cli/lib/webpack-cli.js
bugfix
Nope
N/A
**Summary**
Currently, the package name that shows up while prompting for installation is the same as the argument supplied as part of `process.argv`. However, this would be misleading if the user supplies the alias or the `loader`/`plugin` command (`generators`).
https://github.com/webpack/webpack-cli/blob/767fe6b4b4d4980b5b5cf8fd5dafb0aa84465625/packages/webpack-cli/lib/webpack-cli.js#L359-L361
```bash
$ webpack loader
```
Nope
N/A
> fix: show exact package name while prompting for installation

- packages/generators/init-template/sw.js
- packages/generators/src/init-generator.ts
chore
yes
yes
**Summary**
- removes default sw which is no longer used, instead we injest sw using workbox plugin in webpack build chain
no
no
> fix: use worker from plugin and remove default

- .github/workflows/nodejs.yml
- packages/serve/src/index.ts
- packages/webpack-cli/__tests__/resolveConfig/resolveConfig.test.js
- packages/webpack-cli/lib/webpack-cli.js
- test/config/type/function-with-argv/function-with-argv.test.js
- test/serve/basic/function-with-argv.config.js
- test/serve/basic/function-with-env.config.js
- test/serve/basic/serve-basic.test.js
- yarn.lock
bugfix
Yes
No need
**Summary**
fixes #2962 (I think it was fixed, but no, so let's fix)
No
No
> fix: pass all `argv` to configurations when `serve` command used

- packages/webpack-cli/lib/webpack-cli.js
- packages/webpack-cli/package.json
- yarn.lock
chore
Existing
No
**Summary**
update webpack-merge
No
No
> chore: update `webpack-merge`

- OPTIONS.md
- packages/webpack-cli/lib/webpack-cli.js
- test/build/basic/basic.test.js
- test/help/help.test.js
feature
Yes
Yes
**Summary**
allow to show help information for options 
No
fixes #1463
> feat: allow to use `help` command to show option information

- OPTIONS.md
- packages/configtest/package.json
- packages/configtest/src/index.ts
- packages/webpack-cli/README.md
enhancement
NA
Yes
**Summary**
improve description for `configtest` command.
No
https://github.com/webpack/webpack.js.org/pull/4450#discussion_r560597020
> fix: improve description for `configtest` command

- packages/serve/src/index.ts
- packages/webpack-cli/lib/webpack-cli.js
- test/serve/basic/serve-basic.test.js
- test/serve/basic/watch.config.js
- test/watch/basic/basic.test.js
- test/watch/watch-variable/src/index.js
- test/watch/watch-variable/watch-variable.test.js
- test/watch/watch-variable/webpack.config.js
fix
yes
no
**Summary**
fixes https://github.com/webpack/webpack-cli/issues/2370
show a warning if `serve` and `--watch` are used together
No
I will work on removing `--watch` & `--no-watch` options from `serve` help output in next PR.
> fix: show a warning if serve and `--watch` are used together

- README.md
- packages/README.md
Docs
N/A
Yup
**Summary**
- Remove references to the `utils` package, which was unioned to `generators`.
- Add a reference to the `configtest` package.
Nope
N/A
> docs: remove references to non-existent packages

- .github/CONTRIBUTING.md
docs
No need
Yes
**Summary**
Update commit types
No
no
> docs: update

- test/merge/config/1.js
- test/merge/config/2.js
- test/merge/config/3.js
- test/merge/config/first-entry.js
- test/merge/config/merge-config.test.js
- test/merge/config/second-entry.js
- test/merge/config/some_entry.js
- test/merge/config/third-entry.js
test
YES
NO
**Summary**
improve existing tests and add one more case for merging more than two configs.
No
No
> test: improve tests for --merge

- packages/generators/src/index.ts
- test/loader/loader.test.js
- test/plugin/plugin.test.js
feat
Not needed, already present
No
**Summary**
Enforced use of process.cwd() as default `output-path`
No
Part of Roadmap
> test: default loader name and plugin name

- packages/webpack-cli/lib/webpack-cli.js
- test/node-env/auto-mode.config.js
- test/node-env/node-env.test.js
- test/node-env/src/index.js
- test/node-env/webpack.config.js
feature
YES WIP
YES
**Summary**
fixes https://github.com/webpack/webpack-cli/issues/2362
NO
> feat: add --node-env flag

- packages/generators/init-template/package.json.js
- packages/generators/src/init-generator.ts
- test/init/auto/init-auto.test.js
- test/init/generation-path/init-generation-path.test.js
- test/init/generator/init-inquirer.test.js
- test/init/language/css/init-language-css.test.js
- test/init/language/js/init-language-js.test.js
- test/init/multipleEntries/init-multipleEntries.test.js
patch
Update existing test suite.
Nope
**Summary**
https://github.com/webpack/webpack-cli/blob/dd0f1632217a40c04c19af973ef3d696cc595d21/packages/generators/init-template/package.json.js#L6
The current implementation adds a `start` script that invokes `webpack-dev-server`. However, the intended way would be to have `webpack serve` instead.
Adds a `serve` script if the user opts for `webpack-dev-server`.
Nope
N/A
> fix: add serve script if opted for WDS with init

- .github/workflows/nodejs.yml
- package.json
- packages/webpack-cli/__tests__/applyCLIPlugin.test.js
- packages/webpack-cli/lib/plugins/CLIPlugin.js
- packages/webpack-cli/lib/webpack-cli.js
- test/build/basic/basic.test.js
- test/build/basic/log.config.js
- test/core-flags/infrastructure-logging.test.js
- test/json/json.test.js
- test/serve/basic/log.config.js
- test/serve/basic/serve-basic.test.js
- test/watch/basic/basic.test.js
- test/watch/basic/log.config.js
feat
yes
NA
**Summary**
- Displays the used config when infra logging level is log, helpful to know which config is in use when there are multiple
No
> feat: display used config path when logging level=log 

- README.md
- packages/README.md
Docs update
N/A
Yup
**Summary**
Remove references to the `init` package, which was unioned to `generators`.
Nope
#2393
> docs: remove references to init package

- packages/webpack-cli/lib/webpack-cli.js
- smoketests/index.js
- smoketests/missing-command-help/generator.test.js
bugfix
WIP on tests
No
**Summary**
Fixes #2479 
No
No
> fix: improve error message

- OPTIONS.md
- packages/webpack-cli/README.md
- packages/webpack-cli/lib/webpack-cli.js
- test/hot/hot-flag.test.js
feature
yes, serve tests can be added after upgrade to v4.
Yes
**Summary**
Allow string value for `--hot`, `--hot=only` is accepted by `webpack-dev-server`
No
No
> feat: allow string value for '--hot'

- smoketests/helpers.js
- smoketests/missing-command-packages/generator.test.js
- smoketests/missing-command-packages/info.test.js
- smoketests/missing-command-packages/serve.test.js
- smoketests/missing-packages/webpack-dev-server.test.js
- smoketests/missing-packages/webpack.test.js
refactoring
Update smoke tests
Nope
**Summary**
This PR aims at refactoring the smoke test suite by introducing helpers.
#2493
Nope
N/A
> refactor: leverage helpers for smoketests

- packages/webpack-cli/lib/webpack-cli.js
minor comment change, currently tells opposite
N/A
N/A
**Summary**
Comment previously told that `['webpack.config', '.webpack/webpack.config', '.webpack/webpackfile']` this is priority in the increasing order for location of configuration, but actually it is in decreasing order. First one being highest priority.
No
N/A
> fix: comment on config resolution priority

- test/help/help.test.js
tests
yes
no
**Summary**
test assertions seem to be wrong for aliases.
https://github.com/webpack/webpack-cli/blob/e71deff24023cc8242f71b858a8ace46612a7312/test/help/help.test.js#L215
expected - `webpack c` ❌ 
expected - `webpack init|c` ✅
No
https://github.com/webpack/webpack-cli/actions/runs/670671448
> test: fix help tests

- smoketests/helpers.js
- smoketests/index.js
- smoketests/missing-command-packages/configtest.test.js
- smoketests/missing-command-packages/generator.test.js
- smoketests/missing-command-packages/info.test.js
- smoketests/missing-command-packages/serve.test.js
- smoketests/missing-packages/webpack-bundle-analyzer.test.js
- smoketests/missing-packages/webpack-dev-server.test.js
- smoketests/missing-packages/webpack.test.js
test, refactor
yes
No
**Summary**
Refactor code, follow DRY code.
No
No
> test: refactor smoketests

- OPTIONS.md
- README.md
- packages/generators/src/index.ts
- packages/webpack-cli/README.md
fix description
No
Yes
**Summary**
initialize a new `project`
No
No
> fix: description for `init` command

- packages/webpack-cli/bin/cli.js
- test/build/import-local/import-local.test.js
feat
Yes
**Summary**
Add env var to skip import-local
No
Fix #2543
> feat: add env var to skip local import

- packages/generators/init-template/default/package.json.js
- test/init/__snapshots__/init.test.js.snap.webpack4
- test/init/__snapshots__/init.test.js.snap.webpack5
Enhancement
Yes
N/A
**Summary**
https://github.com/webpack/webpack-cli/pull/2536#discussion_r598864385
Nope
N/A
> feat: add additional scripts to init template

- packages/webpack-cli/lib/webpack-cli.js
- test/build/custom-webpack/custom-webpack.js
- test/build/custom-webpack/custom-webpack.test.js
- test/build/custom-webpack/src/index.js
- test/build/custom-webpack/webpack.config.js
feature
Yes
will send PR to documentation
**Summary**
FIxes #2551 
```
"webpack": "^4.0.0",
"webpack5": "npm:webpack@^5.28.0",
"webpack-cli": "^4.5.0"
```
`webpack` - run webpack 4
`WEBPACK_PACKAGE=webpack5` - run webpack 5
No
No
> feat: add `WEBPACK_PACKAGE` env var to use custom `webpack` package

- packages/webpack-cli/lib/plugins/CLIPlugin.js
- test/build/start-finish-force-log/src/index.js
- test/build/start-finish-force-log/start-finish-force-log.test.js
- test/build/start-finish-force-log/webpack.config.array.js
- test/build/start-finish-force-log/webpack.config.js
feat
wip
NA
**Summary**
Add a env var to force compilation log
No
> feat: add flag to force start finish log

- test/init/init.test.js
Test update
Update test suite.
N/A
**Summary**
This PR aims at adding a test case to ensure the behavior of `init-generator` throwing if the current path is non-writable.
Nope
#2569
> test: init generator throws if the path is not writable

- test/build/config-format/typescript-esnext/main.ts
- test/build/config-format/typescript-esnext/package.json
- test/build/config-format/typescript-esnext/tsconfig.json
- test/build/config-format/typescript-esnext/typescript.test.js
- test/build/config-format/typescript-esnext/webpack.config.ts
test
Yes
NA
**Summary**
Add test for ts esm
no
Fix https://github.com/webpack/webpack-cli/issues/2458
> test: ts esnext

- OPTIONS.md
- packages/generators/src/index.ts
- packages/webpack-cli/README.md
- test/help/__snapshots__/help.test.js.snap.webpack4
- test/help/__snapshots__/help.test.js.snap.webpack5
- test/help/help.test.js
patch
Update test snapshots
Yes
**Summary**
#2576
Nope
N/A
> fix: update usage info

- packages/serve/src/startDevServer.ts
fix
NA
NA
**Summary**
we removed `client.port` in https://github.com/webpack/webpack-dev-server/pull/3181
Refer https://github.com/webpack/webpack-dev-server/pull/3181#issuecomment-818921391
No
No
> fix(serve): do not set port for modern client

- packages/webpack-cli/lib/webpack-cli.js
- test/build/config/type/function-with-env/function-with-env.test.js
- test/build/config/type/function-with-env/webpack.config.js
- test/help/__snapshots__/help.test.js.snap.webpack4
- test/help/__snapshots__/help.test.js.snap.webpack5
- test/help/help.test.js
bugfix
Yes
will add an example in webpack.js.org after merge.
**Summary**
Fixes #2642 
Maybe
No
> fix: improve parsing of `--env` flag

- packages/serve/src/startDevServer.ts
bugfix/refactor
Will be added with `webpack-dev-server@beta`
No need
**Summary**
we don't need to search free port before start webpack dev server, v4 do it automatically, so let's simplify it and avoid unnecessary code (also remove `dev.publicPath`, this option doesn't exist in webpack dev server v3)
No
No
> fix: avoid unnecessary searching port

- packages/generators/src/index.ts
- packages/webpack-cli/lib/webpack-cli.js
- test/help/__snapshots__/help.test.js.snap.devServer3.webpack4
- test/help/__snapshots__/help.test.js.snap.devServer3.webpack5
- test/help/__snapshots__/help.test.js.snap.devServer4.webpack4
- test/help/__snapshots__/help.test.js.snap.devServer4.webpack5
added support arguments description
tests updated
**Summary**
added support the [arguments description](https://github.com/tj/commander.js#specify-the-argument-syntax)
No
No
> feat: added support arguments description

- packages/serve/src/index.ts
fix/feat/refactor?
tested manually, no way to test rn
no need I think
**Summary**
we're migrating all flags to a single format, core/cli built in/server flags so this is to handle backward compatibility with dev server flags in migration to new format, once this is released we can go ahead with the migration
Ref https://github.com/webpack/webpack-dev-server/pull/3213
no
> refactor: backward compatible flags for dev server

- packages/generators/src/addon-generator.ts
- packages/generators/src/loader-generator.ts
- packages/generators/src/plugin-generator.ts
refactoring
Already present
N/A
**Summary**
https://github.com/webpack/webpack-cli/blob/65ae77d98e918ea5907de89c9c87b797f57f1b2f/packages/generators/src/addon-generator.ts#L30
Directory content is inferred from the `templateDir` argument. Hence, it is not necessary to explicitly specify the template files.
No
N/A
> refactor(generators): remove extraneous args to addon-generator

- README.md
docs
NA
NA
**Summary**
- we don't have scaffold guide anymore
no
https://github.com/webpack/webpack-cli/pull/2677
> docs: remove scaffold guide

- packages/webpack-cli/README.md
Docs
NA
Yes
**Summary**
Add more useful information.
No
No
> docs: add more information

- package.json
- yarn.lock
update deps + regenerate lock file
No need
No need
**Summary**
No need
No
No need
> chore(deps): update

- packages/serve/src/startDevServer.ts
- packages/webpack-cli/lib/webpack-cli.js
- test/plugin/plugin.test.js
refactor
Existing
No
**Summary**
Unify code, we should avoid using `require` for external packages due Node.js is out and we some modules can migrate on ES. Also reduce duplicate of code and error handling
No
No
> refactor: loading packages

- jest.config.js
- setupTest.js
- test/api/CLI.test.js
chore
No
No
**Summary**
Migrate to `jest-circus` which is the default test runner as of `jest` v27
No
No
> chore: migrate to `jest-circus`

- .github/workflows/nodejs.yml
- test/build/entry/scss/package.json
chore
NA
NA
**Summary**
run tests on node 16
shouldn't 
> fix: add node 16 to CI

- packages/webpack-cli/lib/utils/package-exists.js
- packages/webpack-cli/lib/utils/prompt-installation.js
bugfix
Hard to add, manually tested
No need
**Summary**
fixes #2716
No
@webpack/cli-team 
- we need backport this solution, in `webpack-dev-server` and `webpack` itself, just replace `require.resolve` on this function
- also we need small refactor, `promptInstallation` should not return something, only install package
> fix: not found module after ask installation

- packages/serve/src/index.ts
- test/serve/serve-variable/webpack.config.js
feature
Exist, but only work after merge https://github.com/webpack/webpack-dev-server/pull/3325
No need
**Summary**
New API for CLI options
No
I think we should refactor `serve` and put `startDevServer.ts` in `index.ts` to avoid extra `require` (but it is not problem, because `require` is cachable). Also we will avoid a lot of `for`/`reduce`/`forEach` after https://github.com/webpack/webpack-cli/pull/2626, but I want postpone it right now, focus on webpack-dev-server
> feat: new CLI options API for serve

- packages/serve/src/index.ts
bugfix, my mistake, check will be bad for webpack v4 and webpack-dev-server the next version
Latest, but we will have these test in webpack-dev-server
No need
**Summary**
Fix new CLI API
No
I will do the new patch release after merge
> fix: broken serve with new CLI API

- packages/generators/src/init-generator.ts
- packages/webpack-cli/lib/utils/get-available-installers.js
- packages/webpack-cli/lib/utils/index.js
- test/init/init.test.js
Feature
Update test suite
N/A
**Summary**
#2768
No
N/A
> feat(init-generator): add ability to specify a package manager of choice

- packages/generators/src/addon-generator.ts
- test/loader/loader.test.js
- test/plugin/plugin.test.js
Feature
Update test suite
N/A
**Summary**
closes #2768
No
N/A
> feat(addon-generator): add prompt to select a package manager of choice

- test/loader/loader.test.js
- test/plugin/plugin.test.js
Test update
This PR aims at updating the test suite.
N/A
**Summary**
Currently, a couple of integration test assertions associated with the `loader` and `plugin` commands get skipped.
https://github.com/webpack/webpack-cli/blob/9c6b341fd84e03606c9a9558711238f0863bd56f/test/loader/loader.test.js#L39-L42
This PR aims at fixing up this behavior.
No
N/A
> test: enable skipped test assertions

- packages/webpack-cli/lib/webpack-cli.js
- test/api/CLI.test.js
- test/api/__snapshots__/CLI.test.js.snap.webpack4
- test/api/__snapshots__/CLI.test.js.snap.webpack5
fix
Manual testing
**Summary**
show default value in help output if provided in the `option` object.
None
No
> fix: show default value in help output if available

- packages/serve/src/index.ts
fix
Already present
No
**Summary**
Use the latest API, otherwise `npx webpack serve` will show a deprecation warning like:
No
No
> fix: update `webpack-dev-server` usage

- packages/webpack-cli/lib/webpack-cli.js
- test/build/config/top-multi-compilers-options/index.js
- test/build/config/top-multi-compilers-options/top-multi-compilers-options.test.js
- test/build/config/top-multi-compilers-options/webpack.config.js
bugfix
yes
No
**Summary**
fixes #2873
No
We should refactor our logic for multiple `--config`, ideally I think we should run `merge` when multiple configurations provided, but it is breaking change and should be solved for the next major release
> fix: support top multi compiler options

- OPTIONS.md
docs
No
yes
**Summary**
update docs
No
No
> docs: update cli options

- packages/serve/src/index.ts
bugfix
existing
No need
**Summary**
due https://github.com/webpack/webpack-dev-server/pull/3608
No
No
> fix: using new dev server API for v4

- packages/configtest/src/index.ts
- packages/generators/src/index.ts
- packages/info/src/index.ts
- packages/serve/src/index.ts
- packages/webpack-cli/bin/cli.js
- packages/webpack-cli/lib/utils/prompt-installation.js
- packages/webpack-cli/lib/webpack-cli.js
- smoketests/helpers.js
- smoketests/index.js
- smoketests/missing-packages/webpack-dev-server.test.js
- smoketests/missing-packages/webpack.test.js
- test/build/custom-webpack/custom-webpack.test.js
- test/help/__snapshots__/help.test.js.snap.devServer3.webpack4
- test/help/__snapshots__/help.test.js.snap.devServer3.webpack5
- test/help/__snapshots__/help.test.js.snap.devServer4.webpack4
- test/help/__snapshots__/help.test.js.snap.devServer4.webpack5
- test/version/__snapshots__/version.test.js.snap.webpack4
- test/version/__snapshots__/version.test.js.snap.webpack5
- yarn.lock
feature
Yes, some tests
No need
**Summary**
Allow to run `npx webpack-cli info` without `webpack` installation
No
due `v8-compile-cache` has bug with `import()`, after this refactor webpack can use `import()` to load ECMA modules, it is great fix
> feat: allow to run commands not requiring webpack without webpack installation

- packages/webpack-cli/lib/webpack-cli.js
- test/build/config/no-code/no-code.test.js
- test/build/config/no-code/src/index.js
- test/build/config/undefined-default/src/index.js
- test/build/config/undefined-default/undefined-default.test.js
- test/build/config/undefined-default/webpack.config.js
- test/build/config/undefined/src/index.js
- test/build/config/undefined/undefined.test.js
- test/build/config/undefined/webpack.config.js
fix and test
Yup, did in TDD fashion.
Not required.
**Summary**
Treat `undefined` configuration as a case for `zero-config`
Nope.
/cc @alexander-akait 
> when we have `webpack.config.js`  without `module.exports`  or `export`  we don't work, but no exports means zero configuration and should work
> fix: handle undefined configuration export

- packages/serve/src/index.ts
Fix
Open to suggestions for testing this.
N/A
**Summary**
This fixes a regression that we noticed when updating to `webpack-cli@4.7.2`. We are still on `webpack-dev-server@3.11.2` which allows using `null` or `0` to automatically use a free port. In our case we are setting `port: 0` and it was causing this error:
```
Error: listen EADDRINUSE: address already in use 127.0.0.1:8080
```
If `webpack-cli` still supports `webpack-dev-server@3.11.2` it seems like it shouldn't prevent passing `null` or `0` as an option to `port`. Our current workaround is using the string `'0'`, which is not falsy.
No
**Other …
> fix: allow falsy values for "port" option

- test/build/config/absent/config-absent.test.js
- test/build/config/absent/webpack.config-absent.js
- test/build/config/basic/basic-config.test.js
- test/build/config/defaults/basic-config/default-js-config.test.js
- test/build/config/defaults/cjs-config/default-cjs-config.test.js
- test/build/config/defaults/dot-webpack-directory-webpackfile/dot-webpack-webpackfile.test.js
- test/build/config/defaults/dot-webpack-directory/dot-webpack-config.test.js
- test/build/config/defaults/mjs-config/default-mjs-config.test.js
- test/build/config/defaults/with-mode/default-config-with-mode.test.js
- test/build/config/empty-array/empty-array.test.js
- test/build/config/empty-function/empty-function.test.js
- test/build/config/empty-promise/empty-promise.test.js
- test/build/config/empty/empty.test.js
- test/build/config/error-array/config-array-error.test.js
- test/build/config/error-commonjs/config-error.test.js
- test/build/config/function/functional-config.test.js
- test/build/config/invalid-export/invalid-export.test.js
- test/build/config/invalid-path/a.js
- test/build/config/invalid-path/invalid-path.test.js
- test/build/config/invalid-path/webpack.config.js
- test/build/config/multiple-with-one-compilation/multiple-with-one-compilation.test.js
- test/build/config/multiple/multiple-config.test.js
- test/build/config/no-code/no-code.test.js
- test/build/config/no-config-array/no-config-array.test.js
- test/build/config/no-config-object/no-config-object.test.js
refactor
Yup
Not needed,
**Summary**
There are various grammatical mistakes as well as non standard descriptions.
Some cases also have redundant files.
Nope
Discussed in #2930
> refactor: config tests

- packages/generators/package.json
bugfix
manually tests
yes
/cc @webpack/cli-team we need update our docs, for `init` we should always use `npx webpack-cli init`
**Summary**
It is fast fix, in future we should create rename `init` to `create-webpack-app` and use `npx create-webpack-app`
No
Partial fix https://github.com/webpack/webpack-cli/issues/2944
> fix: npx init

- OPTIONS.md
- package.json
- yarn.lock
docs
No
Yes
**Summary**
update webpack options.
None
No
> docs: update webpack options

- packages/webpack-cli/lib/webpack-cli.js
bugfix
No
No
**Summary**
For https://github.com/webpack/webpack-dev-server/pull/4216
No
Internal usage.
> fix: respect `negatedDescription` for flags from schema

- packages/webpack-cli/package.json
- packages/webpack-cli/src/webpack-cli.ts
- smoketests/helpers.js
- test/api/do-install.test.js
- test/api/get-default-package-manager.test.js
Refactor: use a simple child process instead of a shell and replace `execa` with `cross-spawn`.
No, I only replaced the `execa` mocks with `cross-spawn` mocks, as the functionality should be identical as before.
I've tested `webpack init` on my local machine.
**Summary**
Executing a shell is less performant, less secure and less cross-platform, according to both the [execa](https://github.com/sindresorhus/execa#shell) and [cross-spawn](https://github.com/moxystudio/node-cross-spawn#using-optionsshell-as-an-alternative-to-cross-spawn) documentation.
Replacing `execa` with `cross-spawn` removes 9 dependencies on a production install:
- execa
- get-stream
- human-signals
- is-stream
- mimic-fn
- …
> refactor(webpack-cli): don't spawn needless shells and replace execa with cross-spawn

- packages/webpack-cli/src/webpack-cli.ts
- smoketests/helpers.js
This PR contains a:
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
None
> chore: replace deprecated String.prototype.substr()

- packages/webpack-cli/src/plugins/CLIPlugin.ts
Bugfix
No, seemed too niche for a test case but happy to add one with a bit of instruction (namely whether `test/plugin/plugin.test.js` is the correct spot)
Not relevant, updates a verbose log
**Summary**
Fixes https://github.com/webpack/webpack-cli/issues/3197
We need to pass the timestamp in milliseconds to the date constructor, this code was assuming that changeTime was in seconds and needed to be multiplied by 1000 to get milliseconds but it is already in milliseconds.
This led to the constructed date being incorrect.
|Before|After|
|---|---|
|<img src="https://user-images.githubusercontent.com/3004111/162455034-f94baef3-3468-41b4-82db-911351e08336. …
> Bugfix in calculation of modified time of files in watch mode

- packages/generators/init-template/react/src/index.js.tpl
- packages/generators/init-template/react/src/index.tsx.tpl
- packages/generators/src/handlers/react.ts
I see that there is a react template support being added so used `createRoot` instead of `render` as per React 18.
> fix: consider using createroot instead of render

- .github/workflows/nodejs.yml
- package.json
chore.
Drop node v12 as suggested by @alexander-akait 
Nope
Nope
**Summary**
> chore: drop node version 12

- .cspell.json
- smoketests/index.js
feature
Yes
No Need
**Summary**
It is difficult to detect which test passed and which one failed on CI. Added a summary at the end of run to make it easier.
Nope
Nope
> feat: add summary to smoketests

- OPTIONS.md
- README.md
- packages/webpack-cli/README.md
- packages/webpack-cli/package.json
- packages/webpack-cli/src/webpack-cli.ts
- test/help/__snapshots__/help.test.js.snap.devServer3.webpack4
- test/help/__snapshots__/help.test.js.snap.devServer3.webpack5
- test/help/__snapshots__/help.test.js.snap.devServer4.webpack4
- test/help/__snapshots__/help.test.js.snap.devServer4.webpack5
- test/help/help.test.js
- test/version/__snapshots__/version.test.js.snap.webpack4
- test/version/__snapshots__/version.test.js.snap.webpack5
- test/version/version.test.js
refactor
Removed tests.
Yes.
**Summary**
remove `migrate` command.
BREAKING CHANGE: the `migrate` command was removed without replacement, please use migration guide.
No
> refactor!: remove `migrate` command

- OPTIONS.md
- packages/webpack-cli/src/types.ts
- packages/webpack-cli/src/webpack-cli.ts
- test/build/build-warnings/warnings.test.js
feature
Yes
Done
**Summary**
adds `--fail-on-warnings` option
closes #3315 
No
#3315
> feat: failOnWarnings option

- .cspell.json
- .github/workflows/nodejs.yml
- packages/configtest/package.json
- packages/generators/package.json
- packages/info/package.json
- packages/serve/package.json
- packages/serve/src/index.ts
- packages/webpack-cli/package.json
- test/build/cache/cache.test.js
- test/build/colors/colors.test.js
- test/build/config/defaults/basic-config/default-js-config.test.js
- test/build/config/defaults/cjs-config/default-cjs-config.test.js
- test/build/config/defaults/mjs-config/default-mjs-config.test.js
- test/build/config/top-multi-compilers-options/top-multi-compilers-options.test.js
- test/build/env/array/array-env.test.js
- test/build/env/object/object-env.test.js
- test/build/error/invalid-schema/invalid-schema.test.js
- test/build/mode/mode-single-arg/mode-single-arg.test.js
- test/build/progress/progress-flag.test.js
- test/build/start-finish-force-log/start-finish-force-log.test.js
- test/build/stats/config-no/no-stats-with-config.test.js
- test/build/stats/config/stats.test.js
- test/build/stats/flags/stats.test.js
- test/build/target/flag-test/__snapshots__/target-flag.test.js.snap.webpack5
- test/build/target/flag-test/target-flag.test.js
- test/help/help.test.js
- test/serve/basic/serve-basic.test.js
- test/utils/test-utils.js
- test/watch/basic/basic.test.js
- test/watch/watch-variable/watch-variable.test.js
refactor
Removed tests for webpack 4.
No.
**Summary**
Drop webpack v4 from tests, packages, and CI.
Yes.
Yes.
> refactor: drop webpack v4 from tests, packages, and CI

- packages/webpack-cli/src/index.ts
Fix
Not needed.
No.
**Summary**
Follow up https://github.com/webpack/webpack-cli/pull/3291
Resolve TODO. Remove the redundant `utils` export.
Yes.
No
> fix: remove the redundant `utils` export

- test/build/target/flag-test/__snapshots__/target-flag.test.js.snap.webpack5
- test/build/target/flag-test/multiple-target.config.js
- test/build/target/flag-test/target-flag.test.js
- test/build/target/flag-test/target.web.config.js
test
Yes.
No
**Summary**
add a case for the use of `--target-reset` with multiple targets.
No
No
> test: add case for `--target-reset` with multiple targets

- OPTIONS.md
- package.json
- packages/webpack-cli/src/types.ts
- packages/webpack-cli/src/webpack-cli.ts
- test/build/config-format/disable-interpret/disable-interpret.test.js
- test/build/config-format/disable-interpret/main.ts
- test/build/config-format/disable-interpret/tsconfig.json
- test/build/config-format/disable-interpret/webpack.config.ts
- test/build/config-format/typescript/typescript.test.js
- test/help/__snapshots__/help.test.js.snap.devServer3.webpack4
- test/help/__snapshots__/help.test.js.snap.devServer3.webpack5
- test/help/__snapshots__/help.test.js.snap.devServer4.webpack4
- test/help/__snapshots__/help.test.js.snap.devServer4.webpack5
A kind of bugfix.
Yes.
Users can check this option with the `webpack --help`.
**Summary**
Fixed https://github.com/webpack/webpack-cli/issues/3195
No.
> fix(webpack-cli): add an option for preventing interpret

- packages/webpack-cli/src/webpack-cli.ts
- test/help/__snapshots__/help.test.js.snap.devServer4.webpack5
bugfix
Yes. Updated snapshots.
No.
**Summary**
webpack-cli offers many additional flags like (`--analyze`, `--json`, `--env`, etc) than pure configuration option (like `--stats`, `--target`).
The minimum help output should contain all the additional feature flags webpack-cli offers for better visibility, It's easy to miss these flags in the verbose help output.
No
NO
> fix: show all CLI specific flags in the minimum help output

- packages/webpack-cli/src/webpack-cli.ts
- test/help/__snapshots__/help.test.js.snap.devServer4.webpack5
fix
Yes, updated snapshots.
No.
**Summary**
Improve description of the `--disable-interpret` option
No
No
> fix: improve description of the `--disable-interpret` option

- packages/generators/package.json
- packages/generators/src/addon-generator.ts
- packages/generators/src/init-generator.ts
- test/init/init.test.js
- yarn.lock
chore
No.
No.
**Summary**
update `yeoman-generator` to v5.
No.
No/
> chore: update `yeoman-generator` to v5

- package.json
- yarn.lock
deps update
No.
**Summary**
Fix https://github.com/webpack/webpack-cli/pull/3448
No
No
> chore: update lerna to v6

- .github/CONTRIBUTING.md
docs.
No.
Yes.
**Summary**
Add [CLA Link ](https://easycla.lfx.linuxfoundation.org/#/?version=2)
No
No
> docs: add CLA link

- packages/webpack-cli/package.json
- packages/webpack-cli/src/types.ts
- packages/webpack-cli/src/webpack-cli.ts
- test/api/CLI.test.js
- test/build/unknown/__snapshots__/unknown.test.js.snap.webpack5
- yarn.lock
feature
Updated snapshots and tests.
No
**Summary**
- Update commander to v9
- Commander v9 provides suggestions for unknown options by default. Removed our custom logic for suggestion options and kept the code for suggesting commands.
- Ideally, the commander should export its [API for suggestSimilar](https://github.com/tj/commander.js/blob/master/lib/suggestSimilar.js#L95)
No
No
> feat: update commander to v9

- CHANGELOG.md
- packages/configtest/CHANGELOG.md
- packages/configtest/package.json
- packages/generators/CHANGELOG.md
- packages/generators/package.json
- packages/info/CHANGELOG.md
- packages/info/package.json
- packages/serve/CHANGELOG.md
- packages/serve/package.json
- packages/webpack-cli/CHANGELOG.md
- packages/webpack-cli/package.json
- packages/webpack-cli/src/webpack-cli.ts
chore + docs
No need
No
**Summary**
Changelog and versions
This no, but it is about changes
prepare changelog for release + need to fix `--entry` option
> chore(release): 5.0.0

- README.md
Docs
N/A
Yea
**Summary**
Adds pnpm line
N/A
N/A
> docs: add pnpm example

- packages/webpack-cli/src/webpack-cli.ts
Two improvements:
- Try to load popular configuration first - less fs calls
- lazy loading `envinfo`, you don't need it when you build or serve
No need
No
**Summary**
No
no
> fix(perf): improve startup time

- packages/webpack-cli/package.json
- yarn.lock
bump before release to check everything
No need
No need
**Summary**
No need
No
no
> chore(deps): bump

- packages/serve/src/index.ts
- packages/webpack-cli/src/types.ts
- packages/webpack-cli/src/webpack-cli.ts
- test/serve/basic/__snapshots__/serve-basic.test.js.snap.devServer4.webpack5
- test/watch/bail/bail.test.js
- test/watch/basic/basic.test.js
- test/watch/basic/no-watch.config.js
~~Avoid validation of our arguments from command line, i.e. when you have `webpack --stats invalid`~~
Update existing
No need
**Summary**
~~Webpack **always** validates provided configurations, when we have `webpack --stats invalid`, we just set `stats` to `"invalid"` value and now try to validate it, but I don't see any reasons to spend time on it, because when we pass it to `webpack` it will be validated again, so now we skip a one extra validation~~
We can't do it
No
fixes https://github.com/webpack/webpack-cli/pull/2626/
> perf: simplify logic, reduce extra loops and perf

- packages/serve/src/index.ts
- packages/webpack-cli/src/types.ts
- packages/webpack-cli/src/webpack-cli.ts
- test/serve/basic/__snapshots__/serve-basic.test.js.snap.devServer4.webpack5
- test/serve/basic/serve-basic.test.js
- test/watch/basic/basic.config.js
- test/watch/basic/basic.test.js
bugfix
Yes
No need
**Summary**
fixes #3778
No, but now we just print a warning about using `watch` with dev server, but also we avoid extra loop, so our startup time will be faster
> fix: false positive watch warning

- .github/workflows/nodejs.yml
- package.json
- test/build/config-format/typescript-esnext/package.json
- test/build/config-format/typescript-esnext/typescript.test.js
- yarn.lock
> ci: add Node.js v20

- packages/webpack-cli/src/webpack-cli.ts
bugfix
No
No
**Summary**
Fix https://github.com/webpack/webpack-cli/pull/3161
No
No
> fix: improve check for custom webpack-dev-server package existance

- .gitattributes
Currently, the `.gitattributes` file canonicalizes line endings for all files since all repository files are text files. So, that's a perfect fit.
With #2862, however, a binary file was added to the repository: `webpack.png.tpl`. On Windows development machines, that file becomes inadvertently altered at checkout time due to `.gitattributes` configuration.
Now, with this pull request, the `.gitattributes` file is amended to exclude that particular file (and similar future `*.png.tpl` files) from line ending canonicalization.
No. Not necessary as this is a build environment change.
No.
> .gitattributes updated to ignore `png.tpl` files

- .github/workflows/nodejs.yml
- packages/webpack-cli/package.json
- packages/webpack-cli/src/webpack-cli.ts
- test/info/additional-package.test.js
- test/info/basic.test.js
- test/info/output.test.js
- test/version/additional-package.test.js
- test/version/basic.test.js
- test/version/output.test.js
- yarn.lock
feature
Yes
No
**Summary**
Fixes https://github.com/webpack/webpack-cli/pull/3072/
Add `pnpm` information
No
No
> feat: output pnpm version with `info`/`version` command

- packages/generators/init-template/default/webpack.configjs.tpl
- packages/generators/src/handlers/default.ts
- test/init/__snapshots__/init.test.js.snap.webpack5
Fixes #3990 
No
N/A
**Summary**
Allows images to be loaded in index.html
No
N/A
> feat: use html-loader to default template

- OPTIONS.md
- SERVE-OPTIONS-v4.md
- packages/webpack-cli/src/webpack-cli.ts
- test/help/__snapshots__/help.test.js.snap.devServer4.webpack5
bug fix
Yes.
Yes.
**Summary**
Don't show multiple `--extends` in the help output.
No
No
> fix: correct the minimum help output

- packages/generators/src/handlers/default.ts
- test/utils/test-utils.test.js
Fixes #3754
No
N/A
**Summary**
Doesnt override already set values in pkg.json
No
Might need to fix/add test for this.
> fix: dont override set pkg.json props

- packages/webpack-cli/src/webpack-cli.ts
fixes #2918 
fixes #2919
Existing
No need
**Summary**
gracefully shutting down, so hooks will be called and cache will not be broken
Also we need it for https://github.com/webpack-contrib/sass-loader/pull/1195
No
No
> fix: gracefully shutting down

- test/serve/basic/__snapshots__/serve-basic.test.js.snap.devServer4.webpack5
- test/serve/basic/__snapshots__/serve-basic.test.js.snap.devServer5.webpack5
- test/serve/basic/serve-basic.test.js
test stability due racing
No need
No need
**Summary**
In comment
No
No
> test: stability

- package.json
- packages/serve/src/index.ts
- packages/webpack-cli/src/webpack-cli.ts
- test/serve/basic/__snapshots__/serve-basic.test.js.snap.devServer4.webpack5
- test/serve/basic/__snapshots__/serve-basic.test.js.snap.devServer5.webpack5
- test/serve/basic/dev-server-false.multi.config.js
- test/serve/basic/serve-basic.test.js
- test/serve/basic/src/worker.js
- test/serve/serve-variable/__snapshots__/serve-variable.test.js.snap.devServer4.webpack5
- test/serve/serve-variable/__snapshots__/serve-variable.test.js.snap.devServer5.webpack5
- test/serve/serve-variable/serve-variable.test.js
- test/serve/with-custom-port/__snapshots__/serve-custom-config.test.js.snap.devServer4.webpack5
- test/serve/with-custom-port/__snapshots__/serve-custom-config.test.js.snap.devServer5.webpack5
- test/utils/test-utils.js
- yarn.lock
feature https://github.com/webpack/webpack-cli/pull/2947
WIP
WIP
**Summary**
WIP
WIP
WIP
> fix: support `devServer: false`

- .github/workflows/nodejs.yml
CI
No
No
**Summary**
- Currently, if we push commit to `next` it triggers two CI runs, one for `pull request synchronization` event and one for `push` event to `next` branch
- Removed `workflow_dispatch`, we don't use it.
No
No
> ci: avoid multiple CI runs when pushed to next

- packages/webpack-cli/package.json
- packages/webpack-cli/src/webpack-cli.ts
- test/api/CLI.test.js
- test/api/__snapshots__/CLI.test.js.snap.webpack5
- yarn.lock
deps
Updated existing tests
NA
**Summary**
- Update commandar.js to the latest version.
- [`addHelpCommand` usage is deprecated](https://github.com/tj/commander.js/blob/master/CHANGELOG.md#deprecated), hence migrated to the new `helpCommand` API.
No
No
> chore: update commander.js to v12

- packages/webpack-cli/src/webpack-cli.ts
- test/api/__snapshots__/CLI.test.js.snap.webpack5
- test/help/__snapshots__/help.test.js.snap.devServer5.webpack5
- test/help/help.test.js
bugfix
Yes
NA
**Summary**
No
No
> fix: improve help output for possible values

- test/utils/test-utils.js
chore
NA
NA
**Summary**
Remove old TODO
NA
NA
> chore: update normalizedStderr

- packages/create-webpack-app/package.json
- packages/create-webpack-app/src/generators/init/default.ts
- packages/create-webpack-app/src/generators/init/react.ts
- packages/create-webpack-app/src/generators/init/svelte.ts
- packages/create-webpack-app/src/generators/init/vue.ts
- packages/create-webpack-app/src/generators/loader/default.ts
- packages/create-webpack-app/src/generators/plugin/default.ts
- packages/create-webpack-app/src/index.ts
- packages/create-webpack-app/src/utils/generate-files.ts
- packages/create-webpack-app/src/utils/install-dependencies.ts
- packages/create-webpack-app/src/utils/logger.ts
- packages/create-webpack-app/src/utils/pkgInstallAction.ts
- test/create-webpack-app/init/__snapshots__/init.test.js.snap.webpack5
- test/create-webpack-app/init/init.test.js
bugfix
Existing
No need
**Summary**
Less size
No
No
> fix: reduce package size, avoid `*.d.ts`

- .github/workflows/nodejs.yml
[CI is failing on Node.js v23.6.1](https://github.com/webpack/webpack-cli/actions/runs/12941121060/job/36096847885?pr=4380#step:7:76), let's fix that separately. Meanwhile, pin version to unblock PR merges.
> ci: pin Node.js v23 to 23.5.0

- packages/webpack-cli/src/types.ts
bugfix
No
No
**Summary**
Fix the incorrect type.
No
> fix: correct `nodeEnv` type in `WebpackDevServerOptions`

- package.json
- packages/create-webpack-app/package.json
- packages/webpack-cli/package.json
- yarn.lock
Update cross-pawn to avoid high-severity issue
Updating cross-spawn version on webpack-cli and create-webpack-app to 7.0.6.
**Summary**
We use trivy to analyze high security dependencies in our projects. Webpack-cli package contains cross-spawn 7.0.3:
Specific vulnerability: CVE-2024-21538 (https://avd.aquasec.com/nvd/cve-2024-21538)
> feat: update-dependencies

- packages/create-webpack-app/templates/init/default/babel.config.json.tpl
Bug fix
Yes
No
**Summary**
This PR solves the issue #4419 
No
[Babel docs for plugin-syntax-dynamic-import mentions this plugin no longer needs to be used for @babel/core 7.8.0 and above](https://babeljs.io/docs/babel-plugin-syntax-DYNAMIC-Import), webpack-cli uses 7.25.2 as of now
> fix: #4419 removed plugin-syntax-dynamic-import

- packages/webpack-cli/src/webpack-cli.ts
- test/build/config/object-freeze-partial/index.test.js
- test/build/config/object-freeze-partial/src/index.js
- test/build/config/object-freeze-partial/webpack.config.js
- test/build/config/object-freeze/index.test.js
- test/build/config/object-freeze/src/index.js
- test/build/config/object-freeze/webpack.config.js
fixes https://github.com/webpack/webpack-cli/issues/4427
Yes
No need
**Summary**
Allow to use `Object.freeze({})` as a configuration
No
There is a small limitation, because we modify some default options in configuration for better DX, using `Object.freeze({})` prevent doing it, theoretically we can clone object, but it is has a bed perf and will don't work for all fields, also if you are using `Object.freeze({})` it means you really don't want to modify something, otherwise just don't use it
> fix: allow configuration freeze

- package.json
- packages/serve/src/index.ts
- packages/webpack-cli/src/types.ts
- packages/webpack-cli/src/webpack-cli.ts
- yarn.lock
fix types
No need
No need
**Summary**
Nothing
No
Webpack improve own types so we need to fix it on our side too
> chore: fix types

- packages/create-webpack-app/src/generators/loader/default.ts
- packages/webpack-cli/src/webpack-cli.ts
refactoring
no
no
**Summary**
- Use the 'String#endsWith' method instead
no
no
> refactor: use the 'String#endsWith' method instead

- packages/webpack-cli/src/plugins/cli-plugin.ts
- packages/webpack-cli/src/types.ts
refactoring
no
no
**Summary**
- remove redundant type
- fix nested template literals
no
no
> refactor: remove redundant type & fix nested template literals

- packages/create-webpack-app/src/index.ts
- packages/webpack-cli/src/webpack-cli.ts
refactoring
no
no
**Summary**
use optional chaining & delete unnecessary assertion
no
no
> refactor: use optional chaining & delete unnecessary assertion

- packages/configtest/src/index.ts
refactoring
no
no
**Summary**
change if in else to else if for better readability
no
> refactor: change if in else to else if

- package.json
- packages/webpack-cli/src/types.ts
- packages/webpack-cli/src/webpack-cli.ts
- yarn.lock
refactor + TODO for the next major release
Existing
No need
**Summary**
Refactor
No
Nothing
> Chore update webpack
